Repository Emurgo/yoroi, pull requests merged in 2021-12, with the labels that each got.

#1809 Updated send-screen according to the design
  legacy/components/Send/AmountField.js
  legacy/components/Send/SendScreen.js
  legacy/components/Send/styles/SendScreen.style.js
  legacy/components/UiKit/TextInput.js
  legacy/i18n/locales/en-US.json
Labels: UI/UX

#1804 TxHistoryListItem migrating to tx
  legacy/selectors.d.ts
  src/TxHistory/AssetList.tsx
  src/TxHistory/TxHistoryList.tsx
  src/TxHistory/TxHistoryListItem.tsx
  src/TxHistory/types.ts
  src/components/Icon/Direction.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/index.ts
  src/types/cardano.ts
  storybook/mocks.ts
Labels: refactor

#1818 feature/resync-wallet
  legacy/crypto/Wallet.js
  legacy/crypto/WalletInterface.js
  legacy/crypto/shelley/transactionCache.js
  legacy/crypto/walletManager.js
  legacy/i18n/global-messages.js
  legacy/i18n/locales/en-US.json
  src/Settings/WalletSettingsScreen.tsx
Labels: feature

#1824 [4.5.1] Fix-invalid-token
  android/app/build.gradle
  ios/Nightly-Info.plist
  ios/Staging-Info.plist
  ios/emurgo.xcodeproj/project.pbxproj
  ios/emurgo/Info.plist
  ios/emurgoTests/Info.plist
  legacy/components/Send/SendScreen.js
  src/WalletNavigator.tsx
Labels: release, hotfix

#1839 Release / 4.5.2
  android/app/build.gradle
  ios/Nightly-Info.plist
  ios/Staging-Info.plist
  ios/emurgo.xcodeproj/project.pbxproj
  ios/emurgo/Info.plist
  ios/emurgoTests/Info.plist
  legacy/components/Receive/Addresses/Modals.js
  legacy/components/Send/AssetSelectorScreen/AssetSelectorScreen.js
  legacy/components/Send/SendScreen.js
  src/TxHistory/AssetList.tsx
Labels: release
