Repository Emurgo/yoroi, pull requests merged in 2021-11, with the labels that each got.

#1757 The second update for the README.md
  README.md
Labels: docs

#1755 Adapt to ledgerjs 4.0.0 API changes
  legacy/crypto/shelley/ledgerUtils.js
  package.json
  yarn.lock
Labels: fix

#1708 Revamp assets tab
  legacy/i18n/global-messages.js
  legacy/i18n/locales/en-US.json
  legacy/selectors.d.ts
  src/assets/img/icon/asset_ada.png
  src/assets/img/icon/asset_ada@2x.png
  src/assets/img/icon/asset_ada@3x.png
  src/assets/img/icon/asset_no_image.png
  src/assets/img/icon/asset_no_image@2x.png
  src/assets/img/icon/asset_no_image@3x.png
  src/assets/img/no_transactions.png
  src/assets/img/no_transactions@2x.png
  src/assets/img/no_transactions@3x.png
  src/components/Spacer/Spacer.tsx
  src/components/Spacer/index.tsx
  src/components/TxHistory/AssetList.tsx
  src/components/TxHistory/ChipButton.stories.tsx
  src/components/TxHistory/ChipButton.tsx
  src/components/TxHistory/EmptyHistory.tsx
  src/components/TxHistory/SyncErrorBanner.tsx
  src/components/TxHistory/TxHistory.tsx
  src/components/TxHistory/TxHistoryList.tsx
  src/components/TxHistory/TxListActionsBanner.stories.tsx
  src/components/TxHistory/TxListActionsBanner.tsx
  src/components/WalletHero/ActionsBanner.tsx
  src/components/WalletHero/BalanceBanner.tsx
  src/components/WalletHero/TabNavigator.tsx
  src/components/WalletHero/WalletHero.tsx
  src/components/WalletHero/index.ts
  src/features.ts
  storybook/storyLoader.js
Labels: UI/UX

#1706 Add support for Unstoppable Domains
  legacy/components/Send/SendScreen.js
  legacy/i18n/locales/en-US.json
  legacy/utils/validators.js
  package.json
  yarn.lock
Labels: 3rd-party

#1688 New Crowdin updates
  legacy/i18n/locales/de-DE.json
Labels: chore

#1765 Fix-isInitialized-crash
  legacy/actions/history.js
  legacy/crypto/walletManager.js
Labels: bug (confirmed), fix

#1764 fix/double key creation and keyboard last line
  legacy/components/Catalyst/Step3.js
  legacy/components/Common/PinInputKeyboard.js
Labels: bug (confirmed), fix

#1766 fix/Tx details error
  legacy/components/TxHistory/TxDetails.js
Labels: bug (confirmed), fix

#1768 fix face id multiple authorization requests
  legacy/components/Send/BiometricAuthScreen.js
Labels: bug (confirmed), fix

#1776 Fix withdraw/open url button
  legacy/components/Delegation/dashboard/DelegatedStakepoolInfo.js
  legacy/components/Delegation/dashboard/UserSummary.js
Labels: fix

#1783 Transaction ui updates
  .gitignore
  legacy/components/TxHistory/TxHistoryNavigator.js
  legacy/selectors.d.ts
  src/TxHistory/ChipButton.tsx
  src/TxHistory/TxHistory.stories.tsx
  src/TxHistory/TxHistory.tsx
  src/TxHistory/TxHistoryList.tsx
  src/TxHistory/WalletHero/ActionsBanner.tsx
  src/TxHistory/WalletHero/BalanceBanner.tsx
  src/TxHistory/WalletHero/TabNavigator.tsx
  src/TxHistory/indext.tsx
Labels: chore

#1785 auto add storyLoader
  package.json
Labels: chore

#1782 Bugfix multi taps on catalyst app download
  legacy/components/Catalyst/Step1.js
Labels: bug (confirmed), fix

#1794 Bump detox e2e
  e2e/config.json
  e2e/environment.js
  package.json
  yarn.lock
Labels: chore

#1797 [fix] Reverting detox due to building issues
  package.json
  yarn.lock
Labels: fix

#1802 Bump @unstoppabledomains/resolution to v6.0.3
  package.json
  yarn.lock
Labels: 3rd-party

#1801 migrate logout to react-query
  src/Settings/WalletSettingsScreen.tsx
Labels: fix
