Repository Emurgo/yoroi, pull requests merged in 2022-09, with the labels that each got.

#2124 chore: Increase storage for big wallets
  android/gradle.properties
Labels: chore

#2123 upgrade to cross-csl
  jestSetup.ts
  package.json
  src/Send/SendScreen/utils.ts
  src/Staking/StakingCenter/StakingCenter.tsx
  src/WalletInit/VerifyRestoredWallet/VerifyRestoredWalletScreen.tsx
  src/appStorage.ts
  src/components/ConfirmTx/ConfirmTx.tsx
  src/legacy/commonUtils.ts
  src/legacy/ledgerUtils.ts
  src/legacy/state.ts
  src/legacy/types.ts
  src/legacy/utils.ts
  src/yoroi-wallets/Wallet.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/addressInfo.test.ts
  src/yoroi-wallets/cardano/addressInfo.ts
  src/yoroi-wallets/cardano/assetUtils.ts
  src/yoroi-wallets/cardano/bip44Validators.ts
  src/yoroi-wallets/cardano/byron/plate.ts
  src/yoroi-wallets/cardano/byron/util.ts
  src/yoroi-wallets/cardano/catalyst/catalystUtils.ts
  src/yoroi-wallets/cardano/chain.ts
  src/yoroi-wallets/cardano/index.ts
  src/yoroi-wallets/cardano/shelley/delegationUtils.ts
  src/yoroi-wallets/cardano/shelley/plate.ts
  src/yoroi-wallets/cardano/signedTx.ts
  src/yoroi-wallets/cardano/types.ts
  src/yoroi-wallets/cardano/unsignedTx.test.ts
  src/yoroi-wallets/cardano/unsignedTx.ts
  src/yoroi-wallets/types.ts
  storybook/storyLoader.js
  yarn.lock
Labels: refactor

#2135 fix: WR wrap padding bug
  src/WalletInit/MnemonicCheck/MnemonicCheckScreen.tsx
Labels: fix

#2133 Remove redux from hooks
  src/Catalyst/Step4.tsx
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithOS.tsx
  src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
  src/Settings/WalletSettings/WalletSettingsScreen.tsx
  src/hooks/index.ts
  src/legacy/actions.ts
Labels: refactor

#2141 remove FC type
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTx.tsx
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithHW.tsx
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithOS.tsx
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithPassword.tsx
  src/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  src/FirstRun/LanguagePickerScreen/LanguagePickerScreen.tsx
  src/Screen.tsx
  src/SelectedWallet/Context/SelectedWalletContext.tsx
  src/SelectedWallet/Context/SelectedWalletMetaContext.tsx
  src/Send/AddressReaderQR/AddressReaderQR.tsx
  src/Send/Context/SendContext.tsx
  src/Settings/Currency/CurrencyContext.tsx
  src/Storage/StorageProvider.tsx
  src/TxHistory/ModalInfo/ModalInfo.tsx
  src/TxHistory/TxHistory.tsx
  src/WalletInit/WalletAddress/FadeOutView.tsx
  src/WalletInit/WalletFreshInit/WalletFreshInitScreen.tsx
  src/auth/CreatePinInput/CreatePinInput.tsx
  src/components/Banner/Banner.tsx
  src/components/Boundary/Boundary.stories.tsx
  src/components/Boundary/Boundary.tsx
  src/components/ConfirmTx/ConfirmTx.tsx
  src/components/ConfirmTx/Dialog.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/TextInput/TextInput.tsx
  src/i18n/LanguageProvider.tsx
  src/theme/Palette.stories.tsx
  src/theme/ThemeProvider.tsx
  src/theme/Typography.stories.tsx
Labels: refactor

#2142 remove hwDeviceInfo from redux
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithHW.tsx
  src/components/ConfirmTx/ConfirmTx.tsx
  src/legacy/history.ts
  src/legacy/hwWallet.ts
  src/legacy/mockWallet.ts
  src/legacy/selectors.ts
  src/legacy/state.ts
  src/yoroi-wallets/hwWallet.ts
  src/yoroi-wallets/walletManager.ts
Labels: refactor

#2143 Remove-auth-redux
  package.json
  src/App.tsx
  src/AppNavigator.tsx
  src/FirstRun/FirstRunNavigator.tsx
  src/FirstRun/TermsOfServiceScreen/TermsOfServiceScreen.tsx
  src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
  src/Settings/WalletSettings/WalletSettingsScreen.tsx
  src/auth/AuthProvider.tsx
  src/auth/PinLoginScreen/PinLoginScreen.tsx
  src/auth/backgroundTimeout.stories.tsx
  src/auth/backgroundTimeout.ts
  src/auth/index.ts
  src/legacy/actions.ts
  src/legacy/backgroundLockHelper.ts
  src/legacy/config.ts
  src/legacy/selectors.ts
  src/legacy/state.ts
  src/yoroi-wallets/index.ts
  storybook/storyLoader.js
  yarn.lock
Labels: refactor

#2146 Choose transport on send transaction confirmation
  src/Send/ConfirmScreen/ConfirmScreen.tsx
Labels: fix

#2149 Remove wallet refactor
  src/Settings/RemoveWallet/RemoveWalletScreen.tsx
  src/hooks/index.ts
  src/yoroi-wallets/walletManager.ts
Labels: fix

#2152 fix withdrawal loading
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithHW.tsx
  src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.stories.tsx
  src/components/ConfirmTx/ConfirmTx.tsx
  src/components/TwoActionView/TwoActionView.tsx
  src/legacy/hwWallet.ts
  src/yoroi-wallets/hwWallet.ts
  src/yoroi-wallets/index.ts
  src/yoroi-wallets/walletManager.ts
  storybook/decorators/index.ts
  storybook/mocks/index.ts
  storybook/mocks/storage.ts
  storybook/mocks/wallet.ts
  storybook/storyLoader.js
Labels: fix

#2156 fix boundary style, move balances
  src/Send/AssetSelectorScreen/AssetSelectorScreen.stories.tsx
  src/Send/AssetSelectorScreen/AssetSelectorScreen.tsx
  src/TxHistory/TxHistoryNavigator.tsx
  src/components/Boundary/Boundary.tsx
Labels: fix

#2160 Close wallet when going to wallet list
  src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
  src/Settings/WalletSettings/WalletSettingsScreen.tsx
  src/legacy/DeveloperScreen.tsx
  src/navigation.ts
Labels: fix

#2151 Remove last redux stuff from hooks
  src/Settings/RemoveWallet/RemoveWalletScreen.tsx
  src/hooks/index.ts
Labels: refactor
