Repository Emurgo/yoroi, pull requests merged in 2022-06, with the labels that each got.

#1996 4.7.15-rc.1
  android/app/build.gradle
  ios/emurgo.xcodeproj/project.pbxproj
  legacy/actions.js
  legacy/components/Ledger/DeviceItem/DeviceItem.js
  legacy/components/Ledger/LedgerConnect.js
  legacy/components/Send/BiometricAuthScreen.stories.js
  legacy/components/UiKit/PleaseWaitModal.js
  legacy/i18n/locales/en-US.json
  package.json
  src/AppNavigator.tsx
  src/Dashboard/Dashboard.tsx
  src/Dashboard/StakePoolInfo.tsx
  src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  src/Menu/Menu.tsx
  src/Receive/AddressVerifyModal.tsx
  src/SelectedWallet/WalletSelection/WalletListItem.tsx
  src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
  src/Send/ConfirmScreen/ConfirmScreen.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/TxHistory/TxHistoryNavigator.tsx
  src/WalletInit/WalletCredentials/WalletCredentialsScreen.tsx
  src/WalletInit/WalletNameForm/WalletNameForm.tsx
  src/assets/img/icon/shape.png
  src/index.tsx
  src/navigation.ts
Labels: release

#2012 UI_V2 flag, ts issues
  src/.eslintrc.js
  src/Dashboard/Dashboard.tsx
  src/Dashboard/DashboardNavigator.tsx
  src/Receive/ReceiveScreen.tsx
  src/Send/ScannerButton.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/TxHistory/AssetList/AssetList.tsx
  src/TxHistory/BalanceBanner.tsx
  src/TxHistory/TxDetails/AssetList.tsx
  src/TxHistory/TxHistory.tsx
  src/TxHistory/TxHistoryNavigator.tsx
  src/WalletNavigator.tsx
  src/components/Boundary/Boundary.tsx
  src/components/ConfirmTx/ConfirmTx.tsx
  src/legacy/config.ts
Labels: chore

#2014 chore: Tx sync minor improvement
  ios/Podfile.lock
  src/TxHistory/TxDetails/TxDetails.tsx
  src/TxHistory/TxHistoryList/TxHistoryList.tsx
  src/TxHistory/TxHistoryList/TxHistoryListItem.tsx
  src/hooks/index.ts
  src/legacy/HistoryTransaction.ts
  src/legacy/api.test.ts
  src/legacy/api.ts
  src/legacy/errors.ts
  src/legacy/facade.test.ts
  src/legacy/facade.ts
  src/legacy/fetch.ts
  src/legacy/processTransactions.test.ts
  src/legacy/processTransactions.ts
  src/legacy/selectors.test.ts
  src/legacy/types.ts
  src/yoroi-wallets/Wallet.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/shelley/transactionCache.test.ts
  src/yoroi-wallets/cardano/shelley/transactionCache.ts
  src/yoroi-wallets/cardano/types.ts
  storybook/mocks/transaction.ts
  storybook/mocks/wallet.ts
Labels: chore

#2021 fix: Send token stuck
  src/hooks/index.ts
Labels: fix

#2020 feature: Currency pairing
  src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  src/Settings/ChangeLanguage/ChangeLanguageScreen.tsx
  src/Settings/Currency/ChangeCurrencyScreen.stories.tsx
  src/Settings/Currency/ChangeCurrencyScreen.tsx
  src/Settings/Currency/CurrencyContext.tsx
  src/Settings/Currency/CurrencyPickerItem.tsx
  src/Settings/Currency/CurrencyPickerList.tsx
  src/Settings/Currency/index.ts
  src/Settings/SettingsScreenNavigator.tsx
  src/TxHistory/BalanceBanner.tsx
  src/hooks/index.ts
  src/i18n/global-messages.ts
  src/i18n/locales/en-US.json
  src/index.tsx
  src/legacy/api.ts
  src/legacy/types.ts
  src/navigation.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/types.ts
  storybook/mocks/wallet.ts
  storybook/storyLoader.js
Labels: feature

#2026 Fix pin nav
  src/AppNavigator.tsx
  src/FirstRun/FirstRunNavigator.tsx
  src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
  src/hooks/index.ts
  src/legacy/DeveloperScreen.tsx
  src/legacy/actions.ts
  src/navigation.ts
Labels: fix, chore

#2025 [YOMO-179] Language selector revamp
  package.json
  src/FirstRun/FirstRunNavigator.tsx
  src/FirstRun/LanguagePickerScreen/LanguagePickerScreen.tsx
  src/Settings/Currency/CurrencyPickerItem.tsx
  src/Settings/SettingsScreenNavigator.tsx
  src/components/Icon/Check.tsx
  src/components/Icon/Cross.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/Magnify.tsx
  src/components/LanguagePicker/LanguageListItem.tsx
  src/components/LanguagePicker/LanguagePicker.stories.tsx
  src/components/LanguagePicker/LanguagePicker.tsx
  src/components/LanguagePicker/LanguagePickerWarning.stories.tsx
  src/components/LanguagePicker/LanguagePickerWarning.tsx
  src/components/TextInput/TextInput.tsx
  src/i18n/global-messages.ts
  src/i18n/locales/en-US.json
  storybook/storyLoader.js
Labels: chore

#2031 Dev test cleanup
  src/Receive/ReceiveScreenNavigator.tsx
  src/Receive/index.ts
  src/Send/SendScreenNavigator.tsx
  src/Send/index.ts
  src/TxHistory/TxHistory.tsx
  src/TxHistory/TxHistoryNavigator.tsx
  src/legacy/DeveloperScreen.tsx
  src/legacy/actions.ts
  src/yoroi-wallets/walletManager.ts
Labels: chore

#1990 Update installation instructions MAC users
  README.md
Labels: docs
