Repository Emurgo/yoroi, pull requests merged in 2022-12, with the labels that each got.

#2249 Chore/bump lib 2
  package.json
  yarn.lock
Labels: chore

#2248 Fix stuck anim
  package.json
  src/AppNavigator.tsx
  src/Settings/SettingsItems.tsx
  src/WalletInit/WalletInitNavigator.tsx
  src/legacy/DeveloperScreen.tsx
  yarn.lock
Labels: fix

#2244 fix: ledger connection
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  package.json
  src/AppNavigator.tsx
  src/HW/LedgerConnect/LedgerConnect.tsx
  src/HW/LedgerTransportSwitchModal/LedgerTransportSwitchModal.tsx
  src/Settings/SettingsItems.tsx
  src/WalletInit/WalletInitNavigator.tsx
  src/i18n/locales/en-US.json
  src/legacy/DeveloperScreen.tsx
  src/legacy/ledgerUtils.ts
  yarn.lock
Labels: fix

#2250 Fix/libwind hack
  android/build.gradle
Labels: fix

#2258 Fix Ledger bluetooth connection handler
  src/HW/LedgerConnect/DeviceItem/DeviceItem.stories.tsx
  src/HW/LedgerConnect/DeviceItem/DeviceItem.tsx
  src/HW/LedgerConnect/LedgerConnect.tsx
  src/WalletInit/ConnectNanoX/ConnectNanoXScreen.tsx
Labels: fix

#2263 Bump lib to 0.3
  package.json
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  yarn.lock
Labels: chore

#2264 fix: trans key
  src/i18n/global-messages.ts
  src/i18n/locales/en-US.json
Labels: fix

#2259 Missing receive addresses on wallet restoring fix
  src/Receive/Addresses.tsx
  src/TxHistory/ActionsBanner.tsx
  src/TxHistory/TxHistory.tsx
  src/hooks/index.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
Labels: fix

#2268 Tx list item layout fix
  src/TxHistory/TxHistoryList/TxHistoryListItem.tsx
Labels: fix

#2274 Tx list screen issues fix improvement
  src/TxHistory/CollapsibleHeader.tsx
Labels: fix

#2279 chore: new pool hash preprod
  src/legacy/config.ts
Labels: chore

#2286 remove redux
  README.md
  package.json
  src/App.tsx
  src/Dashboard/Dashboard.stories.tsx
  src/WalletInit/WalletNameForm/WalletNameForm.tsx
  src/index.tsx
  src/legacy/actions.ts
  src/legacy/appSettings.ts
  src/legacy/configureStore.ts
  src/legacy/reduxTypes.ts
  src/legacy/rootReducer.ts
  src/legacy/selectors.ts
  src/legacy/state.ts
  src/legacy/subscription.ts
  src/legacy/utils.ts
  src/yoroi-wallets/cardano/types.ts
  storybook/README.md
  storybook/decorators/index.ts
  storybook/decorators/redux.tsx
  storybook/index.ts
  tsconfig.json
  yarn.lock
Labels: refactor
