Repository Emurgo/yoroi, pull requests merged in 2022-07, with the labels that each got.

#2035 4.7.17-rc.1
  android/app/build.gradle
  ios/emurgo.xcodeproj/project.pbxproj
  src/Staking/StakingCenter/StakingCenter.tsx
Labels: release, fix

#2047 Moved pool info to the new endpoint
  src/legacy/api.ts
Labels: chore

#2063 Remove-unused-code-01
  .gitignore
  package.json
  src/AccountAutoRefresher.tsx
  src/Catalyst/Step5.tsx
  src/Catalyst/hooks.ts
  src/Dashboard/Dashboard.tsx
  src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  src/Receive/AddressModal.stories.tsx
  src/Receive/AddressModal.tsx
  src/Send/ConfirmScreen/ConfirmScreen.tsx
  src/Send/SendScreen/ErrorBanners.tsx
  src/Send/SendScreen/Fee.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/Send/SendScreen/utils.ts
  src/Settings/RemoveWallet/RemoveWalletScreen.tsx
  src/Settings/ToggleEasyConfirmation/ToggleEasyConfirmationScreen.tsx
  src/Settings/WalletSettings/WalletSettingsScreen.tsx
  src/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  src/Staking/StakingCenter/StakingCenter.tsx
  src/TxHistory/ActionsBanner.tsx
  src/TxHistory/TxHistory.tsx
  src/TxHistory/TxHistoryList/TxHistoryListItem.tsx
  src/UtxoAutoRefresher.tsx
  src/components/OfflineBanner/OfflineBanner.tsx
  src/hooks/index.ts
  src/legacy/account.ts
  src/legacy/actions.ts
  src/legacy/history.ts
  src/legacy/hwWallet.ts
  src/legacy/networkInfo.ts
  src/legacy/pools.ts
  src/legacy/selectors.ts
  src/legacy/state.ts
  src/legacy/tokenInfo.ts
  src/legacy/utxo.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/types.ts
  src/yoroi-wallets/walletManager.ts
  yarn.lock
Labels: refactor

#2084 fix: Display path
  src/Receive/AddressModal.stories.tsx
  src/Receive/AddressModal.tsx
  src/Receive/Modals.tsx
Labels: fix

#2082 fix: Cleaning the pin input when the error dialog is closed
  src/auth/CheckPinInput/CheckPinInput.tsx
  src/auth/CreatePinInput/CreatePinInput.tsx
  src/auth/PinInput/PinInput.stories.tsx
  src/auth/PinInput/PinInput.tsx
  src/auth/PinLoginScreen/PinLoginScreen.tsx
  storybook/storyLoader.js
Labels: fix

#2083 fix: Display keyhashes
  ios/Podfile.lock
  src/Receive/AddressModal.tsx
  src/yoroi-wallets/cardano/Address.dto.test.ts
  src/yoroi-wallets/cardano/Address.dto.ts
  src/yoroi-wallets/cardano/AddressInterface.ts
  src/yoroi-wallets/cardano/addressInfo.test.ts
  src/yoroi-wallets/cardano/addressInfo.ts
  src/yoroi-wallets/cardano/index.ts
Labels: fix

#2088 fix: Dashboard crashing
  src/Dashboard/EpochProgress.tsx
  src/Dashboard/StakePoolInfo.tsx
  src/TxHistory/TxDetails/TxDetails.tsx
  src/components/Modal/Modal.tsx
Labels: fix
