Repository Emurgo/yoroi, pull requests merged in 2022-11, with the labels that each got.

#2199 fix tx cache, storage
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/shelley/transactionCache.test.ts
  src/yoroi-wallets/cardano/shelley/transactionCache.ts
  src/yoroi-wallets/storage.ts
Labels: fix

#2198 Clear txs on resync and remove wallet
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/shelley/transactionCache.test.ts
  src/yoroi-wallets/cardano/shelley/transactionCache.ts
  src/yoroi-wallets/storage.ts
Labels: chore

#2200 Android build fix
  package.json
  yarn.lock
Labels: fix

#2197 Wallet resync does nothing
  src/Settings/WalletSettings/WalletSettingsScreen.tsx
  src/hooks/index.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/types.ts
  src/yoroi-wallets/walletManager.ts
  storybook/mocks/wallet.ts
Labels: fix

#2206 enable crash reporting on nightly
  src/hooks/index.ts
  src/legacy/actions.ts
  src/legacy/appSettings.ts
  src/legacy/state.ts
  src/yoroi-wallets/utils/parsing.ts
Labels: chore

#2207 prevent withdrawal with no rewards
  src/Dashboard/StakePoolInfos.tsx
  src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.stories.tsx
  src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  src/components/DangerousActionModal/DangerousActionModal.tsx
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/shelley/delegationUtils.ts
  src/yoroi-wallets/cardano/types.ts
  src/yoroi-wallets/types/staking.ts
  src/yoroi-wallets/walletManager.ts
  storybook/mocks/storage.ts
  storybook/mocks/wallet.ts
Labels: fix

#2208 chore: clean up state
  src/legacy/appSettings.ts
  src/legacy/state.ts
Labels: chore

#2205 merge wallet, shelley wallet
  src/Settings/ChangePassword/ChangePasswordScreen.tsx
  src/yoroi-wallets/Wallet.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/types.ts
  src/yoroi-wallets/index.ts
  src/yoroi-wallets/walletManager.ts
Labels: chore

#2209 Receive component refactor to get new addresses
  src/Receive/Addresses.tsx
  src/Receive/ReceiveScreen.tsx
  src/Settings/WalletSettings/WalletSettingsScreen.tsx
  src/hooks/index.ts
  src/legacy/actions.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/types.ts
  src/yoroi-wallets/cardano/utxoStorage.ts
  src/yoroi-wallets/walletManager.ts
  storybook/mocks/wallet.ts
Labels: fix

#2210 Create wallet form background fix
  src/WalletInit/CreateWallet/CreateWalletScreen.tsx
  src/WalletInit/WalletForm.tsx
Labels: fix

#2216 fix: bool conversion
  src/auth/authOS.test.ts
  src/auth/authOS.ts
  src/hooks/index.ts
Labels: fix

#2213 Auth with OS error
  android/build.gradle
  ios/emurgo.xcodeproj/project.pbxproj
  ios/fastlane/README.md
  src/AppNavigator.tsx
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithOS.tsx
  src/FirstRun/TermsOfServiceScreen/TermsOfServiceScreen.tsx
  src/OsAuth/index.ts
  src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  src/Settings/EnableLoginWithOs/EnableLoginWithOsScreen.tsx
  src/Settings/WalletSettings/WalletSettingsScreen.tsx
  src/Settings/index.ts
  src/Settings/types.ts
  src/Storage/StorageProvider.tsx
  src/Storage/index.ts
  src/Storage/migrations/4_9_0.test.ts
  src/Storage/migrations/4_9_0.ts
  src/Storage/migrations/hooks.ts
  src/Storage/migrations/walletMeta.test.ts
  src/Storage/migrations/walletMeta.ts
  src/auth/CheckPinInput/CheckPinInput.tsx
  src/auth/CreatePinInput/CreatePinInput.tsx
  src/auth/EnableLoginWithPin.tsx
  src/auth/Keychain.ts
  src/auth/KeychainStorage.ts
  src/auth/OsAuthScreen/OsAuthScreen.stories.tsx
  src/auth/OsAuthScreen/OsAuthScreen.tsx
  src/auth/OsAuthScreen/index.ts
  src/auth/OsLoginScreen/OsLoginScreen.stories.tsx
  src/auth/OsLoginScreen/OsLoginScreen.tsx
  src/auth/OsLoginScreen/index.ts
  src/auth/PinLoginScreen/PinLoginScreen.tsx
  src/auth/authError.ts
  src/auth/authOS.ts
  src/auth/hooks.ts
  src/auth/index.ts
  src/components/ConfirmTx/ConfirmTx.tsx
  src/hooks/index.ts
  src/i18n/locales/en-US.json
  src/index.tsx
  src/legacy/actions.ts
  src/yoroi-wallets/walletManager.ts
  storybook/storyLoader.js
Labels: fix, chore

#2214 Mnemonic fix to avoid submitting weird input values
  src/WalletInit/MnemonicInput/MnemonicInput.tsx
Labels: fix

#2218 chore: bumps
  android/build.gradle
  ios/emurgo.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: chore

#2219 Set migration to run always
  ios/emurgo.xcodeproj/project.pbxproj
  src/Storage/migrations/hooks.ts
Labels: fix

#2222 fix offline errors
  ios/Podfile.lock
  jestSetup.ts
  package.json
  src/Catalyst/ConfirmVotingTx.tsx
  src/Dashboard/Dashboard.tsx
  src/Menu/Menu.tsx
  src/Receive/ReceiveScreen.tsx
  src/Send/ConfirmScreen/ConfirmScreen.tsx
  src/Send/SendScreen/ErrorBanners.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  src/TxHistory/TxDetails/TxDetails.tsx
  src/TxHistory/TxHistory.tsx
  src/WalletNavigator.tsx
  src/components/Boundary/Boundary.tsx
  src/components/OfflineBanner/OfflineBanner.tsx
  src/hooks/index.ts
  yarn.lock
Labels: fix, refactor

#2220 Cleanup
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/api.ts
  src/yoroi-wallets/cardano/types.ts
  src/yoroi-wallets/types/other.ts
Labels: chore

#2228 fix withdraw error
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithHW.stories.tsx
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithHW.tsx
  src/HW/LedgerConnect/LedgerConnect.tsx
  storybook/mocks/wallet.ts
Labels: fix

#2231 Cleanup-mocks-2
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithHW.stories.tsx
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithOS.stories.tsx
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithPassword.stories.tsx
  src/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.stories.tsx
  src/Send/ConfirmScreen/ConfirmScreen.stories.tsx
  src/Staking/DelegationConfirmation/DelegationConfirmation.stories.tsx
  storybook/mocks/wallet.ts
Labels: refactor

#2233 Utxo Manager
  src/Dashboard/Dashboard.tsx
  src/Dashboard/StakePoolInfos.tsx
  src/Send/SendScreen/ErrorBanners.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/TxHistory/LockedDeposit.tsx
  src/TxHistory/TxHistory.stories.tsx
  src/hooks/index.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/types.ts
  src/yoroi-wallets/cardano/utxoManager.ts
  src/yoroi-wallets/cardano/utxoStorage.ts
  src/yoroi-wallets/walletManager.ts
  storybook/mocks/wallet.ts
Labels: fix

#2234 Workaround - render issue
  src/HW/LedgerConnect/LedgerConnect.tsx
Labels: fix

#2239 Fix open wallet loading dialog on ios
  src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
Labels: fix

#2243 Fix hook in wrong place
  src/AppNavigator.tsx
Labels: chore

#2242 chore: target sdk 31
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
Labels: chore

#2246 prevent readonly wallets from voting
  src/Catalyst/VotingBanner.tsx
  src/Catalyst/hooks.ts
  src/Menu/Menu.stories.tsx
  src/Menu/Menu.tsx
  storybook/mocks/wallet.ts
Labels: fix

#2245 remove instructions
  src/Send/ConfirmScreen/ConfirmScreen.tsx
Labels: chore
