Repository Emurgo/yoroi, pull requests merged in 2022-08, with the labels that each got.

#2096 chore: Lint improvements
  .eslintrc.js
  package.json
  src/AccountAutoRefresher.tsx
  src/App.tsx
  src/AppNavigator.tsx
  src/BiometricAuth/BiometricAuthScreen.tsx
  src/Catalyst/Step4.tsx
  src/Dashboard/Dashboard.tsx
  src/Dashboard/StakePoolInfo.tsx
  src/HW/LedgerConnect/LedgerConnect.tsx
  src/Legal/TermsOfService/TermsOfService.tsx
  src/Menu/Menu.tsx
  src/Receive/Addresses.tsx
  src/Receive/ReceiveScreen.tsx
  src/SelectedWallet/WalletSelection/WalletListItem.tsx
  src/Send/AmountField.tsx
  src/Send/AssetSelectorScreen/AssetSelectorScreen.tsx
  src/Send/SendScreen/AvailableAmountBanner.tsx
  src/Send/SendScreen/ErrorBanners.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  src/Settings/ChangeWalletName/ChangeWalletName.tsx
  src/Settings/Currency/CurrencyContext.tsx
  src/Settings/PrivacyMode/PrivacyMode.tsx
  src/Settings/ToggleEasyConfirmation/ToggleEasyConfirmationScreen.tsx
  src/Settings/WalletSettings/WalletSettingsScreen.tsx
  src/Staking/StakingCenter/StakingCenter.tsx
  src/TxHistory/AssetList/AssetList.tsx
  src/TxHistory/BalanceBanner.tsx
  src/TxHistory/LockedDeposit.tsx
  src/TxHistory/TxDetails/AssetList.tsx
  src/TxHistory/TxDetails/TxDetails.tsx
  src/TxHistory/TxHistoryList/TxHistoryListItem.tsx
  src/TxHistory/WarningBanner.tsx
  src/UtxoAutoRefresher.tsx
  src/WalletInit/CreateWallet/CreateWalletScreen.tsx
  src/WalletInit/MnemonicInput/MnemonicInput.tsx
  src/WalletInit/MnemonicShow/MnemonicShowScreen.tsx
  src/WalletInit/RestoreWallet/RestoreWalletScreen.tsx
  src/WalletInit/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.tsx
  src/WalletInit/WalletForm.tsx
  src/WalletInit/WalletNameForm/WalletNameForm.tsx
  src/components/Boundary/Boundary.tsx
  src/components/ConfirmTx/ConfirmTx.tsx
  src/components/DangerousActionModal/DangerousActionModal.tsx
  src/components/ErrorModal/ErrorModal.stories.tsx
  src/components/ErrorModal/ErrorModal.tsx
  src/components/Icon/WalletAccount.tsx
  src/components/Modal/Modal.tsx
  src/components/Text.tsx
  src/components/TextInput/TextInput.tsx
  src/components/ValidatedTextInput.tsx
  src/i18n/LanguageProvider.tsx
  src/index.tsx
  src/legacy/DeveloperScreen.tsx
  src/legacy/deviceSettings.ts
  src/legacy/utils.ts
  src/theme/ThemeProvider.tsx
  src/yoroi-wallets/cardano/shelley/transactionCache.ts
  yarn.lock
Labels: chore

#2100 Removing exponential formatting for large numbers
  src/Send/AssetSelectorScreen/AssetSelectorScreen.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/TxHistory/AssetList/AssetList.tsx
  src/TxHistory/TxDetails/AssetList.tsx
  src/legacy/format.ts
Labels: fix

#2102 Fix: RN key
  src/WalletInit/CheckNanoX/CheckNanoXScreen.tsx
Labels: fix

#2103 chore: Adapted word list same behavior ext
  src/WalletInit/MnemonicInput/MnemonicInput.tsx
Labels: chore

#2106 Fix: Loader icon is stuck
  src/TxHistory/TxHistoryList/TxHistoryList.tsx
Labels: fix

#2101 Fix: Wallet name suggestion for ledger
  src/WalletInit/SaveNanoX/SaveNanoXScreen.tsx
  src/WalletInit/WalletNameForm/WalletNameForm.tsx
  src/i18n/locales/en-US.json
  src/legacy/config.ts
Labels: fix

#2105 Fix: Add showErrorOnBlur feature to textInput component
  src/WalletInit/WalletForm.tsx
  src/components/TextInput/TextInput.tsx
Labels: fix

#2107 New Crowdin updates
  src/i18n/locales/cs-CZ.json
  src/i18n/locales/de-DE.json
  src/i18n/locales/el-GR.json
  src/i18n/locales/es-ES.json
  src/i18n/locales/fr-FR.json
  src/i18n/locales/hr-HR.json
  src/i18n/locales/hu-HU.json
  src/i18n/locales/id-ID.json
  src/i18n/locales/it-IT.json
  src/i18n/locales/ja-JP.json
  src/i18n/locales/ko-KR.json
  src/i18n/locales/nl-NL.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/ru-RU.json
  src/i18n/locales/sk-SK.json
  src/i18n/locales/tr-TR.json
  src/i18n/locales/zh-Hans.json
  src/i18n/locales/zh-Hant.json
Labels: chore

#2099 Yomo 307 send feature isolate data 3
  src/Send/AddressReaderQR/AddressReaderQR.stories.tsx
  src/Send/AddressReaderQR/AddressReaderQR.tsx
  src/Send/AssetSelectorScreen/AssetSelectorScreen.stories.tsx
  src/Send/AssetSelectorScreen/AssetSelectorScreen.tsx
  src/Send/ConfirmScreen/ConfirmScreen.stories.tsx
  src/Send/ConfirmScreen/ConfirmScreen.tsx
  src/Send/Context/SendContext.tsx
  src/Send/SendScreen/SendScreen.stories.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/TxHistory/ActionsBanner.tsx
  src/TxHistory/TxHistoryNavigator.tsx
  storybook/index.ts
  storybook/mocks/index.ts
  storybook/mocks/wallet.ts
Labels: refactor

#2095 Refactor Send feature to use YoroiAmounts
  src/Send/AddressReaderQR/AddressReaderQR.stories.tsx
  src/Send/AddressReaderQR/AddressReaderQR.tsx
  src/Send/AssetSelectorScreen/AssetSelectorScreen.stories.tsx
  src/Send/AssetSelectorScreen/AssetSelectorScreen.tsx
  src/Send/ConfirmScreen/ConfirmScreen.stories.tsx
  src/Send/ConfirmScreen/ConfirmScreen.tsx
  src/Send/Context/SendContext.tsx
  src/Send/SendScreen/BalanceAfterTransaction.tsx
  src/Send/SendScreen/Fee.tsx
  src/Send/SendScreen/SendScreen.stories.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/Send/SendScreen/utils.ts
  src/TxHistory/ActionsBanner.tsx
  src/TxHistory/TxHistoryNavigator.tsx
  src/hooks/index.ts
  src/navigation.ts
  src/yoroi-wallets/utils.test.ts
  src/yoroi-wallets/utils.ts
  storybook/index.ts
  storybook/mocks/index.ts
  storybook/mocks/wallet.ts
Labels: refactor

#2110 chore: Bump rnhs@3.1.4
  package.json
  yarn.lock
Labels: chore

#2112 fix: Lib methods signature
  src/yoroi-wallets/cardano/byron/util.ts
Labels: fix

#2115 chore: Update Podfile
  ios/Podfile.lock
Labels: chore

#2098 Denis/intrawallet tx asset
  src/Dashboard/Dashboard.tsx
  src/Dashboard/EpochProgress.tsx
  src/Dashboard/NotDelegatedInfo.tsx
  src/Dashboard/StakePoolInfo.tsx
  src/Dashboard/UserSummary.tsx
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithPassword.tsx
  src/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  src/Send/AssetSelectorScreen/AssetSelectorScreen.tsx
  src/Send/SendScreen/BalanceAfterTransaction.tsx
  src/Send/SendScreen/Fee.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  src/Staking/PoolDetails/PoolDetailScreen.tsx
  src/TxHistory/AssetList/AssetList.tsx
  src/TxHistory/TxHistory.tsx
  src/TxHistory/TxHistoryList/EmptyHistory.tsx
  src/TxHistory/TxHistoryList/TxHistoryList.tsx
  src/TxHistory/TxHistoryList/TxHistoryListItem.tsx
  src/components/DangerousActionModal/DangerousActionModal.tsx
  src/components/TitledCard.tsx
  src/components/TwoActionView/TwoActionView.tsx
  tests/config/testPaths.ts
  tests/config/wdio.android.local.conf.ts
  tests/constants.ts
  tests/helpers/utils.ts
  tests/screenFunctions/common.screenFunctions.ts
  tests/screenFunctions/myWallet.screenFunctions.ts
  tests/screenFunctions/prepare.screenFunctions.ts
  tests/screenFunctions/send.screenFunctions.ts
  tests/screenFunctions/walletHistory.screenFunctions.ts
  tests/screenObjects/addWallets.screen.ts
  tests/screenObjects/connectLedgerScreens/connectToLedgerDevice.screen.ts
  tests/screenObjects/createWalletScreens/createWalletCredentials.screen.ts
  tests/screenObjects/createWalletScreens/recoveryPhraseEnter.screen.ts
  tests/screenObjects/receive.screen.ts
  tests/screenObjects/send.screen.ts
  tests/screenObjects/stakingScreens/confirmDelegating.screen.ts
  tests/screenObjects/stakingScreens/confirmWithdrawTransaction.screen.ts
  tests/screenObjects/stakingScreens/stakingCenter.screen.ts
  tests/screenObjects/stakingScreens/stakingDashboard.screen.ts
  tests/screenObjects/stakingScreens/withdrawWarning.screen.ts
  tests/screenObjects/walletHistory.screen.ts
  tests/specs/happyPaths.shelley.15.test.ts
  tests/specs/local.ledger.test.ts
Labels: chore

#2116 Bring 4.8.0-rc.2
  src/Dashboard/Dashboard.tsx
  src/Dashboard/EpochProgress.tsx
  src/Dashboard/NotDelegatedInfo.tsx
  src/Dashboard/StakePoolInfo.tsx
  src/Dashboard/UserSummary.tsx
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithPassword.tsx
  src/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  src/Send/AssetSelectorScreen/AssetSelectorScreen.tsx
  src/Send/SendScreen/BalanceAfterTransaction.tsx
  src/Send/SendScreen/Fee.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  src/Staking/PoolDetails/PoolDetailScreen.tsx
  src/TxHistory/AssetList/AssetList.tsx
  src/TxHistory/TxHistory.tsx
  src/TxHistory/TxHistoryList/EmptyHistory.tsx
  src/TxHistory/TxHistoryList/TxHistoryList.tsx
  src/TxHistory/TxHistoryList/TxHistoryListItem.tsx
  src/components/DangerousActionModal/DangerousActionModal.tsx
  src/components/TitledCard.tsx
  src/components/TwoActionView/TwoActionView.tsx
  tests/config/testPaths.ts
  tests/config/wdio.android.local.conf.ts
  tests/constants.ts
  tests/helpers/utils.ts
  tests/screenFunctions/common.screenFunctions.ts
  tests/screenFunctions/myWallet.screenFunctions.ts
  tests/screenFunctions/prepare.screenFunctions.ts
  tests/screenFunctions/send.screenFunctions.ts
  tests/screenFunctions/walletHistory.screenFunctions.ts
  tests/screenObjects/addWallets.screen.ts
  tests/screenObjects/connectLedgerScreens/connectToLedgerDevice.screen.ts
  tests/screenObjects/createWalletScreens/createWalletCredentials.screen.ts
  tests/screenObjects/createWalletScreens/recoveryPhraseEnter.screen.ts
  tests/screenObjects/receive.screen.ts
  tests/screenObjects/send.screen.ts
  tests/screenObjects/stakingScreens/confirmDelegating.screen.ts
  tests/screenObjects/stakingScreens/confirmWithdrawTransaction.screen.ts
  tests/screenObjects/stakingScreens/stakingCenter.screen.ts
  tests/screenObjects/stakingScreens/stakingDashboard.screen.ts
  tests/screenObjects/stakingScreens/withdrawWarning.screen.ts
  tests/screenObjects/walletHistory.screen.ts
  tests/specs/happyPaths.shelley.15.test.ts
  tests/specs/local.ledger.test.ts
Labels: chore

#2114 fix: Clipped views
  src/TxHistory/TxHistoryList/TxHistoryList.tsx
  src/TxHistory/TxHistoryList/TxHistoryListItem.tsx
Labels: fix

#2120 fix: Drop verify ledger
  src/Receive/AddressModal.stories.tsx
  src/Receive/AddressModal.tsx
  src/Receive/AddressVerifyModal.stories.tsx
  src/Receive/AddressVerifyModal.tsx
  src/Receive/Addresses.tsx
  src/Receive/Modals.tsx
  src/TxHistory/TxDetails/TxDetails.tsx
  storybook/storyLoader.js
Labels: fix

#2119 migrate wallet, walletmanager to events
  src/Settings/EasyConfirmation/DisableEasyConfirmationScreen.tsx
  src/Settings/EasyConfirmation/EasyConfirmationScreen.stories.tsx
  src/Settings/EasyConfirmation/EnableEasyConfirmationScreen.tsx
  src/Settings/EasyConfirmation/index.ts
  src/Settings/SettingsScreenNavigator.tsx
  src/Settings/ToggleEasyConfirmation/ToggleEasyConfirmationScreen.stories.tsx
  src/Settings/ToggleEasyConfirmation/ToggleEasyConfirmationScreen.tsx
  src/Settings/ToggleEasyConfirmation/index.ts
  src/Settings/WalletSettings/WalletSettingsScreen.tsx
  src/hooks/index.ts
  src/i18n/locales/cs-CZ.json
  src/i18n/locales/de-DE.json
  src/i18n/locales/el-GR.json
  src/i18n/locales/en-US.json
  src/i18n/locales/es-ES.json
  src/i18n/locales/fr-FR.json
  src/i18n/locales/hr-HR.json
  src/i18n/locales/hu-HU.json
  src/i18n/locales/id-ID.json
  src/i18n/locales/it-IT.json
  src/i18n/locales/ja-JP.json
  src/i18n/locales/ko-KR.json
  src/i18n/locales/nl-NL.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/ru-RU.json
  src/i18n/locales/sk-SK.json
  src/i18n/locales/tr-TR.json
  src/i18n/locales/zh-Hans.json
  src/i18n/locales/zh-Hant.json
  src/legacy/mockWallet.ts
  src/legacy/state.ts
  src/navigation.ts
  src/yoroi-wallets/Wallet.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/types.ts
  src/yoroi-wallets/walletManager.ts
  storybook/storyLoader.js
Labels: refactor

#2121 fix: Easy tx translations
  src/Settings/EasyConfirmation/DisableEasyConfirmationScreen.tsx
  src/Settings/EasyConfirmation/EnableEasyConfirmationScreen.tsx
  src/Settings/SettingsScreenNavigator.tsx
  src/i18n/locales/en-US.json
Labels: fix
