Repository Emurgo/yoroi, pull requests merged in 2022-10, with the labels that each got.

#2163 Boundary error image fix
  src/TxHistory/BalanceBanner.tsx
  src/TxHistory/LockedDeposit.tsx
  src/TxHistory/TxHistory.stories.tsx
  src/components/Boundary/Boundary.stories.tsx
  src/components/Boundary/Boundary.tsx
  storybook/decorators/index.ts
  storybook/decorators/query.tsx
Labels: fix

#2169 chore/ledgerjs-5.1.0
  package.json
  yarn.lock
Labels: chore

#2174 Fix(packages): Moved dev pkgs as dev deps
  package.json
  yarn.lock
Labels: fix

#2177 remove wallet selectors
  src/Receive/AddressModal.tsx
  src/Receive/Addresses.stories.tsx
  src/Receive/Addresses.tsx
  src/Receive/ReceiveScreen.stories.tsx
  src/Receive/ReceiveScreen.tsx
  src/TxHistory/TxDetails/TxDetails.stories.tsx
  src/TxHistory/TxDetails/TxDetails.tsx
  src/TxHistory/TxHistoryList/TxHistoryListItem.tsx
  src/legacy/actions.ts
  src/legacy/history.ts
  src/legacy/mockWallet.ts
  src/legacy/selectors.ts
  src/legacy/state.ts
  src/yoroi-wallets/cardano/types.ts
  storybook/mocks/wallet.ts
Labels: refactor

#2179 migrate utxos to hooks
  src/Catalyst/Step4.tsx
  src/Dashboard/Dashboard.stories.tsx
  src/Dashboard/Dashboard.tsx
  src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithOS.tsx
  src/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.stories.tsx
  src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
  src/Send/SendScreen/ErrorBanners.tsx
  src/Send/SendScreen/SendScreen.stories.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/Settings/RemoveWallet/RemoveWalletScreen.tsx
  src/Settings/WalletSettings/WalletSettingsScreen.tsx
  src/UtxoAutoRefresher.tsx
  src/hooks/index.ts
  src/legacy/actions.ts
  src/legacy/selectors.ts
  src/legacy/state.ts
  src/legacy/utxo.ts
  storybook/mocks/wallet.ts
Labels: refactor

#2180 cleanup voting registration
  package.json
  src/Catalyst/Catalyst.stories.tsx
  src/Catalyst/CatalystNavigator.tsx
  src/Catalyst/ConfirmPin.tsx
  src/Catalyst/ConfirmVotingTx.tsx
  src/Catalyst/Dialog.tsx
  src/Catalyst/DisplayPin.tsx
  src/Catalyst/DownloadCatalyst.tsx
  src/Catalyst/QrCode.tsx
  src/Catalyst/Step4.tsx
  src/Catalyst/VotingRegistration.stories.tsx
  src/Catalyst/VotingRegistration.tsx
  src/Catalyst/VotingRegistrationBackupCheckModal.tsx
  src/Catalyst/hooks.ts
  src/Catalyst/index.ts
  src/Dashboard/DashboardNavigator.tsx
  src/Dashboard/StakePoolInfos.tsx
  src/Menu/Menu.tsx
  src/TxHistory/BalanceBanner.tsx
  src/WalletNavigator.tsx
  src/hooks/index.ts
  src/legacy/fetch.ts
  src/navigation.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/types.ts
  storybook/storyLoader.js
  yarn.lock
Labels: refactor

#2182 migrate TxDetails to getTransactions
  src/TxHistory/TxDetails/TxDetails.stories.tsx
  src/TxHistory/TxDetails/TxDetails.tsx
  src/TxHistory/TxHistoryNavigator.tsx
  src/hooks/index.ts
  src/legacy/actions.ts
  src/yoroi-wallets/Wallet.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/api.ts
  src/yoroi-wallets/cardano/index.ts
  src/yoroi-wallets/cardano/shelley/transactionCache.ts
  src/yoroi-wallets/cardano/types.ts
  storybook/decorators/query.tsx
  storybook/mocks/wallet.ts
Labels: refactor

#2183 clean up txdetails, copy button
  src/Catalyst/QrCode.tsx
  src/TxHistory/TxDetails/TxDetails.tsx
  src/TxHistory/TxHistoryNavigator.tsx
  src/WalletInit/WalletAddress/WalletAddress.tsx
  src/components/FadeIn.tsx
  src/components/FadeOut.tsx
  src/components/index.ts
Labels: chore, refactor

#2186 remove crash reports from redux
  src/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  src/hooks/index.ts
  src/legacy/actions.ts
  src/legacy/selectors.ts
  src/legacy/state.ts
Labels: refactor

#2190 chore: added pyenv cfg
  .python-version
Labels: chore

#2187 chore: disabled flipper
  ios/Podfile
  ios/Podfile.lock
  ios/emurgo.xcodeproj/project.pbxproj
Labels: chore

#2189 Migrate from fetch utxos to yoroi-lib utxos
  package.json
  src/Catalyst/ConfirmVotingTx.tsx
  src/Dashboard/StakePoolInfos.tsx
  src/Send/AssetSelectorScreen/AssetSelectorScreen.tsx
  src/Send/Context/SendContext.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/Send/SendScreen/utils.ts
  src/Staking/DelegationConfirmation/DelegationConfirmation.stories.tsx
  src/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  src/hooks/index.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/types.ts
  src/yoroi-wallets/cardano/utxoStorage.ts
  src/yoroi-wallets/walletManager.ts
  storybook/mocks/wallet.ts
  yarn.lock
Labels: feature
