Repository Emurgo/yoroi, pull requests merged in 2023-05, with the labels that each got.

#2454 Story fix
  src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.stories.tsx
Labels: fix

#2460 chore(ci): workflow composite
  .github/actions/wallet-mobile/action.yml
  .github/workflows/wallet-mobile-checks.yml
Labels: chore

#2459 Fix: counter on SelectTokenFromList
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: fix

#2463 chore: bumped bridge + lib
  apps/wallet-mobile/android/app/src/main/java/com/yoroi/FlagSecure.java
  apps/wallet-mobile/android/app/src/main/java/com/yoroi/FlagSecurePackage.java
  apps/wallet-mobile/android/app/src/main/java/com/yoroi/MainActivity.java
  apps/wallet-mobile/android/app/src/main/java/com/yoroi/MainApplication.java
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/NftDetails/NftDetails.tsx
  apps/wallet-mobile/src/components/NftPreview/NftPreview.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/common.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/Catalyst/ConfirmVotingTx.json
  apps/wallet-mobile/translations/messages/src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.json
  apps/wallet-mobile/translations/messages/src/NftDetails/NftDetails.json
  apps/wallet-mobile/translations/messages/src/WalletInit/MnemonicExplanationModal/MnemonicExplanationModal.json
  apps/wallet-mobile/translations/messages/src/components/LanguagePicker/LanguagePickerWarning.json
  apps/wallet-mobile/yarn.lock
Labels: chore

#2455 Tx signed and tx failed screens
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Send/common/strings.ts
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/FailedTx/FailedTxImage.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/FailedTx/FailedTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/SubmittedTx/SubmittedTxImage.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/SubmittedTx/SubmittedTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/SubmittedTx/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Send/common/strings.json
Labels: feature

#2462 fix(NFT): Fix NFT name decoding
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/utils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/utils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/nfts.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/parsing.test.ts
  apps/wallet-mobile/translations/messages/src/NftDetails/NftDetails.json
Labels: fix

#2465 Bluetooth fix
  apps/wallet-mobile/global.js
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/metro.config.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/yarn.lock
Labels: fix

#2469 csl bridge update
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/yarn.lock
Labels: chore

#2467 fix(navigation): Fix navigation avoid when keyboard is open
  apps/wallet-mobile/android/app/src/main/AndroidManifest.xml
Labels: fix

#2466 Fix: camera
  apps/wallet-mobile/android/build.gradle
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ReadQRCodeScreen.tsx
  apps/wallet-mobile/yarn.lock
Labels: fix

#2470 add token text input fix
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/src/components/TextInput/TextInput.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
  apps/wallet-mobile/yarn.lock
Labels: fix

#2477 fix tsc errors
  apps/wallet-mobile/package.json
  packages/metrics/package.json
  yarn.lock
Labels: fix

#2474 Add zod parsing
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/components/NftPreview/NftPreview.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/api.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/assetSuply.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/assetSupply.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/metadata.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/metadata.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/nftModerationStatus.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/nftModerationStatus.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/tokenRegistry.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/utils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/utils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/nfts.ts
  apps/wallet-mobile/src/yoroi-wallets/types/tokens.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/parsing.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/parsing.ts
  apps/wallet-mobile/translations/messages/src/Catalyst/ConfirmVotingTx.json
  apps/wallet-mobile/translations/messages/src/Nfts/Nfts.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryList/TxHistoryListItem.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  yarn.lock
Labels: chore

#2479 fix(debugger): Override buffer's subarray and remove react-native-buffer
  apps/wallet-mobile/global.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/polyfills.ts
  metro.config.js
  yarn.lock
Labels: fix

#2481 chore(build): fix tools
  .tool-versions
  apps/wallet-mobile/.gitignore
  apps/wallet-mobile/.tool-versions
  apps/wallet-mobile/Gemfile
  apps/wallet-mobile/Gemfile.lock
  apps/wallet-mobile/fastlane/Appfile
  apps/wallet-mobile/fastlane/Fastfile
  apps/wallet-mobile/fastlane/Matchfile
  apps/wallet-mobile/fastlane/README.md
  apps/wallet-mobile/get_rust.sh
  apps/wallet-mobile/ios/Podfile
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/ios/yoroi.xcodeproj/xcshareddata/xcschemes/yoroi.xcscheme
  apps/wallet-mobile/ios/yoroi/Info.plist
  apps/wallet-mobile/ios/yoroiTests/Info.plist
  apps/wallet-mobile/scripts/react-native-xcode.sh
  apps/wallet-mobile/translations/messages/src/TxHistory/TxDetails/TxDetails.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryList/TxHistoryListItem.json
Labels: chore
