Repository Emurgo/yoroi, pull requests merged in 2023-07, with the labels that each got.

#2527 refactor: Revamp qr scanner (#2527)
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/components/QRCodeScanner/QRCodeScanner.stories.tsx
  apps/wallet-mobile/src/components/QRCodeScanner/QRCodeScanner.tsx
  apps/wallet-mobile/src/features/Send/common/strings.ts
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ReadQRCodeScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
Labels: feature

#2537 fix: Input password dots color on android
  apps/wallet-mobile/android/app/src/dev/res/values/styles.xml
  apps/wallet-mobile/android/app/src/nightly/res/values/styles.xml
  apps/wallet-mobile/android/app/src/production/res/values/styles.xml
Labels: fix

#2534 chore: Hide tabs on send when reading QR code
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/components/QRCodeScanner/QRCodeScanner.tsx
  apps/wallet-mobile/src/features/Send/common/strings.ts
Labels: feature

#2541 fix: Privacy mode
  apps/wallet-mobile/src/Settings/PrivacyMode/PrivacyMode.tsx
  apps/wallet-mobile/src/TxHistory/AssetList/AssetList.tsx
  apps/wallet-mobile/src/TxHistory/BalanceBanner.tsx
  apps/wallet-mobile/src/TxHistory/PairedBalance.stories.tsx
  apps/wallet-mobile/src/TxHistory/PairedBalance.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryList/TxHistoryListItem.tsx
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
Labels: fix

#2536 fix(Ledger): Add Ledger Cardano app V5 voting support
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/Catalyst/ConfirmVotingTx.tsx
  apps/wallet-mobile/src/components/ConfirmTx/ConfirmTx.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/common.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/hw/hw.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/tests/mainnet/ShelleyWallet.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/tests/testnet/ShelleyWalletTestnet.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/tests/testnet/__snapshots__/ShelleyWalletTestnet.test.ts.snap
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/translations/messages/src/Catalyst/ConfirmVotingTx.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Send/common/strings.json
  yarn.lock
Labels: fix

#2539 fix: Navigation from failed tx screen
  apps/wallet-mobile/src/components/ConfirmTx/ConfirmTx.tsx
  apps/wallet-mobile/src/features/Send/common/navigation.ts
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/FailedTx/FailedTxScreen.tsx
Labels: fix

#2545 fix send tx edit amounts
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
Labels: fix

#2546 fix(mat): rebuilding history after send tx submit fail
  apps/wallet-mobile/src/features/Send/common/navigation.ts
Labels: fix

#2543 fix(mat): qr scanner amount
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ReadQRCodeScreen.tsx
Labels: fix

#2548 fix(mat): send tx wrong password error message
  apps/wallet-mobile/src/components/ConfirmTx/ConfirmTx.tsx
Labels: fix

#2547 fix(mat): input helper info color
  apps/wallet-mobile/src/components/TextInput/TextInput.tsx
  apps/wallet-mobile/src/theme/config.ts
Labels: fix

#2549 fix(tx-details): Fix transaction details privacy mode
  apps/wallet-mobile/src/TxHistory/TxDetails/AssetList.stories.tsx
  apps/wallet-mobile/src/TxHistory/TxDetails/AssetList.tsx
  apps/wallet-mobile/src/TxHistory/TxDetails/TxDetails.stories.tsx
  apps/wallet-mobile/src/TxHistory/TxDetails/TxDetails.tsx
  apps/wallet-mobile/translations/messages/src/Catalyst/ConfirmVotingTx.json
  apps/wallet-mobile/translations/messages/src/TxHistory/AssetList/AssetList.json
  apps/wallet-mobile/translations/messages/src/TxHistory/PairedBalance.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxDetails/AssetList.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxDetails/TxDetails.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryList/TxHistoryListItem.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Send/common/strings.json
Labels: fix

#2550 chore: updated cli cmd for ampli
  apps/wallet-mobile/ampli.json
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/metrics/README.md
Labels: chore

#2544 fix(mat): Fix MAT swipe navigation
  apps/wallet-mobile/src/Search/SearchContext.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Send/common/navigation.ts
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
  apps/wallet-mobile/src/utils/navigation.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.ts
  apps/wallet-mobile/translations/messages/src/Catalyst/ConfirmVotingTx.json
  apps/wallet-mobile/translations/messages/src/TxHistory/AssetList/AssetList.json
  apps/wallet-mobile/translations/messages/src/TxHistory/PairedBalance.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryList/TxHistoryListItem.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
Labels: fix

#2554 fix(CIP-36): Use stakingPrivateKey to sign CIP36 transaction metadata on a pw wallet
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/AddToken/AddToken.json
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
  yarn.lock
Labels: fix

#2558 fix: iOS build on intel chip
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
Labels: fix

#2557 fix: Wrong status bar style on some screens
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/components/StatusBar.tsx
  yarn.lock
Labels: fix

#2559 fix: hide locked limit and staking page balances
  apps/wallet-mobile/src/Dashboard/UserSummary.tsx
  apps/wallet-mobile/src/TxHistory/LockedDeposit.tsx
Labels: fix

#2562 fix(translations): Reconnect Crowdin
  crowdin-wallet-mobile.yml
Labels: fix
