Repository Emurgo/yoroi, pull requests merged in 2023-03, with the labels that each got.

#2362 Expanded supported languages
  src/Legal/TermsOfService/loadTos.ts
  src/Legal/TermsOfService/tos/bn-BD.md
  src/Legal/TermsOfService/tos/fil-PH.md
  src/Legal/TermsOfService/tos/pl-PL.md
  src/Legal/TermsOfService/tos/sl-SI.md
  src/Legal/TermsOfService/tos/sv-SE.md
  src/Legal/TermsOfService/tos/sw-KE.md
  src/Legal/TermsOfService/tos/tl-PH.md
  src/Legal/TermsOfService/tos/uk-UA.md
  src/Legal/TermsOfService/tos/vi-VN.md
  src/i18n/index.ts
  src/i18n/languages.ts
  src/i18n/polyfills.ts
  src/i18n/translations.ts
Labels: chore

#2359 Fix NFT search bar position and metadata spacing
  src/NftDetails/NftDetails.tsx
  src/Nfts/NftsNavigator.tsx
  src/Search/SearchHeader.tsx
Labels: fix

#2377 fix story import
  src/components/TokenIcon/TokenIcon.stories.tsx
Labels: fix

#2381 Fix animated gifs on android
  android/app/build.gradle
Labels: fix

#2380 Flashlist implementation in assets lists
  src/Send/AssetSelectorScreen/AssetSelectorScreen.tsx
  src/TxHistory/AssetList/AssetList.tsx
Labels: feature

#2393 Removing nft refetch
  src/yoroi-wallets/hooks/index.ts
Labels: fix

#2395 Missing kenian transaltion declaration
  src/i18n/index.ts
  src/i18n/languages.ts
  src/i18n/translations.ts
Labels: fix

#2399 Button component font weight fix
  src/components/Button/Button.tsx
Labels: fix

#2398 Enable send screen scrolling when keyboard is shown
  src/Send/SendScreen/SendScreen.tsx
Labels: fix

#2394 Avoid nft list refresh animation on automatic refetch
  src/Nfts/Nfts.tsx
  src/Nfts/hooks.ts
  src/yoroi-wallets/hooks/index.ts
Labels: fix

#2400 Send component container fix
  src/Send/SendScreen/SendScreen.tsx
Labels: fix

#2402 Nft details title bold
  src/NftDetails/NftDetails.tsx
Labels: fix

#2403 Fix send loading animation overflow
  src/Send/SendScreen/SendScreen.tsx
Labels: fix

#2396 Add SVG support to NFT Gallery
  .storybook/storybook.requires.js
  .tool-versions
  ios/Podfile.lock
  jestSetup.ts
  package.json
  src/NftDetails/NftDetails.tsx
  src/NftDetails/NftDetailsImage.tsx
  src/Nfts/ImageGallery/ImageGallery.tsx
  src/components/Icon/Document.tsx
  src/components/Icon/WalletAccount.tsx
  src/components/NftPreview/NftPreview.stories.tsx
  src/components/NftPreview/NftPreview.tsx
  src/components/NftPreview/index.ts
  src/components/TokenIcon/ModeratedNftIcon.stories.tsx
  src/components/TokenIcon/ModeratedNftIcon.tsx
  src/components/TokenIcon/TokenIcon.tsx
  yarn.lock
Labels: feature

#2401 Show NFTs with missing metadata
  src/NftDetails/NftDetails.tsx
  src/Nfts/ImageGallery/ImageGallery.tsx
  src/components/NftPreview/NftPreview.stories.tsx
  src/components/NftPreview/NftPreview.tsx
  src/yoroi-wallets/cardano/api/api.ts
  src/yoroi-wallets/cardano/nfts.ts
  src/yoroi-wallets/hooks/index.ts
  src/yoroi-wallets/mocks/wallet.ts
  src/yoroi-wallets/types/tokens.ts
  src/yoroi-wallets/types/types.ts
Labels: fix

#2405 Show placeholder when there is an error loading the NFT image
  src/NftDetails/NftDetails.tsx
  src/components/NftPreview/NftPreview.tsx
Labels: fix

#2406 Redirect to NFT gallery when NFT can not be found
  src/NftDetails/NftDetails.tsx
  src/NftDetails/NftDetailsImage.tsx
  src/navigation.ts
  src/yoroi-wallets/hooks/index.ts
Labels: fix

#2408 Fix concat for image array props
  src/yoroi-wallets/cardano/nfts.ts
Labels: fix

#2411 Update ledger hw app 6.0.0
  package.json
  yarn.lock
Labels: chore

#2413 Fix staging token registry
  src/yoroi-wallets/cardano/networks.ts
  src/yoroi-wallets/cardano/shelley-testnet/constants.ts
Labels: fix
