Repository Emurgo/yoroi, pull requests merged in 2023-10, with the labels that each got.

#2738 chore: impr ffee
  packages/swap/src/helpers/orders/getBuyAmount.ts
  packages/swap/src/helpers/orders/getFrontendFee.test.ts
  packages/swap/src/helpers/orders/getFrontendFee.ts
  packages/swap/src/helpers/orders/getMuesliswapFrontendFee.ts
  packages/swap/src/helpers/orders/getSellAmount.ts
  packages/swap/src/index.ts
  packages/swap/src/translators/constants.ts
  packages/swap/src/utils/quantities.test.ts
  packages/swap/src/utils/quantities.ts
Labels: chore

#2749 chore: Dropped min-ada received with slippage
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  packages/swap/src/helpers/orders/amounts/getMinAdaReceiveAfterSlippage.test.ts
  packages/swap/src/helpers/orders/amounts/getMinAdaReceiveAfterSlippage.ts
  packages/swap/src/index.ts
Labels: refactor

#2748 fix: edit limit price
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/ClearQuantities.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/TopTokenActions.tsx
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: fix

#2751 fix: Show market price in pool selection
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
  apps/wallet-mobile/translations/messages/src/Catalyst/VotingRegistrationBackupCheckModal.json
  apps/wallet-mobile/translations/messages/src/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/HW/LedgerTransportSwitchModal/LedgerTransportSwitchModal.json
  apps/wallet-mobile/translations/messages/src/Receive/AddressModal.json
  apps/wallet-mobile/translations/messages/src/Staking/PoolWarningModal/PoolWarningModal.json
  apps/wallet-mobile/translations/messages/src/TxHistory/ModalInfo/ModalInfo.json
  apps/wallet-mobile/translations/messages/src/WalletInit/MnemonicBackupModal/MnemonicBackupImportanceModal.json
  apps/wallet-mobile/translations/messages/src/WalletInit/MnemonicExplanationModal/MnemonicExplanationModal.json
  apps/wallet-mobile/translations/messages/src/WalletInit/WalletInit/WalletInitScreen.json
  apps/wallet-mobile/translations/messages/src/components/ErrorModal/ErrorModal.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: fix

#2752 fix: Get market price of each pool, not the selected
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
Labels: fix, done

#2756 fix(swap): cancellation modal
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/components/index.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/helpers.ts
  apps/wallet-mobile/src/legacy/BottomSheet/BottomSheet.stories.tsx
  apps/wallet-mobile/src/legacy/BottomSheet/BottomSheet.tsx
  apps/wallet-mobile/src/legacy/BottomSheet/index.ts
Labels: fix

#2755 chore(swap): handle swap balance errors
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.stories.tsx
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.tsx
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
  packages/swap/src/helpers/mocks.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.ts
  packages/swap/src/translators/reactjs/state/state.ts
Labels: chore

#2757 fix: storybook require
  apps/wallet-mobile/.storybook/storybook.requires.js
Labels: fix

#2758 fix(swap): infinite open orders loading
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
Labels: fix

#2761 fix balance errors
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
Labels: fix

#2759 fix(modal): Fix event handlers inside modal
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
Labels: fix

#2765 chore: banxa doesn't work with testnets
  apps/wallet-mobile/.env
  apps/wallet-mobile/.env.nightly
  apps/wallet-mobile/.env.staging
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/legacy/env.ts
  packages/banxa/src/adapters/zod-schema.ts
  packages/banxa/src/helpers/wallet-address.test.ts
  packages/banxa/src/helpers/wallet-address.ts
Labels: chore

#2764 fix(swap): Improve ledger flow
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithHW.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxWithHW.tsx
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: fix

#2766 fix(staking): hw wallets
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
Labels: fix

#2770 fix(swap): reselect primary token to sell when no buy token is selected
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
Labels: fix

#2767 fix(swap): Use error boundary to handle HW errors
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/Icon/Danger.tsx
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTx.stories.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTx.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithHW.tsx
  apps/wallet-mobile/src/features/Swap/common/ModalError/ModalError.stories.tsx
  apps/wallet-mobile/src/features/Swap/common/ModalError/ModalError.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTx.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
Labels: fix

#2771 fix(swap): Fix limit price precision / denomination
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.ts
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
  packages/swap/src/utils/quantities.test.ts
  packages/swap/src/utils/quantities.ts
Labels: fix

#2776 fix(swap): Show custom error message when ADA app on Ledger is closed
  apps/wallet-mobile/src/features/Swap/common/ModalError/ModalError.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/hw/hw.ts
  apps/wallet-mobile/src/yoroi-wallets/hw/hw.ts
Labels: fix

#2773 fix(swap): yoroi entry for non ada tokens
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
Labels: fix

#2778 chore: bump rn iOS 17
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/package.json
  packages/banxa/package.json
  packages/cardano/package.json
  packages/common/package.json
  packages/swap/package.json
  yarn.lock
Labels: chore

#2774 fix: Removes loading overlay
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
Labels: fix

#2772 New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#2769 feature(swap): resfresh animation
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/TopTokenActions.tsx
Labels: feature, dont-merge

#2779 fix(swap): Fix collateral check
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.stories.tsx
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: fix

#2780 fix: Copy change ' tokens' => 'assets
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
Labels: fix

#2781 chore: banxa partner update
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
Labels: chore

#2784 fix(swap): Fix swap cancellation fee error handling
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/helpers.ts
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: fix

#2787 refactor(swap): refresh animation improvement
  apps/wallet-mobile/src/components/Icon/Refresh.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/TopTokenActions.tsx
Labels: refactor

#2782 fix(swap): Metadata labels
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/src/features/Swap/common/LiquidityPool/LiquidityPool.stories.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/common/useSwapTx.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/processTransactions/processTransactions.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/transaction.ts
  apps/wallet-mobile/src/yoroi-wallets/types/other.ts
  packages/openswap/src/api.ts
  packages/swap/src/helpers/orders/factories/makePossibleMarketOrder.test.ts
  packages/swap/src/helpers/orders/factories/makePossibleMarketOrder.ts
  packages/swap/src/translators/constants.ts
Labels: fix

#2792 fix(swap): fix typo and loading state
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: fix

#2790 chore: Swap/copy updates
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
  apps/wallet-mobile/src/features/Swap/common/SwapInfoLink/SwapInfoLink.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: chore

#2793 fix: Centralization hw buttons
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/LedgerTransportSwitch.tsx
Labels: fix

#2786 refactor(swap): create form
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/ClearQuantities.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/SwitchTokens.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/TopTokenActions.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: refactor

#2796 refactor(swap): tx confirm info modals
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
Labels: refactor

#2798 refactor(swap): slippage info modal
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/ShowSlippageInfo.tsx
Labels: refactor

#2795 refactor(swap): improve swap buy field performance
  apps/wallet-mobile/src/features/Swap/SwapNavigator.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
Labels: refactor

#2797 refactor(swap): pool actions modals
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
Labels: refactor

#2799 refactor(swap): limit price warning modal
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/LimitPriceWarning/LimitPriceWarning.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/LimitPriceWarning/LimitPriceWarning.tsx
Labels: refactor

#2794 chore: New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#2803 fix(swap): limit input
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
Labels: fix

#2806 fix(swap): create swap
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
Labels: fix

#2800 refactor(swap): remove old modal
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/index.ts
  apps/wallet-mobile/src/legacy/BottomSheetModal/BottomSheetModal.stories.tsx
  apps/wallet-mobile/src/legacy/BottomSheetModal/BottomSheetModal.tsx
  apps/wallet-mobile/src/legacy/BottomSheetModal/index.ts
Labels: refactor

#2804 feature: Banxa info modal and metrics
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/i18n/global-messages.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/metrics/ampli/index.ts
  apps/wallet-mobile/src/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/metrics/metricsManager.tsx
  apps/wallet-mobile/src/metrics/mocks.ts
  apps/wallet-mobile/translations/messages/src/i18n/global-messages.json
  yarn.lock
Labels: feature

#2809 chore: New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#2811 fix: dep swap
  packages/swap/package.json
Labels: fix

#2813 fix: hook check
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
Labels: fix

#2810 fix(swap): balance errors
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
Labels: fix

#2812 fix(swap): disable swap when limit 0
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
Labels: fix

#2815 chore: Added tests
  packages/swap/package.json
  packages/swap/src/helpers/mocks.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.test.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.ts
  packages/swap/src/helpers/pools/getBestBuyPool.test.ts
  packages/swap/src/helpers/pools/getBestPoolCalculation.test.ts
  packages/swap/src/helpers/pools/getBestSellPool.test.ts
  packages/swap/src/helpers/prices/getPairPriceInPtTerms.test.ts
  packages/swap/src/helpers/prices/getPairPriceInPtTerms.ts
  packages/swap/src/helpers/prices/getPriceAfterFee.test.ts
  packages/swap/src/translators/reactjs/provider/SwapProvider.test.tsx
  packages/swap/src/translators/reactjs/state/state.test.ts
  packages/swap/src/translators/reactjs/state/state.ts
Labels: chore

#2817 chore: Bump versions
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/banxa/package.json
  packages/common/package.json
  packages/openswap/package.json
  packages/swap/package.json
  packages/types/package.json
Labels: chore

#2818 chore: upd wrkspace e2e
  yoroi.code-workspace
Labels: chore

#2816 chore(swap): Refactor datum and YoroiEntry
  apps/wallet-mobile/src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithHW.stories.tsx
  apps/wallet-mobile/src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithOS.stories.tsx
  apps/wallet-mobile/src/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithPassword.stories.tsx
  apps/wallet-mobile/src/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.stories.tsx
  apps/wallet-mobile/src/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  apps/wallet-mobile/src/Staking/DelegationConfirmation/DelegationConfirmation.stories.tsx
  apps/wallet-mobile/src/features/Send/common/mocks.ts
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/BalanceAfter.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/PrimaryTotal.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/SecondaryTotals.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/BalanceAfter.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/PrimaryTotal.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/SecondaryTotals.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/tests/mainnet/ShelleyWallet.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/unsignedTx/unsignedTx.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/unsignedTx/unsignedTx.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/types/yoroi.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.ts
  apps/wallet-mobile/translations/messages/src/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.json
Labels: chore

#2822 chore: Added fintech wallet fef
  apps/wallet-mobile/.env
  apps/wallet-mobile/.env.nightly
  apps/wallet-mobile/.env.production
  apps/wallet-mobile/.env.staging
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/common/entries.test.ts
  apps/wallet-mobile/src/features/Swap/common/entries.ts
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
Labels: chore, refactor

#2824 fix: No supply error never showing
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
Labels: fix

#2823 refactor: Tokens state
  apps/wallet-mobile/src/features/Swap/SwapNavigator.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
  packages/swap/src/helpers/orders/costs/getFrontendFee.test.ts
  packages/swap/src/helpers/orders/costs/getFrontendFee.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.test.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.ts
  packages/swap/src/translators/reactjs/provider/SwapProvider.test.tsx
  packages/swap/src/translators/reactjs/provider/SwapProvider.tsx
  packages/swap/src/translators/reactjs/state/state.test.ts
  packages/swap/src/translators/reactjs/state/state.ts
  packages/types/src/helpers/types.ts
Labels: refactor

#2828 fix(swap) : change condition for complete orders
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
Labels: fix

#2829 chore: build flow only for release
  packages/api/package.json
  packages/banxa/package.json
  packages/common/package.json
  packages/openswap/package.json
  packages/openswap/scripts/flowgen.sh
  packages/swap/package.json
  packages/types/package.json
Labels: chore

#2831 refactor: Sell quantity adjusts to token change
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  packages/swap/src/helpers/mocks.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.test.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.ts
  packages/swap/src/helpers/pools/getBestPoolCalculation.test.ts
  packages/swap/src/translators/reactjs/provider/SwapProvider.test.tsx
  packages/swap/src/translators/reactjs/provider/SwapProvider.tsx
  packages/swap/src/translators/reactjs/state/state.ts
Labels: fix, refactor

#2832 chore: added fefee summary tx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
Labels: chore

#2833 fix: bottom bar android
  apps/wallet-mobile/src/WalletNavigator.tsx
Labels: fix

#2834 chore: hide liq prov fee when limit order
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: chore

#2835 fix: limit price initialization
  packages/swap/src/helpers/orders/amounts/getBuyAmount.test.ts
  packages/swap/src/helpers/orders/amounts/getBuyAmount.ts
  packages/swap/src/helpers/orders/amounts/getSellAmount.test.ts
  packages/swap/src/helpers/orders/amounts/getSellAmount.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.ts
Labels: fix

#2837 Fix: limit with undefined price
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
  packages/swap/src/helpers/orders/amounts/getBuyAmount.test.ts
  packages/swap/src/helpers/orders/amounts/getBuyAmount.ts
  packages/swap/src/helpers/orders/amounts/getSellAmount.test.ts
  packages/swap/src/helpers/orders/amounts/getSellAmount.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.ts
  packages/swap/src/helpers/prices/getMarketPrice.test.ts
  packages/swap/src/helpers/prices/getMarketPrice.ts
  packages/swap/src/translators/reactjs/state/state.test.ts
Labels: fix

#2839 fix: read-only wallet password menu disabled
  apps/wallet-mobile/src/features/Settings/SettingsItems.tsx
  apps/wallet-mobile/src/features/Settings/WalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/WalletSettings/WalletSettingsScreen.json
Labels: fix

#2841 fix(swap): Open submitted tx screen after easy confirmation step
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
Labels: fix

#2842 fix(swap): modals
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/LimitPriceWarning/LimitPriceWarning.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/LimitPriceWarning/LimitPriceWarning.tsx
Labels: fix

#2843 fix(settings): easy confirmation bad states
  apps/wallet-mobile/src/features/Settings/WalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/WalletSettings/WalletSettingsScreen.json
Labels: fix

#2844 fix(swap): format market price
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/LimitPriceWarning/LimitPriceWarning.tsx
Labels: fix

#2845 chore: Swap/sort-tokes-to-buy
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
Labels: chore

#2846 fix(settings): disable password change in hw wallets
  apps/wallet-mobile/src/features/Settings/WalletSettings/WalletSettingsScreen.tsx
Labels: fix

#2848 chore: remove swap/onramp feature flag
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/features/index.ts
  apps/wallet-mobile/translations/messages/src/features/Settings/WalletSettings/WalletSettingsScreen.json
Labels: chore

#2849 fix: infinite priceWithFees sort
  packages/swap/src/helpers/pools/getBestPoolCalculation.ts
  packages/swap/src/translators/reactjs/state/state.test.ts
Labels: fix

#2850 fix: ro feature only
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
Labels: fix

#2851 fix: Amountcard input ref
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: fix

#2852 fix: Use system language as locale when different than app language
  apps/wallet-mobile/src/i18n/LanguageProvider.tsx
Labels: fix

#2853 chore: bump pkgs version 1.2.0
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/banxa/package.json
  packages/common/package.json
  packages/openswap/package.json
  packages/swap/package.json
  packages/types/package.json
Labels: chore

#2855 chore(moment): Remove moment artifacts
  apps/wallet-mobile/src/i18n/languages.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/chain/chain.ts
Labels: chore

#2854 fix: numbers locale from system
  apps/wallet-mobile/.vscode/launch.json
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/src/i18n/LanguageProvider.tsx
  apps/wallet-mobile/src/i18n/getRegion.test.ts
  apps/wallet-mobile/src/i18n/getRegion.ts
  apps/wallet-mobile/src/i18n/initialization.ts
  apps/wallet-mobile/src/i18n/languages.ts
  apps/wallet-mobile/src/i18n/transformers/asYoroiLocale.test.ts
  apps/wallet-mobile/src/i18n/transformers/asYoroiLocale.ts
Labels: wip, fix, dont-merge

#2857 fix(swap): Fix default tickers in limit/market price
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
Labels: fix

#2858 fix(swap): Reset errors when switch touched
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
Labels: fix
