Repository Emurgo/yoroi, pull requests merged in 2023-09, with the labels that each got.

#2655 Fix typos
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
Labels: chore

#2656 chore(swap): Format quantities
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/ClosedOrders.tsx
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: chore

#2662 fix(swap): Fix trailing zero decimal input
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.ts
Labels: fix

#2661 fix(swap): Fix asset selection list bugs
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/components/TokenIcon/TokenIcon.tsx
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: fix, chore

#2665 chore(swap): Typo
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
Labels: chore

#2667 fix(swap): Asset price recalculation on asset change and minor bugs
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
Labels: fix

#2670 fix(initialization): Add scrollbar to inital screen and ToS changed screen
  apps/wallet-mobile/src/features/Initialization/InitialScreen/InitialScreen.tsx
  apps/wallet-mobile/src/features/Initialization/TermsOfServiceChangedScreen/TermsOfServiceChangedScreen.tsx
Labels: fix

#2669 refactor(swap): expandable card
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/BottomSheetModal/BottomSheetModal.tsx
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.stories.tsx
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.tsx
  apps/wallet-mobile/src/components/ExpandableInfoCard/index.ts
  apps/wallet-mobile/src/components/index.ts
  apps/wallet-mobile/src/features/Swap/common/SelectPool/ExpendableCard/ExpandableInfoCard.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
Labels: refactor

#2672 feature(settings): wallet settings revamp
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/Logout.tsx
  apps/wallet-mobile/src/components/Icon/Resync.tsx
  apps/wallet-mobile/src/components/Icon/WalletStack.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/features/Settings/ChangePassword/ChangePasswordScreen.tsx
  apps/wallet-mobile/src/features/Settings/ChangeWalletName/ChangeWalletName.tsx
  apps/wallet-mobile/src/features/Settings/RemoveWallet/RemoveWalletScreen.tsx
  apps/wallet-mobile/src/features/Settings/SettingsItems.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/Settings/WalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/i18n/global-messages.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/legacy/SettingItems.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/ChangePassword/ChangePasswordScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ChangeWalletName/ChangeWalletName.json
  apps/wallet-mobile/translations/messages/src/features/Settings/RemoveWallet/RemoveWalletScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/WalletSettings/WalletSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/i18n/global-messages.json
Labels: feature

#2674 fix(swap): Ignore spaces when searching
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
Labels: chore

#2677 Fix pool provider key
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
Labels: fix

#2678 fix(swap): Set pool auto when changing pool list
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: fix

#2659 chore(swap): add unsignedTx
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/Receive/Addresses.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/common/useSwapTx.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  packages/swap/src/index.ts
  packages/swap/src/translators/reactjs.tsx
  yarn.lock
Labels: chore

#2676 chore(settings): improvements
  apps/wallet-mobile/src/Dashboard/DashboardNavigator.tsx
  apps/wallet-mobile/src/NftDetails/NftDetailsNavigator.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/features/Settings/EasyConfirmation/DisableEasyConfirmationScreen.tsx
  apps/wallet-mobile/src/features/Settings/EasyConfirmation/EnableEasyConfirmationScreen.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/Settings/WalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/features/Settings/common/navigation.tsx
  apps/wallet-mobile/src/navigation.tsx
Labels: chore

#2682 fix(swap): Unknown pool provider
  apps/wallet-mobile/src/features/Swap/common/PoolIcon/PoolIcon.tsx
Labels: fix

#2685 fix(swap): Buy value recalculation race condition
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.tsx
Labels: fix

#2686 fix(swap): Add not enough supply error msg
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: fix

#2681 fix(swap): Remove verified filter, API returns only verified ones
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  packages/openswap/src/api.ts
Labels: fix

#2663 chore: add sign and submit with passwoard
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/HW/LedgerTransportSwitchModal/LedgerTransportSwitchModal.tsx
  apps/wallet-mobile/src/assets/img/transaction-success.png
  apps/wallet-mobile/src/features/Swap/common/TransactionSigned/TransactionSigned.stories.tsx
  apps/wallet-mobile/src/features/Swap/common/TransactionSigned/TransactionSigned.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/common/mocks.ts
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/common/useSwapTx.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTx.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxWithHW.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxWithPassword.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/LedgerTransportSwitch.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowMarketPrice.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowMarketPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/mapOrders.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/translations/messages/src/HW/LedgerTransportSwitchModal/LedgerTransportSwitchModal.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/Swap/useCases/ConfirmTxScreen/LedgerTransportSwitch.json
  packages/swap/src/translators/reactjs.tsx
  yarn.lock
Labels: chore

#2690 fix(swap): Choose best pool and fix changing it
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
Labels: fix

#2695 chore(swap): add tab navigation
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/Swap/SwapNavigator.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/ListOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/StartSwapScreen.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/StartSwapScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/index.ts
  apps/wallet-mobile/src/features/Swap/useCases/index.ts
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
Labels: chore

#2699 refactor: bottomsheet modal
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/BottomSheet/BottomSheet.stories.tsx
  apps/wallet-mobile/src/components/BottomSheet/BottomSheet.tsx
  apps/wallet-mobile/src/components/BottomSheet/index.ts
  apps/wallet-mobile/src/components/index.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
Labels: refactor

#2701 fix(swap): scrolls
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/ListOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
Labels: fix

#2702 chore: avoid notifying no changes
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
Labels: chore

#2697 refactor(swap): Move calculations to swap package
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.test.ts
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/common/mocks.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/LimitPriceWarning/LimitPriceWarning.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/TopTokenActions.tsx
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
  packages/swap/src/helpers/orders/getBuyAmount.test.ts
  packages/swap/src/helpers/orders/getBuyAmount.ts
  packages/swap/src/helpers/orders/getBuyAmountByChangingSell.ts
  packages/swap/src/helpers/orders/getMarketPrice.test.ts
  packages/swap/src/helpers/orders/getMarketPrice.ts
  packages/swap/src/helpers/orders/getSellAmount.test.ts
  packages/swap/src/helpers/orders/getSellAmount.ts
  packages/swap/src/helpers/orders/getSellAmountByChangingBuy.ts
  packages/swap/src/helpers/orders/makePossibleMarketOrder.ts
  packages/swap/src/helpers/orders/types.ts
  packages/swap/src/helpers/transformers.ts
  packages/swap/src/index.ts
  packages/swap/src/translators/reactjs/provider/SwapProvider.test.tsx
  packages/swap/src/translators/reactjs/state/state.mocks.ts
  packages/swap/src/translators/reactjs/state/state.test.ts
  packages/swap/src/translators/reactjs/state/state.ts
Labels: refactor

#2696 feat(analytics): swap remainder events
  apps/wallet-mobile/src/features/Swap/SwapNavigator.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/mapOrders.ts
  apps/wallet-mobile/src/metrics/ampli/index.ts
  apps/wallet-mobile/src/navigation.tsx
Labels: feature

#2706 chore: bump csl
  apps/wallet-mobile/package.json
  packages/cardano/src/cardano/api/token-offchain-metadata.ts
  packages/cardano/src/cardano/api/token-onchain-metadata.ts
  packages/cardano/src/cardano/api/token-supply.ts
  packages/common/src/api/fetcher.ts
  yarn.lock
Labels: chore

#2707 fix/confirm tx types
  apps/wallet-mobile/src/components/ConfirmTx/ConfirmTx.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
Labels: fix

#2708 fix: wrong import
  packages/swap/src/translators/reactjs/state/state.ts
Labels: fix

#2709 fix(swap): market price calculation and other bugs
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  packages/swap/src/helpers/orders/getMarketPrice.test.ts
  packages/swap/src/helpers/orders/getMarketPrice.ts
  packages/swap/src/translators/reactjs/provider/SwapProvider.test.tsx
Labels: fix

#2710 fix(transactions): Fix datum check when signing transactions
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
Labels: fix

#2703 feature: collateral settings/manager
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/ConfirmTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/FailedTx/FailedTxImage.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/FailedTx/FailedTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/SubmittedTx/SubmittedTxImage.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/SubmittedTx/SubmittedTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/SubmittedTx/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/BalanceAfter.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/CurrentBalance.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/Fees.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/PrimaryTotal.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/ReceiverInfo.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/SecondaryTotals.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/index.ts
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.stories.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/index.ts
  apps/wallet-mobile/src/features/Settings/ManageCollateral/navigation.ts
  apps/wallet-mobile/src/features/Settings/ManageCollateral/strings.ts
  apps/wallet-mobile/src/features/Settings/SettingsItems.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/Settings/WalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utxoManager/raw-utxos.mocks.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utxoManager/types.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utxoManager/useCollateralInfo.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/utxoManager/useSetCollateralId.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/utxoManager/utxoManager.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utxoManager/utxoManager.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utxoManager/utxos.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utxoManager/utxos.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/translations/messages/src/features/Settings/ManageCollateral/ConfirmTx/Summary/ReceiverInfo.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ManageCollateral/strings.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/WalletSettings/WalletSettingsScreen.json
  packages/common/src/helpers/arrays.test.ts
  packages/common/src/helpers/arrays.ts
Labels: feature

#2712 chore: BN improv / ISA
  apps/wallet-mobile/index.js
  packages/common/src/observer/observer.ts
Labels: chore

#2714 fix(swap): Slippage
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  packages/swap/src/helpers/orders/getQuantityWithSlippage.test.ts
  packages/swap/src/helpers/orders/getQuantityWithSlippage.ts
  packages/swap/src/helpers/orders/makeLimitOrder.ts
  packages/swap/src/helpers/orders/makePossibleMarketOrder.ts
Labels: fix

#2715 Fixes limit recalc and parseFromText edge cases
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.ts
  packages/swap/src/translators/reactjs/state/state.test.ts
  packages/swap/src/translators/reactjs/state/state.ts
  packages/swap/src/utils/quantities.test.ts
  packages/swap/src/utils/quantities.ts
Labels: fix

#2719 chore: Change counter text
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/i18n/global-messages.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
  apps/wallet-mobile/translations/messages/src/i18n/global-messages.json
Labels: chore

#2722 fix: add refresh btn logic
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/TopTokenActions.tsx
Labels: fix

#2723 fix: Update limit price on refresh
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/TopTokenActions.tsx
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.ts
  packages/swap/src/utils/quantities.test.ts
  packages/swap/src/utils/quantities.ts
Labels: fix

#2726 refactor: tests unsupported pools
  apps/wallet-mobile/src/features/Swap/common/mocks.ts
  packages/swap/src/adapters/openswap-api/openswap.mocks.ts
  packages/swap/src/helpers/transformers.test.ts
  packages/swap/src/helpers/transformers.ts
  packages/swap/src/index.ts
  packages/types/src/swap/order.ts
  packages/types/src/swap/pool.ts
Labels: refactor

#2724 fix: keyboard view
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
Labels: fix

#2727 fix: typos and upd expandable card api
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.stories.tsx
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
Labels: fix

#2728 fix(swap): Non ada pair selection
  packages/swap/package.json
  packages/swap/src/translators/reactjs/state/state.test.ts
  packages/swap/src/translators/reactjs/state/state.ts
Labels: fix

#2730 fix/refactor: error message and datum
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTx.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxWithPassword.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/unsignedTx/unsignedTx.ts
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/src/yoroi-wallets/types/yoroi.ts
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: fix

#2717 fix: Show some fees and allow selected pool to be undefined
  apps/wallet-mobile/src/features/Swap/common/useSwapTx.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  packages/common/package.json
  packages/swap/package.json
  packages/swap/src/helpers/orders/getLiquidityProviderFee.ts
  packages/swap/src/helpers/orders/getMuesliswapFrontendFee.ts
  packages/swap/src/helpers/orders/getTotalFees.test.ts
  packages/swap/src/helpers/orders/getTotalFees.ts
  packages/swap/src/helpers/transformers.ts
  packages/swap/src/index.ts
  packages/swap/src/translators/reactjs/provider/SwapProvider.tsx
  packages/swap/src/translators/reactjs/state/state.test.ts
  packages/swap/src/translators/reactjs/state/state.ts
Labels: fix

#2732 chore: add datum arg to ledger tx sign
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  yarn.lock
Labels: fix, chore

#2733 fix(swap): Fix swap order cancellation witnesses creation
  apps/wallet-mobile/src/yoroi-wallets/cardano/common/signatureUtils.ts
Labels: fix

#2731 chore: New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#2735 fix(swap): Fix price input format
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.ts
  packages/swap/src/utils/quantities.ts
Labels: fix

#2736 fix(swap): No liquidity pool available
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: fix

#2737 chore: New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore
