Repository Emurgo/yoroi, pull requests merged in 2023-04, with the labels that each got.

#2424 Extract search logic from nfts part2
  src/Nfts/ImageGallery/ImageGallery.tsx
  src/Nfts/Nfts.tsx
  src/Nfts/NftsNavigator.tsx
  src/Nfts/filterNfts.test.ts
  src/Nfts/filterNfts.ts
  src/Nfts/hooks.ts
  src/navigation.ts
  src/yoroi-wallets/mocks/wallet.ts
Labels: refactor

#2425 Update SelectTokenFromList to use query in the nav bar
  .storybook/storybook.requires.js
  src/Nfts/Nfts.stories.tsx
  src/Nfts/Nfts.tsx
  src/Nfts/NftsNavigator.tsx
  src/Nfts/NoNftsScreen.stories.tsx
  src/Search/SearchBar.stories.tsx
  src/Search/SearchBar.tsx
  src/Search/SearchContext.tsx
  src/Search/SearchHeader.tsx
  src/Search/index.tsx
  src/TxHistory/TxHistoryNavigator.tsx
  src/WalletNavigator.tsx
  src/assets/img/no-assets-found.png
  src/components/Icon/Chevron.tsx
  src/features/Send/common/filterAssets.test.ts
  src/features/Send/common/filterAssets.ts
  src/features/Send/common/strings.ts
  src/features/Send/useCases/ListAmountsToSend/AddToken/InputSearch.tsx
  src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  src/features/Send/useCases/ListAmountsToSend/AddToken/Show/EmptySearchResult.stories.tsx
  src/features/Send/useCases/ListAmountsToSend/AddToken/Show/EmptySearchResult.tsx
  src/features/Send/useCases/ListAmountsToSend/AddToken/Show/MaxTokensPerTx.stories.tsx
  src/features/Send/useCases/ListAmountsToSend/AddToken/Show/MaxTokensPerTx.tsx
  src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  src/i18n/locales/en-US.json
  src/navigation.tsx
Labels: feature

#2420 Check NFT supply when parsing NFTs
  src/yoroi-wallets/cardano/api/api.ts
  src/yoroi-wallets/utils/parsing.ts
Labels: fix, dont-merge

#2430 Fix reset search before opening the list
  src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
Labels: fix

#2432 Fix keyboard type
  src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
Labels: fix

#2433 Fix nav back title on nft
  src/NftDetails/NftDetailsNavigator.tsx
  src/Nfts/NftsNavigator.tsx
Labels: fix

#2434 Fix decimal input iOS
  src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
Labels: fix

#2435 NFT details title boldness fix
  src/NftDetails/NftDetails.tsx
Labels: fix

#2437 fix(nft-gallery): Fix supply check for assets with empty name
  src/yoroi-wallets/cardano/api/api.ts
Labels: fix

#2436 Fix: counting only secondary amounts per tx
  .storybook/storybook.requires.js
  src/components/ErrorPanel/ErrorPanel.stories.tsx
  src/features/Send/common/SendContext.test.tsx
  src/features/Send/common/SendContext.tsx
  src/features/Send/common/mocks.ts
  src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  src/features/Send/useCases/ListAmountsToSend/AddToken/Show/MaxAmountsPerTx.stories.tsx
  src/features/Send/useCases/ListAmountsToSend/AddToken/Show/MaxAmountsPerTx.tsx
  src/yoroi-wallets/contants.ts
Labels: fix

#2439 fix(deserialization): Limit asset name to 32 bytes
  src/yoroi-wallets/cardano/api/utils.test.ts
  src/yoroi-wallets/cardano/api/utils.ts
  src/yoroi-wallets/cardano/utils.ts
Labels: fix

#2442 Fix always allow select the primary token
  src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
Labels: fix

#2440 Send TX Token list Tabs
  .storybook/storybook.requires.js
  src/Nfts/ImageGallery/index.ts
  src/Nfts/Nfts.tsx
  src/Search/SearchContext.tsx
  src/assets/img/no-assets-found.png
  src/components/NftImageGallery/NftImageGallery.stories.tsx
  src/components/NftImageGallery/NftImageGallery.tsx
  src/components/NftImageGallery/index.ts
  src/components/index.ts
  src/features/Send/common/NoAssetFoundImage.tsx
  src/features/Send/common/filterAssets.ts
  src/features/Send/common/filterByFungibility.test.ts
  src/features/Send/common/filterByFungibility.ts
  src/features/Send/common/filterBySearch.test.ts
  src/features/Send/common/filterBySearch.ts
  src/features/Send/common/strings.ts
  src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.stories.tsx
  src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  src/features/Send/useCases/ListAmountsToSend/AddToken/Show/EmptySearchResult.stories.tsx
  src/features/Send/useCases/ListAmountsToSend/AddToken/Show/EmptySearchResult.tsx
  src/i18n/global-messages.ts
  src/i18n/locales/en-US.json
Labels: feature

#2441 Add counter based on tab selected in the send tx token list
  src/features/Send/common/strings.ts
  src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  src/i18n/global-messages.ts
  src/i18n/locales/en-US.json
Labels: feature

#2444 Filter assets from the select token list screen when they are selected to send tx
  src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
Labels: feature

#2447 fix: SelectTokenFromList NFT to respect the limit
  src/components/NftImageGallery/NftImageGallery.tsx
  src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  src/yoroi-wallets/hooks/index.ts
Labels: fix
