Repository Emurgo/yoroi, pull requests merged in 2023-08, with the labels that each got.

#2570 chore(tos): update
  apps/wallet-mobile/src/Legal/TermsOfService/tos/en-US.md
Labels: chore

#2572 feature(settings): Analytics section
  apps/wallet-mobile/src/components/Analytics/index.ts
  apps/wallet-mobile/src/components/Icon/Analytics.tsx
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/components/index.ts
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
Labels: feature

#2573 feature(notice): analytics consent notice
  apps/wallet-mobile/src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
  apps/wallet-mobile/src/components/Analytics/Analytics.tsx
  apps/wallet-mobile/src/components/Analytics/AnalyticsNotice.tsx
  apps/wallet-mobile/src/legacy/DeveloperScreen.tsx
  apps/wallet-mobile/src/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/metrics/metricsManager.tsx
  apps/wallet-mobile/src/metrics/mocks.ts
  apps/wallet-mobile/translations/messages/src/SelectedWallet/WalletSelection/WalletSelectionScreen.json
  apps/wallet-mobile/translations/messages/src/components/Analytics/Analytics.json
Labels: feature

#2576 chore: lock/tran/cmp
  apps/wallet-mobile/src/TxHistory/PairedBalance.tsx
  apps/wallet-mobile/translations/messages/src/NftDetails/NftDetails.json
  apps/wallet-mobile/translations/messages/src/Nfts/Nfts.json
  apps/wallet-mobile/translations/messages/src/TxHistory/AssetList/AssetList.json
  apps/wallet-mobile/translations/messages/src/TxHistory/PairedBalance.json
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
Labels: chore

#2578 chore: updates ci/pkgs
  .github/actions/wallet-mobile/action.yml
  .github/workflows/wallet-mobile-checks-avoid.yml
  .github/workflows/wallet-mobile-checks.yml
  .husky/pre-commit
  apps/wallet-mobile/package.json
  package.json
  packages/api-openswap/.editorconfig
  packages/api-openswap/.nvmrc
  packages/api-openswap/README.md
  packages/api-openswap/index.ts
  packages/api-openswap/package.json
  packages/api-openswap/scripts/flowgen.sh
  packages/api-openswap/src/api.ts
  packages/api-openswap/src/config.ts
  packages/api-openswap/src/index.ts
  packages/api-openswap/src/orders.spec.ts
  packages/api-openswap/src/orders.ts
  packages/api-openswap/src/pools.spec.ts
  packages/api-openswap/src/pools.ts
  packages/api-openswap/src/tokens.spec.ts
  packages/api-openswap/src/tokens.ts
  packages/api-openswap/src/types.ts
  packages/api-openswap/tsconfig.json
  packages/react-swap/.editorconfig
  packages/react-swap/package.json
  packages/react-swap/src/adapters/api.ts
  packages/react-swap/src/translators/reactjs.test.tsx
  packages/react-swap/tsconfig.build.json
  packages/react-swap/tsconfig.json
  packages/types/package.json
  packages/types/src/index.ts
  packages/types/src/metrics/module.ts
  packages/types/src/metrics/nft.ts
  packages/types/src/metrics/properties.ts
  packages/types/src/metrics/storage.ts
  packages/types/src/metrics/swap.ts
  packages/types/src/metrics/track.ts
  packages/types/src/metrics/wallet.ts
  yarn.lock
Labels: chore

#2579 fix(build): Fix bob config in react-swap
  packages/react-swap/package.json
Labels: fix

#2581 fix: Yoroi package resolution
  apps/wallet-mobile/package.json
  metro.config.js
  packages/api-openswap/package.json
  packages/react-swap/package.json
  packages/react-swap/src/index.ts
  packages/types/package.json
  yarn.lock
Labels: fix

#2583 chore: Upgrade yoroi lib and cross-csl
  apps/wallet-mobile/package.json
  yarn.lock
Labels: dependencies, chore

#2586 chore: Introduced dependency cruiser for the pkgs
  .gitignore
  apps/wallet-mobile/.gitignore
  apps/wallet-mobile/dependency-graph.svg
  apps/wallet-mobile/package.json
  packages/api-openswap/.dependency-cruiser.js
  packages/api-openswap/package.json
  packages/react-swap/.dependency-cruiser.js
  packages/react-swap/package.json
  packages/types/.dependency-cruiser.js
  packages/types/package.json
  yarn.lock
Labels: chore

#2588 fix(sentry): Restore sentry
  apps/wallet-mobile/.env
  apps/wallet-mobile/.env.nightly
  apps/wallet-mobile/.env.production
  apps/wallet-mobile/.env.staging
  apps/wallet-mobile/app.json
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/InitApp.tsx
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/legacy/config.ts
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
  yarn.lock
Labels: fix

#2587 chore: Added new metrics event nft image viewed
  apps/wallet-mobile/src/NftDetails/NftDetailsImage.tsx
  apps/wallet-mobile/src/metrics/ampli/index.ts
  apps/wallet-mobile/src/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/metrics/metricsManager.tsx
  apps/wallet-mobile/src/metrics/mocks.ts
Labels: chore

#2590 chore: New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#2591 chore: Renamed swap
  apps/wallet-mobile/package.json
  metro.config.js
  packages/swap/.dependency-cruiser.js
  packages/swap/.gitignore
  packages/swap/.watchmanconfig
  packages/swap/babel.config.js
  packages/swap/jest.setup.js
  packages/swap/package.json
  packages/swap/scripts/flowgen.sh
  packages/swap/src/adapters/api.ts
  packages/swap/src/adapters/storage.mocks.ts
  packages/swap/src/adapters/storage.test.ts
  packages/swap/src/adapters/storage.ts
  packages/swap/src/adapters/transformers.test.ts
  packages/swap/src/adapters/transformers.ts
  packages/swap/src/index.ts
  packages/swap/src/translators/reactjs.tsx
  packages/swap/src/translators/swapManager.mocks.ts
  packages/swap/src/translators/swapManager.ts
  packages/swap/src/translators/swapState.ts
  packages/swap/tsconfig.build.json
  packages/swap/tsconfig.json
Labels: chore

#2589 chore: Added order helpers
  packages/swap/src/helpers/order.test.ts
  packages/swap/src/helpers/order.ts
  packages/swap/src/index.ts
Labels: chore

#2594 fix: Github workflow
  .github/workflows/wallet-mobile-checks.yml
  .github/workflows/wallet-mobile-gitlab.yml
Labels: chore

#2593 fix: Order tests/type
  packages/swap/package.json
  packages/swap/src/helpers/order.test.ts
  packages/swap/src/helpers/order.ts
  packages/types/src/swap/pool.ts
Labels: fix

#2597 fix(swap): Fix build by changing fee type to string
  packages/swap/src/adapters/transformers.test.ts
  packages/swap/src/adapters/transformers.ts
  packages/swap/src/helpers/order.ts
  packages/swap/src/translators/swapManager.mocks.ts
Labels: fix

#2598 chore: Nav headers revamp (theming fix)
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/NftDetails/NftDetailsNavigator.tsx
  apps/wallet-mobile/src/Nfts/NftsNavigator.tsx
  apps/wallet-mobile/src/Receive/ReceiveScreen.tsx
  apps/wallet-mobile/src/Search/SearchContext.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Initialization/InitializationNavigator.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/features/Settings/Currency/ChangeCurrencyScreen.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/Settings/TermsOfService/TermsOfServiceScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/StartSwapScreen.tsx
  apps/wallet-mobile/src/legacy/DeveloperScreen.tsx
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/src/theme/config.ts
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/NftDetails/NftDetailsNavigator.json
  apps/wallet-mobile/translations/messages/src/Nfts/Nfts.json
  apps/wallet-mobile/translations/messages/src/Receive/ReceiveScreen.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
Labels: feature

#2599 fix: Analytics scrolling
  apps/wallet-mobile/src/components/Analytics/Analytics.tsx
Labels: fix

#2602 chore: Refactor analytics settings
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/features/Settings/SettingsItems.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/ToggleAnalyticsSettings/ToggleAnalyticsSettings.stories.tsx
  apps/wallet-mobile/src/features/ToggleAnalyticsSettings/ToggleAnalyticsSettingsNavigator.tsx
  apps/wallet-mobile/src/features/ToggleAnalyticsSettings/ToggleAnalyticsSettingsScreen.tsx
  apps/wallet-mobile/src/features/ToggleAnalyticsSettings/index.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/components/Analytics/Analytics.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/features/ToggleAnalyticsSettings/ToggleAnalyticsSettingsNavigator.json
Labels: chore

#2600 refactor: Pin revamp
  apps/wallet-mobile/src/auth/ChangePinScreen/ChangePinScreen.tsx
  apps/wallet-mobile/src/auth/CreatePinInput/CreatePinInput.tsx
  apps/wallet-mobile/src/auth/CreatePinScreen/CreatePinScreen.tsx
  apps/wallet-mobile/src/auth/PinInput/PinInput.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
Labels: refactor

#2606 chore: Added analytics "on read more" link
  apps/wallet-mobile/src/features/Initialization/AnalyticsChangedScreen/AnalyticsChangedScreen.tsx
  apps/wallet-mobile/src/features/Initialization/AnalyticsNoticeScreen/AnalyticsNoticeScreen.tsx
  apps/wallet-mobile/src/features/ToggleAnalyticsSettings/ToggleAnalyticsSettingsScreen.tsx
Labels: chore

#2605 chore: Action buttons color revamp
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/TxHistory/TxDetails/TxDetails.tsx
  apps/wallet-mobile/src/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryList/TxHistoryListItem.tsx
  apps/wallet-mobile/src/components/Icon/Direction.tsx
  apps/wallet-mobile/src/features/Initialization/InitialScreen/InitialScreen.tsx
  apps/wallet-mobile/src/theme/config.ts
Labels: feature

#2609 fix(analytics): Hide Yoroi logo in analytics settings
  apps/wallet-mobile/src/components/Analytics/Analytics.tsx
Labels: fix

#2608 fix(revamp): create wallet header style
  apps/wallet-mobile/src/WalletInit/WalletInit/WalletInitScreen.tsx
  apps/wallet-mobile/src/WalletInit/WalletInitNavigator.tsx
  apps/wallet-mobile/src/navigation.tsx
Labels: fix

#2611 chore(analytics): Remove feature flag
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/features/index.ts
  apps/wallet-mobile/translations/messages/src/TxHistory/TxDetails/TxDetails.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryList/TxHistoryListItem.json
  apps/wallet-mobile/translations/messages/src/WalletInit/WalletInit/WalletInitScreen.json
  apps/wallet-mobile/translations/messages/src/WalletInit/WalletInitNavigator.json
  apps/wallet-mobile/translations/messages/src/auth/CreatePinInput/CreatePinInput.json
  apps/wallet-mobile/translations/messages/src/components/Analytics/Analytics.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/features/ToggleAnalyticsSettings/ToggleAnalyticsSettingsNavigator.json
Labels: chore

#2612 chore: Action banner buttons revamp
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/Swap.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
Labels: chore

#2614 chore: Action banner swap button
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/components/Icon/Swap.tsx
Labels: chore

#2616 fix(analytics): Improve text styling and add translations on ToS Screens
  apps/wallet-mobile/src/components/BlueCheckbox/BlueCheckbox.tsx
  apps/wallet-mobile/src/components/YoroiLogo/YoroiLogo.tsx
  apps/wallet-mobile/src/features/Initialization/InitialScreen/InitialScreen.tsx
  apps/wallet-mobile/src/features/Initialization/TermsOfServiceChangedScreen/TermsOfServiceChangedScreen.tsx
  apps/wallet-mobile/src/features/Initialization/common/strings.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/legacy/config.ts
  apps/wallet-mobile/translations/messages/src/components/YoroiLogo/YoroiLogo.json
  apps/wallet-mobile/translations/messages/src/features/Initialization/common/strings.json
Labels: fix

#2617 fix(legal): Fix markdown styles for ToS and Privacy Policy
  apps/wallet-mobile/src/Legal/PrivacyPolicy/PrivacyPolicy.tsx
  apps/wallet-mobile/src/Legal/TermsOfService/TermsOfService.tsx
Labels: fix

#2624 fix(analytics): nft event when focus page
  apps/wallet-mobile/src/Nfts/Nfts.tsx
Labels: fix

#2621 fix(analytics): minor issues
  apps/wallet-mobile/src/components/YoroiLogo/YoroiLogo.tsx
  apps/wallet-mobile/src/features/Initialization/InitialScreen/InitialScreen.tsx
  apps/wallet-mobile/src/features/Initialization/common/strings.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
Labels: fix

#2623 fix(tos): Update ToS
  apps/wallet-mobile/src/Legal/TermsOfService/tos/en-US.md
Labels: fix

#2622 fix: pin subtitle
  apps/wallet-mobile/src/auth/PinInput/PinInput.tsx
Labels: fix

#2627 fix: Fix legal agreement in dev and update agreement date
  apps/wallet-mobile/src/features/Initialization/common/index.ts
  apps/wallet-mobile/src/features/Initialization/common/terms.ts
  apps/wallet-mobile/src/legacy/DeveloperScreen.tsx
  apps/wallet-mobile/src/legacy/config.ts
  apps/wallet-mobile/translations/messages/src/Nfts/Nfts.json
  apps/wallet-mobile/translations/messages/src/features/Initialization/common/strings.json
Labels: fix

#2629 fix: restore qr scanner on focus
  apps/wallet-mobile/src/components/QRCodeScanner/QRCodeScanner.tsx
Labels: fix

#2628 fix(settings): Disable change PIN setting when biometrics are enabled
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
Labels: fix

#2630 fix: mnemonic input
  apps/wallet-mobile/src/WalletInit/MnemonicInput/MnemonicInput.tsx
Labels: fix

#2632 fix: tx to byron address
  apps/wallet-mobile/__mocks__/@emurgo/csl-mobile-bridge.js
  apps/wallet-mobile/__mocks__/@emurgo/react-native-haskell-shelley.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/common.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/getMinAmounts.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/getMinAmounts.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  yarn.lock
Labels: fix

#2634 feature: Disable swap for zero quantities
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/translations/messages/src/WalletInit/MnemonicInput/MnemonicInput.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
Labels: feature

#2635 feature: Banxa module
  metro.config.js
  packages/banxa/.dependency-cruiser.js
  packages/banxa/.gitignore
  packages/banxa/.watchmanconfig
  packages/banxa/README.md
  packages/banxa/babel.config.js
  packages/banxa/jest.setup.js
  packages/banxa/package.json
  packages/banxa/scripts/flowgen.sh
  packages/banxa/src/adapters/errors.ts
  packages/banxa/src/adapters/zod-errors.test.ts
  packages/banxa/src/adapters/zod-errors.ts
  packages/banxa/src/adapters/zod-schema.ts
  packages/banxa/src/helpers/blockchain-code.test.ts
  packages/banxa/src/helpers/blockchain-code.ts
  packages/banxa/src/helpers/coin-types.test.ts
  packages/banxa/src/helpers/coin-types.ts
  packages/banxa/src/helpers/fiat-types.test.ts
  packages/banxa/src/helpers/fiat-types.ts
  packages/banxa/src/helpers/wallet-address.test.ts
  packages/banxa/src/helpers/wallet-address.ts
  packages/banxa/src/index.ts
  packages/banxa/src/translators/domains.ts
  packages/banxa/src/translators/module.test.ts
  packages/banxa/src/translators/module.ts
  packages/banxa/tsconfig.build.json
  packages/banxa/tsconfig.json
  yarn.lock
Labels: feature

#2638 feat(swap): switch and empty state
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.stories.tsx
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditMarketPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/EditSlippage.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/ShowSlippageActions.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/ClearQuantities.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/ShowTokenActions.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/SwitchTokens.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowTokenActions/SwitchTokens.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/TouchedContext.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/ListOrders.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/StartSwapScreen.stories.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: feature

#2641 fix: typos
  apps/wallet-mobile/Preparation_common_steps.md
  apps/wallet-mobile/Preparing_and_building_Android.md
  apps/wallet-mobile/src/metrics/README.md
Labels: fix

#2637 feat(analytics): swap
  apps/wallet-mobile/ampli.json
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/EditSlippageScreen/EditSlippageScreen.tsx
  apps/wallet-mobile/src/metrics/ampli/index.ts
  apps/wallet-mobile/src/metrics/metricsManager.test.tsx
Labels: feature

#2640 feature(swap): order values remain when switching between limit and market
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditMarketPrice.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowMarketPrice.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowMarketPrice.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
Labels: feature

#2644 chore(swap): tooltip check
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/BottomSheet/index.ts
  apps/wallet-mobile/src/components/BottomSheetModal/BottomSheetModal.stories.tsx
  apps/wallet-mobile/src/components/BottomSheetModal/BottomSheetModal.tsx
  apps/wallet-mobile/src/components/BottomSheetModal/index.ts
  apps/wallet-mobile/src/features/Swap/common/SelectPool/ExpendableCard/ExpandableInfoCard.stories.tsx
  apps/wallet-mobile/src/features/Swap/common/SelectPool/ExpendableCard/ExpandableInfoCard.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/ShowSlippageInfo.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/ClosedOrders.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/ClosedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
Labels: chore

#2647 chore(swap): add confirmation screen real values
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/i18n/global-messages.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/TxHistory/PairedBalance.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
  apps/wallet-mobile/translations/messages/src/i18n/global-messages.json
Labels: chore

#2650 chore(swap): sell/from asset list check
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/TxHistory/PairedBalance.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: chore

#2646 refactor: Internationalize numbers
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.tsx
  apps/wallet-mobile/src/i18n/LanguageProvider.tsx
  apps/wallet-mobile/src/i18n/languages.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.ts
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: refactor

#2652 chore(swap): Some improvements
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/ShowMarketPrice.tsx
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.ts
Labels: chore

#2653 Fix buy/sell price update when updating the other field
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.tsx
  apps/wallet-mobile/src/yoroi-wallets/utils/utils.ts
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: fix

#2654 fix (swap)
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  packages/swap/src/adapters/transformers.test.ts
  packages/swap/src/adapters/transformers.ts
Labels: fix
