Repository Emurgo/yoroi, pull requests merged in 2023-11, with the labels that each got.

#2860 refactor: token list api source
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/features/Swap/SwapNavigator.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  lerna.json
  packages/openswap/src/api.ts
  packages/openswap/src/config.ts
  packages/openswap/src/index.ts
  packages/openswap/src/token-pairs.spec.ts
  packages/openswap/src/token-pairs.ts
  packages/openswap/src/tokens.spec.ts
  packages/openswap/src/tokens.ts
  packages/openswap/src/types.ts
  packages/swap/src/adapters/openswap-api/api.mocks.ts
  packages/swap/src/adapters/openswap-api/api.test.ts
  packages/swap/src/adapters/openswap-api/api.ts
  packages/swap/src/adapters/openswap-api/openswap.mocks.ts
  packages/swap/src/helpers/transformers.test.ts
  packages/swap/src/helpers/transformers.ts
  packages/swap/src/index.ts
  packages/swap/src/manager.mocks.ts
  packages/swap/src/manager.test.ts
  packages/swap/src/manager.ts
  packages/swap/src/translators/reactjs/hooks/useSwapTokensByPair.test.tsx
  packages/swap/src/translators/reactjs/hooks/useSwapTokensByPair.tsx
  packages/swap/src/translators/reactjs/hooks/useSwapTokensOnlyVerified.test.tsx
  packages/swap/src/translators/reactjs/hooks/useSwapTokensOnlyVerified.tsx
  packages/types/src/swap/api.ts
  packages/types/src/swap/manager.ts
Labels: refactor

#2862 fix(swap): Show slippage warning when minReceived is 0
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ShowSubmittedTxScreen/ShowSubmittedTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/SlippageWarning/SlippageWarning.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/SlippageWarning/SlippageWarning.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/SlippageWarning/index.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: in-clarification

#2863 fix(swap): Fix button font weight and paddings
  apps/wallet-mobile/src/features/Swap/common/ButtonGroup/ButtonGroup.tsx
Labels: fix

#2865 chore: v bumper
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/banxa/package.json
  packages/common/package.json
  packages/openswap/package.json
  packages/swap/package.json
  packages/types/package.json
  scripts/bump-pkgs.sh
  scripts/install-pkgs.sh
Labels: chore

#2867 fix: avoid calc same token selection
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
Labels: fix

#2868 Fix: Use react-native-localize for language detection and decimal separator
  apps/wallet-mobile/jestSetup.ts
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/i18n/getRegion.test.ts
  apps/wallet-mobile/src/i18n/getRegion.ts
  apps/wallet-mobile/src/i18n/initialization.ts
  apps/wallet-mobile/src/i18n/languages.ts
  apps/wallet-mobile/src/i18n/transformers/asYoroiLocale.test.ts
  apps/wallet-mobile/src/i18n/transformers/asYoroiLocale.ts
  yarn.lock
Labels: fix

#2869 fix(slippage): Increase bottom padding in slippage warning
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/SlippageWarning/SlippageWarning.tsx
Labels: fix

#2871 fix(swap): Change order details font sizes
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
Labels: fix

#2870 fix(banxa): Fix modal content line height and modal height
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
Labels: fix

#2872 fix: Incorrect change pair order behaviour
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/EditBuyAmount.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/EditSellAmount.tsx
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: fix

#2873 fix: Reset form errors when changing token
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
Labels: fix

#2877 fix(swap): modal swip down gesture
  apps/wallet-mobile/src/components/Modal/ModalContext.tsx
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
Labels: fix

#2876 fix: Go to select token when clicking disabled input
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: fix

#2881 chore: New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#2878 fix: total value in summary
  apps/wallet-mobile/src/TxHistory/BalanceBanner.tsx
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/components/PairedBalance/PairedBalance.stories.tsx
  apps/wallet-mobile/src/components/PairedBalance/PairedBalance.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/PairedBalance.json
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.test.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.ts
  packages/swap/src/translators/reactjs/state/state.ts
Labels: fix

#2882 feature(swap): list orders empty state
  apps/wallet-mobile/src/Search/SearchContext.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/EmptyCompletedOrdersLogo.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/EmptyOpenOrdersLogo.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/ListOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/components/PairedBalance/PairedBalance.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: feature

#2884 fix: token selection
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
Labels: fix

#2883 chore: Swap/list error state
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/Swap/common/ServiceUnavailable/ConectionErrorImage.tsx
  apps/wallet-mobile/src/features/Swap/common/ServiceUnavailable/ServiceUnavailable.stories.tsx
  apps/wallet-mobile/src/features/Swap/common/ServiceUnavailable/ServiceUnavailable.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ShowSubmittedTxScreen/ShowSubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: chore

#2885 fix: buy modal
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
Labels: fix

#2887 fix: buy modal
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
Labels: fix

#2891 fix: modal
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
Labels: fix

#2893 fix(swap): empty orders list image
  apps/wallet-mobile/src/assets/img/illustration-swap-completed-order.png
  apps/wallet-mobile/src/assets/img/illustration-swap-open-order.png
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/EmptyCompletedOrdersLogo.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/EmptyOpenOrdersLogo.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
Labels: fix

#2897 fix: Limit price input color
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
Labels: fix

#2895 feature(swap): min received 0 warning
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: feature

#2898 feature: Swap/change logic when user is picking the same asset
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
Labels: feature

#2900 fix: input colors
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
Labels: fix

#2902 fix(swap): Switch display values when SwitchTouched
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
Labels: fix

#2903 fix: text overflow on expandable card
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.tsx
Labels: fix

#2910 chore: upgrade yarn
  packages/api/package.json
  packages/banxa/package.json
  packages/common/package.json
  packages/swap/package.json
  packages/types/package.json
Labels: chore

#2913 fix(swap): Prevent page viewed event from accidentally firing
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
Labels: fix

#2916 feature(scan): interpret crypto links
  apps/wallet-mobile/.gitignore
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/scripts/build-testing-codes.js
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/WalletInit/ImportReadOnlyWallet/ImportReadOnlyWalletScreen.tsx
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/components/CameraCodeScanner/CameraCodeScanner.stories.tsx
  apps/wallet-mobile/src/components/CameraCodeScanner/CameraCodeScanner.tsx
  apps/wallet-mobile/src/components/CameraCodeScanner/index.ts
  apps/wallet-mobile/src/components/QRCodeScanner/index.ts
  apps/wallet-mobile/src/components/index.ts
  apps/wallet-mobile/src/features/Scan/common/CodeScannerButton.stories.tsx
  apps/wallet-mobile/src/features/Scan/common/CodeScannerButton.tsx
  apps/wallet-mobile/src/features/Scan/common/illustrations/CameraPermissionDeniedIlustration.tsx
  apps/wallet-mobile/src/features/Scan/common/mocks.ts
  apps/wallet-mobile/src/features/Scan/common/parsers.test.ts
  apps/wallet-mobile/src/features/Scan/common/parsers.ts
  apps/wallet-mobile/src/features/Scan/common/types.ts
  apps/wallet-mobile/src/features/Scan/common/useDialogs.tsx
  apps/wallet-mobile/src/features/Scan/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Scan/common/useScanErrorResolver.tsx
  apps/wallet-mobile/src/features/Scan/common/useStrings.tsx
  apps/wallet-mobile/src/features/Scan/common/useTriggerScanAction.tsx
  apps/wallet-mobile/src/features/Scan/useCases/ScanCodeScreen.stories.tsx
  apps/wallet-mobile/src/features/Scan/useCases/ScanCodeScreen.tsx
  apps/wallet-mobile/src/features/Scan/useCases/ShowCameraPermissionDeniedScreen/OpenDeviceAppSettingsButton.stories.tsx
  apps/wallet-mobile/src/features/Scan/useCases/ShowCameraPermissionDeniedScreen/OpenDeviceAppSettingsButton.tsx
  apps/wallet-mobile/src/features/Scan/useCases/ShowCameraPermissionDeniedScreen/ShowCameraPermissionDeniedScreen.stories.tsx
  apps/wallet-mobile/src/features/Scan/useCases/ShowCameraPermissionDeniedScreen/ShowCameraPermissionDeniedScreen.tsx
  apps/wallet-mobile/src/features/Send/common/navigation.ts
  apps/wallet-mobile/src/features/Send/common/strings.ts
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ReadQRCodeScreen.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ReadQRCodeScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/src/utils/feedback.ts
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/WalletInit/ImportReadOnlyWallet/ImportReadOnlyWalletScreen.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Scan/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/Scan/common/useStrings.json
  apps/wallet-mobile/translations/messages/src/features/Send/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/StartActionFromQRCodeScanning/common/strings.json
  metro.config.js
Labels: feature

#2924 fix: Add multiline text to pool selection
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
Labels: fix
