Repository Emurgo/yoroi, pull requests merged in 2023-02, with the labels that each got.

#2305 Managing paired balance errors
  src/TxHistory/BalanceBanner.tsx
  src/TxHistory/TxHistory.tsx
  src/components/Boundary/Boundary.tsx
  src/i18n/locales/en-US.json
  storybook/mocks/wallet.ts
Labels: fix

#2317 refactor(provider): deprecated
  src/Dashboard/Dashboard.tsx
  src/SelectedWallet/WalletSelection/WalletListItem.tsx
  src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
  src/Staking/StakingCenter/StakingCenter.tsx
  src/Storage/migrations/walletMeta.test.ts
  src/WalletInit/CreateWallet/CreateWalletScreen.tsx
  src/WalletInit/MnemonicCheck/MnemonicCheckScreen.tsx
  src/WalletInit/MnemonicShow/MnemonicShowScreen.tsx
  src/WalletInit/RestoreWallet/RestoreWalletScreen.tsx
  src/WalletInit/VerifyRestoredWallet/VerifyRestoredWalletScreen.tsx
  src/WalletInit/WalletCredentials/WalletCredentialsScreen.tsx
  src/WalletInit/WalletFreshInit/WalletFreshInitScreen.tsx
  src/WalletInit/WalletInit/WalletInitScreen.tsx
  src/auth/hooks.test.ts
  src/hooks/index.ts
  src/legacy/DeveloperScreen.tsx
  src/legacy/config.ts
  src/legacy/networks.ts
  src/legacy/state.ts
  src/navigation.ts
  src/yoroi-wallets/cardano/ShelleyWallet.test.ts
  src/yoroi-wallets/cardano/ShelleyWallet.ts
  src/yoroi-wallets/cardano/__snapshots__/ShelleyWallet.test.ts.snap
  src/yoroi-wallets/cardano/types.ts
  src/yoroi-wallets/types/other.ts
  src/yoroi-wallets/walletManager.test.ts
  src/yoroi-wallets/walletManager.ts
  storybook/mocks/wallet.ts
Labels: refactor

#2318 chore(components): ErrorPanel
  src/components/ErrorPanel/ErrorPanel.stories.tsx
  src/components/ErrorPanel/ErrorPanel.tsx
  storybook/storyLoader.js
Labels: chore

#2325 chore(ScannerButton): navbar -> input ador
  src/Send/ScannerButton.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/TxHistory/TxHistoryNavigator.tsx
  src/assets/img/qr_code.png
  src/components/TextInput/TextInput.tsx
Labels: chore

#2324 Memos UI
  src/Send/ConfirmScreen/ConfirmScreen.tsx
  src/Send/Context/SendContext.tsx
  src/Send/Memo.tsx
  src/Send/SendScreen/SendScreen.tsx
  src/TxHistory/TxDetails/TxDetails.tsx
  src/WalletInit/MnemonicInput/MnemonicInput.tsx
  src/components/TextInput/TextInput.tsx
  src/hooks/index.ts
  src/i18n/locales/en-US.json
Labels: feature

#2339 Refactor moderation status fetching
  src/NftDetails/NftDetails.tsx
  src/Nfts/ImageGallery/ImageGallery.tsx
  src/Nfts/hooks.ts
  src/hooks/index.ts
Labels: chore

#2343 Use NFT Thumbnail in NFT Gallery
  src/Nfts/ImageGallery/ImageGallery.tsx
Labels: fix

#2342 Fix NFT parsing
  src/yoroi-wallets/cardano/api/api.ts
  src/yoroi-wallets/cardano/nfts.ts
Labels: fix

#2347 Do not show NFTs that do not belong to the wallet anymore
  src/yoroi-wallets/cardano/api/api.ts
  src/yoroi-wallets/cardano/nfts.ts
Labels: fix

#2351 Hotfix/4.9.4
  android/app/build.gradle
  ios/emurgo.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: hotfix

#2356 keyboard spacer on android fix
  src/components/KeyboardSpacer.tsx
Labels: fix

#2357 Token registry entry check fix
  src/yoroi-wallets/cardano/api/api.ts
Labels: fix

#2354 Do not throw errors when parsing NFTs
  src/yoroi-wallets/cardano/api/api.ts
  src/yoroi-wallets/utils/parsing.ts
Labels: fix
