Repository Emurgo/yoroi, pull requests merged in 2023-12, with the labels that each got.

#2933 fix: hide qr when its a read-only wallet
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
Labels: fix

#2935 fix: keyboard avoiding android send screen
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
Labels: fix

#2894 feature: Use cdn for NFT images
  apps/wallet-mobile/src/NftDetails/NftDetails.tsx
  apps/wallet-mobile/src/NftDetails/NftDetailsImage.tsx
  apps/wallet-mobile/src/components/NftImageGallery/NftImageGallery.tsx
  apps/wallet-mobile/src/components/NftPreview/NftPreview.stories.tsx
  apps/wallet-mobile/src/components/NftPreview/NftPreview.tsx
  apps/wallet-mobile/src/components/TokenIcon/ModeratedNftIcon.tsx
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/translations/messages/src/NftDetails/NftDetails.json
Labels: feature

#2940 fix: Add image/svg to supported images
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: fix

#2936 refactor: apply KeyBoardAvoidingView Wrapper
  apps/wallet-mobile/src/Catalyst/ConfirmVotingTx.tsx
  apps/wallet-mobile/src/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  apps/wallet-mobile/src/WalletInit/WalletForm.tsx
  apps/wallet-mobile/src/WalletInit/WalletNameForm/WalletNameForm.tsx
  apps/wallet-mobile/src/components/KeyboardAvoidingView/KeyboardAvoidingView.tsx
  apps/wallet-mobile/src/components/KeyboardAvoidingView/index.ts
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/components/ModalScreenWrapper/ModalScreenWrapper.tsx
  apps/wallet-mobile/src/components/index.ts
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/EditSlippageScreen/EditSlippageScreen.tsx
  apps/wallet-mobile/translations/messages/src/Catalyst/ConfirmVotingTx.json
  apps/wallet-mobile/translations/messages/src/Staking/DelegationConfirmation/DelegationConfirmation.json
  apps/wallet-mobile/translations/messages/src/WalletInit/WalletForm.json
  apps/wallet-mobile/translations/messages/src/WalletInit/WalletNameForm/WalletNameForm.json
Labels: refactor

#2943 fix: Change completed orders design
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
Labels: fix

#2942 feature(swap): Added the price impact to calculations
  packages/swap/src/helpers/mocks.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.test.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.ts
  packages/swap/src/helpers/pools/getBestPoolCalculation.test.ts
  packages/swap/src/translators/reactjs/state/state.ts
Labels: feature

#2945 refactor: type
  apps/wallet-mobile/src/components/TextInput/TextInput.tsx
Labels: refactor

#2947 fix(governance): Design updates
  apps/wallet-mobile/src/components/ConfirmTxWithSpendingPasswordModal/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/common/Action/Action.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/mocks.ts
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/illustrations/GovernanceImage.tsx
  apps/wallet-mobile/src/features/Staking/Governance/illustrations/index.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/EnterDrepIdModal/EnterDrepIdModal.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/i18n/global-messages.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
  apps/wallet-mobile/translations/messages/src/i18n/global-messages.json
  packages/staking/src/governance/helpers/index.ts
  packages/staking/src/governance/helpers/parsing.test.ts
  packages/staking/src/governance/helpers/parsing.ts
  packages/staking/src/governance/index.ts
  packages/staking/src/governance/manager.ts
  packages/staking/src/governance/mocks.ts
  packages/staking/src/governance/translators/react/hooks.ts
  packages/staking/src/governance/translators/react/index.ts
Labels: fix

#2918 feature: add new api request to get protocol params
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/networks.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  packages/api/src/cardano/api/cardano-api-maker.mocks.ts
  packages/api/src/cardano/api/cardano-api-maker.test.ts
  packages/api/src/cardano/api/cardano-api-maker.ts
  packages/api/src/cardano/api/config.ts
  packages/api/src/cardano/api/parsers.ts
  packages/api/src/cardano/api/protocol-params.mocks.ts
  packages/api/src/cardano/api/protocol-params.test.ts
  packages/api/src/cardano/api/protocol-params.ts
  packages/api/src/cardano/api/token-offchain-metadata.test.ts
  packages/api/src/cardano/api/token-offchain-metadata.ts
  packages/api/src/cardano/api/token-onchain-metadata.test.ts
  packages/api/src/cardano/api/token-onchain-metadata.ts
  packages/api/src/cardano/api/token-supply.ts
  packages/api/src/index.ts
  packages/types/src/api/app.ts
  packages/types/src/api/cardano.ts
  packages/types/src/app/api.ts
  packages/types/src/index.ts
  packages/types/src/swap/manager.ts
Labels: feature

#2951 feature: Adds amplitude events
  apps/wallet-mobile/.prettierignore
  apps/wallet-mobile/src/Catalyst/VotingRegistration.tsx
  apps/wallet-mobile/src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  apps/wallet-mobile/src/Receive/ReceiveScreen.tsx
  apps/wallet-mobile/src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
  apps/wallet-mobile/src/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/src/TxHistory/AssetList/AssetList.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryList/TxHistoryList.tsx
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/metrics/ampli/index.ts
  apps/wallet-mobile/src/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/metrics/metricsManager.tsx
  apps/wallet-mobile/src/metrics/mocks.ts
  apps/wallet-mobile/translations/messages/src/Receive/ReceiveScreen.json
  apps/wallet-mobile/translations/messages/src/SelectedWallet/WalletSelection/WalletSelectionScreen.json
  apps/wallet-mobile/translations/messages/src/TxHistory/AssetList/AssetList.json
Labels: feature

#2952 chore(scripts): Bump pkgs version + scripts
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/banxa/package.json
  packages/common/package.json
  packages/links/package.json
  packages/openswap/package.json
  packages/resolver/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/types/package.json
  scripts/install-pkgs.sh
Labels: chore

#2847 refactor(swap): Refactor swap cardano utilities
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/common/signatureUtils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
Labels: dont-merge, blocked

#2953 fix: removed analytics claim ada
  apps/wallet-mobile/src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  apps/wallet-mobile/src/metrics/ampli/index.ts
  apps/wallet-mobile/src/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/metrics/metricsManager.tsx
  apps/wallet-mobile/src/metrics/mocks.ts
  apps/wallet-mobile/translations/messages/src/Staking/StakingCenter/StakingCenter.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
Labels: fix

#2955 fix: automatic address change
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
Labels: fix

#2957 fix: Ramp on/off and minor issues
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/TxHistory/TxHistoryList/RampOnOffBanner/strings.ts
  apps/wallet-mobile/src/TxHistory/TxHistoryList/TxHistoryList.tsx
  apps/wallet-mobile/src/features/RampOnOff/RampOnOffNavigator.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/DescribeAction/DescribeAction.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/MaybeShowBuyBanner/BuyBannerBig.stories.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/MaybeShowBuyBanner/BuyBannerBig.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/MaybeShowBuyBanner/BuyBannerSmall.stories.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/MaybeShowBuyBanner/BuyBannerSmall.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/MaybeShowBuyBanner/MaybeShowBuyBanner.stories.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/MaybeShowBuyBanner/MaybeShowBuyBanner.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/RampOnOffProvider.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/constants.ts
  apps/wallet-mobile/src/features/RampOnOff/common/strings.ts
  apps/wallet-mobile/src/features/RampOnOff/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/useResetShowBuyBannerSmall.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/useShowBuyBannerSmall.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/useStrings.tsx
  apps/wallet-mobile/src/features/RampOnOff/illustrations/BuyBannerIllustration.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/CreateExchange.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/EditAmount/EditAmount.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/SelectBuyOrSell/SelectBuyOrSell.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/ShowDisclaimer/ShowDisclaimer.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/ShowProviderFee/ShowProviderFee.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/ShowProviderInfo/ShowProviderInfo.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/ShowExchangeResult/ShowExchangeResult.stories.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/ShowExchangeResult/ShowExchangeResult.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/common/useSwapTx.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/translations/messages/src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.json
  apps/wallet-mobile/translations/messages/src/features/RampOnOff/common/useStrings.json
  packages/staking/src/governance/translators/react/hooks.ts
  yarn.lock
Labels: fix

#2954 feature(swap): price impact risk
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/Warning.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/features/Swap/common/PriceImpact/PriceImpact.tsx
  apps/wallet-mobile/src/features/Swap/common/PriceImpact/PriceImpactWarning.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/common/types.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/theme/palettes/lightPalette.ts
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryList/RampOnOffBanner/strings.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: feature

#2956 feature(ramp-on-off): Added metrics events
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/MaybeShowBuyBanner/BuyBannerBig.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/CreateExchange.tsx
  apps/wallet-mobile/src/features/Swap/common/PriceImpact/PriceImpact.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditLimitPrice.tsx
  apps/wallet-mobile/src/metrics/ampli/index.ts
  apps/wallet-mobile/src/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/metrics/metricsManager.tsx
  apps/wallet-mobile/src/metrics/mocks.ts
  apps/wallet-mobile/translations/messages/src/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.json
Labels: feature

#2960 fix(swap): price impact fmt and nmrlz precision
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/TxHistory/TxHistoryList/TxHistoryList.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerBig.stories.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerBig.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerSmall.stories.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerSmall.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/ShowBuyBanner.stories.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/ShowBuyBanner.tsx
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/common/constants.ts
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/Actions/AmountActions/AmountActions.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/Actions/AmountActions/AmountActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/Actions/AmountActions/ClearQuantities.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/Actions/AmountActions/ClearQuantities.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/Actions/AmountActions/SwitchTokens.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/Actions/AmountActions/SwitchTokens.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/Actions/OrderActions/OrderActions.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/Actions/OrderActions/OrderActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPrice/EditPrice.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPrice/EditPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPrice/ShowPriceImpact.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/LimitPriceWarning/index.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/SlippageWarning/index.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnLimitPrice/WarnLimitPrice.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnLimitPrice/WarnLimitPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnPriceImpact/WarnPriceImpact.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnPriceImpact/WarnPriceImpact.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnSlippage/WarnSlippage.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnSlippage/WarnSlippage.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
Labels: fix
