Repository Emurgo/yoroi, pull requests merged in 2023-06, with the labels that each got.

#2468 header title fix
  apps/wallet-mobile/src/navigation.tsx
Labels: fix

#2483 Memo trim fix
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputMemo.tsx
Labels: fix

#2485 fix: android root - fastlane
  apps/wallet-mobile/android/app/build.gradle
  apps/wallet-mobile/translations/messages/src/NftDetails/NftDetails.json
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/StartMultiTokenTx/InputMemo.json
Labels: chore

#2488 fix wallet name trim
  apps/wallet-mobile/src/Settings/ChangeWalletName/ChangeWalletName.tsx
  apps/wallet-mobile/src/WalletInit/WalletForm.tsx
Labels: fix

#2490 Reset the send tx form after submitted
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/SubmittedTx/SubmittedTxScreen.tsx
Labels: fix

#2493 fix crash when tx is submitted
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/SubmittedTx/SubmittedTxScreen.tsx
Labels: fix

#2492 fix(mat): Position QR scan icon to bottom
  apps/wallet-mobile/src/components/TextInput/TextInput.tsx
Labels: fix

#2501 chore: pro-guard
  apps/wallet-mobile/android/app/build.gradle
  apps/wallet-mobile/android/app/proguard-rules.pro
  apps/wallet-mobile/android/build.gradle
Labels: chore

#2500 upgrade cls mobile bridge
  apps/wallet-mobile/.env
  apps/wallet-mobile/.env.nightly
  apps/wallet-mobile/.env.production
  apps/wallet-mobile/.env.staging
  apps/wallet-mobile/android/app/build.gradle
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  yarn.lock
Labels: chore

#2489 fix: crash when editing NFT
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
Labels: feature

#2502 Camera permissions fix
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ReadQRCodeScreen.tsx
Labels: fix

#2503 gradle.properties fix
  apps/wallet-mobile/android/gradle.properties
Labels: fix

#2504 fix orientation
  apps/wallet-mobile/android/app/src/main/AndroidManifest.xml
Labels: fix

#2509 ledger wallet name trim fix
  apps/wallet-mobile/src/WalletInit/WalletNameForm/WalletNameForm.tsx
Labels: fix

#2508 Disable dark mode
  apps/wallet-mobile/android/app/src/dev/res/values/styles.xml
  apps/wallet-mobile/android/app/src/nightly/res/values/styles.xml
  apps/wallet-mobile/android/app/src/production/res/values/styles.xml
  apps/wallet-mobile/ios/nightly.plist
  apps/wallet-mobile/ios/yoroi/Info.plist
Labels: fix

#2505 fix: ledger catalyst voting
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/common.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/tests/mainnet/ShelleyWallet.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
Labels: fix

#2510 chore: byron deprecated / preprod btn
  apps/wallet-mobile/src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
  apps/wallet-mobile/translations/messages/src/SelectedWallet/WalletSelection/WalletSelectionScreen.json
Labels: chore

#2511 fix: rn-paper anchor
  apps/wallet-mobile/src/WalletInit/MnemonicInput/MnemonicInput.tsx
  apps/wallet-mobile/translations/messages/src/WalletInit/MnemonicInput/MnemonicInput.json
  apps/wallet-mobile/translations/messages/src/WalletInit/WalletNameForm/WalletNameForm.json
Labels: fix

#2512 Add custom back navigation to edit amount screen
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
Labels: fix

#2494 fix(transactions): Use local timezone to display transaction time
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/i18n/LanguageProvider.tsx
  yarn.lock
Labels: fix

#2513 Fix stacking registration and deregistration in testnet
  apps/wallet-mobile/src/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/unsignedTx/unsignedTx.ts
Labels: fix

#2515 chore(ledger): Update yoroi-lib to fix Ledger payload inputs order
  apps/wallet-mobile/package.json
  yarn.lock
Labels: fix

#2516 Read-Only Wallet Fix
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/WalletInit/ImportReadOnlyWallet/ImportReadOnlyWalletScreen.tsx
  apps/wallet-mobile/src/components/QRCodeScanner/QRCodeScanner.stories.tsx
  apps/wallet-mobile/src/components/QRCodeScanner/QRCodeScanner.tsx
  apps/wallet-mobile/src/components/QRCodeScanner/index.ts
  apps/wallet-mobile/src/components/index.ts
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ReadQRCodeScreen.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ReadQRCodeScreen.tsx
Labels: fix

#2517 Restoring splash screen logo and colors
  apps/wallet-mobile/android/app/src/dev/res/mipmap-hdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/dev/res/mipmap-mdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/dev/res/mipmap-xhdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/dev/res/mipmap-xxhdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/dev/res/mipmap-xxxhdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/dev/res/values/colors.xml
  apps/wallet-mobile/android/app/src/nightly/res/mipmap-hdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/nightly/res/mipmap-mdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/nightly/res/mipmap-xhdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/nightly/res/mipmap-xxhdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/nightly/res/mipmap-xxxhdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/nightly/res/values/colors.xml
  apps/wallet-mobile/android/app/src/production/res/mipmap-hdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/production/res/mipmap-mdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/production/res/mipmap-xhdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/production/res/mipmap-xxhdpi/bootsplash_logo.png
  apps/wallet-mobile/android/app/src/production/res/mipmap-xxxhdpi/bootsplash_logo.png
  apps/wallet-mobile/ios/yoroi/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png
  apps/wallet-mobile/ios/yoroi/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png
  apps/wallet-mobile/ios/yoroi/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png
  apps/wallet-mobile/src/assets/img/bootsplash_logo.png
  apps/wallet-mobile/src/assets/img/bootsplash_logo@1,5x.png
  apps/wallet-mobile/src/assets/img/bootsplash_logo@2x.png
  apps/wallet-mobile/src/assets/img/bootsplash_logo@3x.png
  apps/wallet-mobile/src/assets/img/bootsplash_logo@4x.png
Labels: chore

#2518 fix: anchor mt
  apps/wallet-mobile/src/WalletInit/MnemonicInput/MnemonicInput.tsx
Labels: fix

#2522 Qr reader refactor
  apps/wallet-mobile/src/WalletInit/ImportReadOnlyWallet/ImportReadOnlyWalletScreen.tsx
  apps/wallet-mobile/src/components/QRCodeScanner/QRCodeScanner.stories.tsx
  apps/wallet-mobile/src/components/QRCodeScanner/QRCodeScanner.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ReadQRCodeScreen.tsx
Labels: fix

#2523 ci: fastlane updates
  apps/wallet-mobile/.env
  apps/wallet-mobile/.env.nightly
  apps/wallet-mobile/.env.production
  apps/wallet-mobile/.env.staging
  apps/wallet-mobile/fastlane/Fastfile
Labels: chore

#2521 fix: Choose transport on confirm transaction press
  apps/wallet-mobile/src/Catalyst/ConfirmVotingTx.tsx
  apps/wallet-mobile/src/Staking/DelegationConfirmation/DelegationConfirmation.tsx
Labels: fix

#2507 Go Back Block In Submitted Tx Screen
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/Catalyst/QrCode.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/SubmittedTx/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/Catalyst/ConfirmVotingTx.json
  apps/wallet-mobile/translations/messages/src/Catalyst/QrCode.json
  apps/wallet-mobile/translations/messages/src/Staking/DelegationConfirmation/DelegationConfirmation.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/WalletInit/ImportReadOnlyWallet/ImportReadOnlyWalletScreen.json
Labels: fix
