Repository Emurgo/yoroi, pull requests merged in 2024-09, with the labels that each got.

#3583 chore(wallet-mobile): Enable governance on mainnet
  apps/wallet-mobile/src/kernel/config.ts
Labels: chore

#3582 feature(catalyst): reset values after registration
  README.md
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ShowQrCode/ShowQrCode.tsx
Labels: feature

#3584 chore(wallet-mobile): bumped target sdk to 34 as requested on store
  apps/wallet-mobile/android/build.gradle
Labels: chore

#3586 refactor(wallet-mobile): drop legacy primary token
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/components/AmountItem/AmountItem.stories.tsx
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/components/TokenIcon/TokenIcon.stories.tsx
  apps/wallet-mobile/src/components/TokenIcon/TokenIcon.tsx
  apps/wallet-mobile/src/features/Claim/useCases/ShowSuccessScreen.tsx
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/ShowBuyBanner.tsx
  apps/wallet-mobile/src/features/Exchange/common/useShowBuyBannerSmall.tsx
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/SecondaryTotals.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/SecondaryTotals.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.stories.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/helpers.ts
  apps/wallet-mobile/src/features/Settings/SettingsItems.tsx
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/StartSwapOrderScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AssetList.tsx
  apps/wallet-mobile/src/hooks/useTokenInfoLegacy.tsx
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  apps/wallet-mobile/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/sorting.ts
  apps/wallet-mobile/translations/messages/src/features/Transactions/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.json
  packages/portfolio/package.json
  packages/portfolio/src/index.ts
  packages/swap/package.json
  packages/transfer/package.json
Labels: refactor

#3587 feature(portfolio): Image invalidate
  apps/wallet-mobile/src/features/Portfolio/common/MediaDetails/MediaDetails.tsx
  apps/wallet-mobile/src/features/Portfolio/common/hooks/usePortfolioImage.ts
  apps/wallet-mobile/translations/messages/src/features/Nfts/useCases/Nfts.json
  apps/wallet-mobile/translations/messages/src/features/Portfolio/common/MediaDetails/MediaDetails.json
  packages/portfolio/src/adapters/dullahan-api/api-maker.mocks.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.test.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.ts
  packages/portfolio/src/adapters/dullahan-api/transformers.test.ts
  packages/portfolio/src/adapters/dullahan-api/transformers.ts
  packages/portfolio/src/adapters/dullahan-api/types.ts
  packages/portfolio/src/adapters/token-image-invalidate.mocks.ts
  packages/portfolio/src/balance-manager.test.ts
  packages/types/src/portfolio/api.ts
Labels: feature

#3589 feat(governance): add drep script id support to staking package
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/EnterDrepIdModal/EnterDrepIdModal.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
  packages/staking/src/governance/helpers/parsing.ts
  packages/staking/src/governance/manager.test.ts
  packages/staking/src/governance/manager.ts
Labels: feature

#3591 fix(wallet-mobile): language picker icon color
  apps/wallet-mobile/src/features/Initialization/InitialScreen/InitialScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Nfts/useCases/Nfts.json
Labels: fix

#3593 fix(wallet-mobile): fix app background color
  apps/wallet-mobile/jestSetup.ts
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/hooks/useStatusBar.ts
  yarn.lock
Labels: fix

#3594 chore(common): improve to-bigint
  packages/common/src/numbers/to-bigint.test.ts
  packages/common/src/numbers/to-bigint.ts
Labels: chore

#3590 fix(restore): duplicated wallet feature and plate display
  apps/wallet-mobile/src/features/Settings/RenameWalletScreen/RenameWalletScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/WalletDuplicatedModal/WalletDuplicatedModal.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/VerifyRecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreHwWallet/ConnectNanoXScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreHwWallet/SaveNanoXScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  apps/wallet-mobile/src/features/WalletManager/wallet-manager.ts
  apps/wallet-mobile/src/legacy/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/src/yoroi-wallets/utils/validators.ts
  apps/wallet-mobile/translations/messages/src/features/Settings/RenameWalletScreen/RenameWalletScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
Labels: fix

#3585 chore(wallet-mobile): Update CSL to 12.1.0-beta.1
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  packages/swap/package.json
  packages/types/package.json
  yarn.lock
Labels: chore

#3598 fix(wallet-mobile): styles changes in receive
  apps/wallet-mobile/src/components/ShareQRCodeCard/ShareQRCodeCard.tsx
  apps/wallet-mobile/src/features/Receive/common/AddressDetailCard/AddressDetailCard.tsx
  apps/wallet-mobile/src/features/Receive/useCases/DescribeSelectedAddressScreen.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/UserSummary.json
Labels: fix

#3599 fix(wallet-mobile): Normalise primary token id when parsing orders
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
Labels: fix

#3602 fix(theme): change kb to dark theme for buy/sell
  apps/wallet-mobile/src/features/Exchange/common/AmountCard/AmountCard.tsx
Labels: fix

#3601 fix(wallet-mobile): adjust custom numeric keyboard colors
  apps/wallet-mobile/src/components/NumericKeyboard.tsx
Labels: fix

#3600 fix(wallet-mobile): remove settings icon from staking header
  apps/wallet-mobile/src/legacy/Dashboard/DashboardNavigator.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/DashboardNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
Labels: fix

#3603 fix(wallet-mobile): uat updates
  apps/wallet-mobile/src/components/Button/Button.tsx
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.tsx
  apps/wallet-mobile/src/components/Icon/ArrowDown.tsx
  apps/wallet-mobile/src/components/Icon/Coins2.tsx
  apps/wallet-mobile/src/components/Icon/Direction.tsx
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/components/StepperProgress/Number1.tsx
  apps/wallet-mobile/src/components/StepperProgress/Number2.tsx
  apps/wallet-mobile/src/components/StepperProgress/Number2Empty.tsx
  apps/wallet-mobile/src/components/StepperProgress/Number3.tsx
  apps/wallet-mobile/src/components/StepperProgress/Number3Empty.tsx
  apps/wallet-mobile/src/components/StepperProgress/Number4.tsx
  apps/wallet-mobile/src/components/StepperProgress/Number4Empty.tsx
  apps/wallet-mobile/src/components/StepperProgress/StepperProgress.tsx
  apps/wallet-mobile/src/features/Portfolio/common/TokenAmountItem/TokenInfoIcon.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/Actions.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Overview/Overview.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/Check2.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/MnemonicInput.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/TextInput/TextInput.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/common/LiquidityPool/LiquidityPool.tsx
  apps/wallet-mobile/src/features/Swap/common/SwapInfoLink/SwapInfoLink.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/Actions/AmountActions/ResetQuantities.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/Actions/AmountActions/SwitchTokens.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/StartSwapOrderScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/ListOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AssetListTransaction.style.ts
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/TxDetails.tsx
  apps/wallet-mobile/src/legacy/Staking/PoolTransition/PoolTransitionModal.tsx
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: fix

#3604 fix(swap): screen freezing when changing tabs with keyboard open
  apps/wallet-mobile/src/features/Swap/SwapNavigator.tsx
Labels: fix

#3607 fix(wallet-mobile): Update favicon fallback URL
  apps/wallet-mobile/src/features/Discover/common/helpers.ts
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
Labels: fix

#3609 fix(wallet-mobile): claim mod in dev mode
  metro.config.js
Labels: fix

#3608 fix(swap): empty open/close order state
  apps/wallet-mobile/src/features/Swap/SwapNavigator.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: fix

#3610 fix(wallet-mobile): hide webview while loading it
  apps/wallet-mobile/src/legacy/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
Labels: fix

#3611 fix(settings): fix analytics UI
  apps/wallet-mobile/src/components/Analytics/Analytics.tsx
  apps/wallet-mobile/translations/messages/src/components/Analytics/Analytics.json
Labels: fix

#3612 fix(general ui): added tooltip and bounce wallet list
  apps/wallet-mobile/src/features/WalletManager/useCases/SelectWalletFromListScreen/SelectWalletFromListScreen.tsx
  apps/wallet-mobile/src/legacy/Dashboard/StakePoolInfo.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/StakePoolInfo.json
Labels: fix

#3613 fix(wallet-mobile): stepper progress crash
  apps/wallet-mobile/src/components/StepperProgress/StepperProgress.tsx
Labels: fix

#3620 chore(wallet-mobile): drop legacy useTokenX
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/src/components/TokenIcon/ModeratedNftIcon.stories.tsx
  apps/wallet-mobile/src/components/TokenIcon/ModeratedNftIcon.tsx
  apps/wallet-mobile/src/components/TokenIcon/TokenIcon.stories.tsx
  apps/wallet-mobile/src/components/TokenIcon/TokenIcon.tsx
  apps/wallet-mobile/src/components/TokenIcon/index.ts
  apps/wallet-mobile/src/components/index.ts
  apps/wallet-mobile/src/features/Discover/useCases/ReviewTransaction/ReviewTransaction.tsx
  apps/wallet-mobile/src/features/Exchange/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Portfolio/common/TokenAmountItem/TokenInfoIcon.tsx
  apps/wallet-mobile/src/features/Portfolio/common/hooks/usePortfolioTokenInfos.ts
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/SecondaryTotals.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/SecondaryTotals.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/mapOrders.ts
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AssetList.stories.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AssetList.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AssetListSend.style.ts
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/TxDetails.tsx
  apps/wallet-mobile/src/kernel/helpers/normalisePtId.test.ts
  apps/wallet-mobile/src/kernel/helpers/normalisePtId.ts
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: chore

#3621 fix(wallet-mobile): missing activity price change
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/DashboardTokenItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/TokenBalanceItem.tsx
Labels: fix

#3623 refactor(wallet-mobile): drop legacy fetch token info
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.stories.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AssetList.stories.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/mainnet/constants.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/sanchonet/constants.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/testnet/constants.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
Labels: refactor

#3625 refactor(wallet-mobile): drop legacy network stage 1
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/unsignedTx/unsignedTx.ts
Labels: refactor

#3624 fix(wallet-mobile): scroll back category filters when toggling one
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppTypes/DAppTypes.tsx
Labels: fix

#3628 chore(types): added epoch to protocol params api response
  packages/api/src/cardano/api/protocol-params.mocks.ts
  packages/api/src/cardano/api/protocol-params.test.ts
  packages/api/src/cardano/api/protocol-params.ts
  packages/types/src/api/cardano.ts
Labels: chore

#3629 chore(wallet-mobile): update protocol params
  apps/wallet-mobile/src/features/WalletManager/network-manager/network-manager.ts
Labels: chore

#3630 refactor(wallet-mobile): moved explorers to network manager
  apps/wallet-mobile/src/features/Claim/useCases/ShowSuccessScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/common/MediaDetailsScreen/MediaDetailsScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Overview/Overview.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ShowSubmittedTxScreen/ShowSubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/TxDetails.tsx
  apps/wallet-mobile/src/features/WalletManager/network-manager/network-manager.ts
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  apps/wallet-mobile/translations/messages/src/features/Portfolio/common/MediaDetailsScreen/MediaDetailsScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.json
  packages/types/src/network/manager.ts
Labels: refactor

#3631 refactor(wallet-mobile): token info drop stage 2
  apps/wallet-mobile/src/features/Discover/useCases/ReviewTransaction/ReviewTransaction.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ConfirmVotingTx/ConfirmVotingTx.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/BalanceAfter.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/Fees.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/PrimaryTotal.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/BalanceAfter.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/Fees.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/PrimaryTotal.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/helpers.ts
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/TxDetails.tsx
  apps/wallet-mobile/src/legacy/Dashboard/UserSummary.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  apps/wallet-mobile/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/MultiToken.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/mainnet/constants.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/sanchonet/constants.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/testnet/constants.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/getMinAmounts.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/getMinAmounts.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/processTransactions/processTransactions.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/processTransactions/processTransactions.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/transformers/to-lib-token.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/transformers/to-lib-token.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utils.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/transaction.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/types/tokens.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/format.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/format.ts
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/UserSummary.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.json
  apps/wallet-mobile/translations/messages/src/yoroi-wallets/utils/format.json
Labels: refactor

#3632 feature(wallet-mobile): update how portfolio token list does privacy
  apps/wallet-mobile/src/components/Icon/Change.tsx
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/TokenBalanceItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/TotalTokensValue/TokenValueBalance.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/TotalTokensValue/TokenValuePairedBalance.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/TotalTokensValue/TotalTokensValueContent.tsx
Labels: feature

#3636 fix(tx-list): hide buy banner when tx count is 0
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/ShowBuyBanner.tsx
Labels: fix

#3637 fix(staking): adjust withdraw dialog height
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
Labels: fix

#3638 refactor(wallet-mobile): network api to include get best block
  apps/wallet-mobile/src/features/Staking/Governance/common/helpers.ts
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/TxDetails.tsx
  apps/wallet-mobile/src/features/WalletManager/common/hooks/useBestBlock.tsx
  apps/wallet-mobile/src/features/WalletManager/network-manager/network-manager.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/translations/messages/src/features/Auth/PinInput/PinInput.stories.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  packages/api/package.json
  packages/api/src/cardano/api/best-block.mocks.ts
  packages/api/src/cardano/api/best-block.test.ts
  packages/api/src/cardano/api/best-block.ts
  packages/api/src/cardano/api/cardano-api-maker.mocks.ts
  packages/api/src/cardano/api/cardano-api-maker.ts
  packages/api/src/cardano/api/config.ts
  packages/api/src/cardano/api/protocol-params.mocks.ts
  packages/types/src/chain/cardano.ts
  packages/types/src/index.ts
  packages/types/src/network/manager.ts
Labels: refactor

#3641 fix(wallet-mobile): use svg for minswap and sundaeswap images
  apps/wallet-mobile/src/components/Icon/MinSwap.tsx
  apps/wallet-mobile/src/components/Icon/SundaeSwap.tsx
Labels: fix

#3640 feature(wallet-mobile): design improvements in portfolio
  apps/wallet-mobile/src/assets/img/chart-placeholder.png
  apps/wallet-mobile/src/assets/img/chart-placeholder@2x.png
  apps/wallet-mobile/src/assets/img/chart-placeholder@3x.png
  apps/wallet-mobile/src/components/PairedBalance/PairedBalance.tsx
  apps/wallet-mobile/src/features/Portfolio/common/hooks/useGetPortfolioTokenChart.ts
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/DashboardTokenItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/ChartPlaceholder.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/PortfolioTokenChart.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/PortfolioTokenChartSkeleton.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/TokenPerformance.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenDetailsScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/TokenBalanceItem.tsx
  apps/wallet-mobile/translations/messages/src/components/PairedBalance/PairedBalance.json
Labels: feature

#3644 fix(wallet-mobile): remove tooltip icon
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/TotalTokensValue/TotalTokensValue.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/TotalTokensValue/TotalTokensValueContent.tsx
Labels: fix

#3645 refactor(staking): withdrawal dialog
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.json
Labels: refactor

#3646 refactor(wallet-mobile): portfolio tabs
  apps/wallet-mobile/src/features/Portfolio/PortfolioNavigator.tsx
  apps/wallet-mobile/src/features/Portfolio/common/PortfolioProvider.tsx
  apps/wallet-mobile/src/features/Portfolio/common/PortfolioTokenDetailContext.tsx
  apps/wallet-mobile/src/features/Portfolio/common/types.ts
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/PortfolioDashboardScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/ExportTokenTransactions.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenDetailsScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/PortfolioTokenInfo.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioDAppsTokenList/PortfolioDAppTabs.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioDAppsTokenList/PortfolioDAppsTokenList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioTokenListScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/PortfolioWalletTokenList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/TotalTokensValue/TotalTokensValue.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/TotalTokensValue/TotalTokensValueContent.tsx
Labels: fix, refactor

#3651 fix(wallet-mobile): scrollviews
  apps/wallet-mobile/src/components/ScrollableView/ScrollableView.tsx
  apps/wallet-mobile/src/components/ScrollableView/index.ts
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/MnemonicInput.stories.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/MnemonicInput.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.json
Labels: fix

#3649 feat(wallet-mobile): portfolio balance card touch to list
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/BalanceCard/BalanceCardContent.tsx
Labels: feature

#3647 fix(wallet-mobile): styles fixes
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithHW.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxWithHW.tsx
Labels: fix

#3648 fix(wallet-mobile): fix swap ledger button styles
  apps/wallet-mobile/.storybook/decorators/index.ts
  apps/wallet-mobile/src/components/Button/Button.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/LedgerTransportSwitch.tsx
Labels: fix

#3650 chore(wallet-mobile): prevent prod from calling missing history chart endpoint
  apps/wallet-mobile/src/features/Portfolio/common/hooks/useGetPortfolioTokenChart.ts
  apps/wallet-mobile/src/kernel/features.ts
Labels: chore

#3652 feat(wallet-mobile): dev builds automatically invalidate token image on error
  apps/wallet-mobile/src/features/Portfolio/common/TokenAmountItem/TokenInfoIcon.tsx
Labels: proposal

#3654 fix(wallet-mobile): fix withdraw modal height
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
Labels: fix

#3655 fix(wallet-mobile): actually fix ledger modal colors
  apps/wallet-mobile/src/components/Button/Button.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/LedgerTransportSwitch.tsx
Labels: fix

#3656 fix(uat): change color of inactive state for tab bar icon and remove divider
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Overview/Overview.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: fix

#3657 fix(wallet-mobile): remove duplicate title
  apps/wallet-mobile/src/components/Button/Button.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreHwWallet/SelectHwConnectionModal.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.json
  packages/staking/src/governance/translators/react/hooks.ts
Labels: fix

#3659 fix(wallet-mobile): history tx flicker in android
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/features/Scan/common/CodeScannerButton.stories.tsx
  apps/wallet-mobile/src/features/Scan/common/CodeScannerButton.tsx
  apps/wallet-mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/hooks/useStatusBar.ts
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/legacy/Dashboard/DashboardNavigator.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Transactions/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/DashboardNavigator.json
Labels: fix

#3660 fix(dApp Explorer): fix dialog height while disconnecting dApps
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
Labels: fix

#3661 feature: update catalyst min ada for fund 13
  apps/wallet-mobile/src/features/RegisterCatalyst/common/InsufficientFundsModal.tsx
  apps/wallet-mobile/src/features/WalletManager/common/adapters/cardano/catalyst-config.ts
Labels: feature

#3662 fix(wallet-mobile: nft white flash
  apps/wallet-mobile/src/features/Portfolio/common/MediaPreview/MediaPreview.tsx
Labels: fix
