Repository Emurgo/yoroi, pull requests merged in 2024-06, with the labels that each got.

#3279 feat(dapp-connector): CIP-30 Add api.getCollateral TX reogranisation support
  apps/wallet-mobile/src/features/Discover/common/helpers.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30.ts
  packages/dapp-connector/package.json
  packages/dapp-connector/src/dapp-connector.test.ts
  packages/dapp-connector/src/resolver.ts
  yarn.lock
Labels: feature

#3282 fix(staking): minor UI fixes on the migration modal
  apps/wallet-mobile/src/legacy/Staking/PoolTransition/PoolTransitionModal.tsx
Labels: fix

#3280 feat(dapp-connector): Add CIP-30 signData support
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/jestSetup.ts
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/Discover/common/helpers.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip8/cip8.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip8/cip8.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/common/signatureUtils.ts
  yarn.lock
Labels: feature

#3290 V.4.27.1 pool transition
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/Dashboard/DashboardNavigator.tsx
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxImage.tsx
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxScreen.stories.tsx
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionModal.stories.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionModal.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionNotice.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransition.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransitionModal.tsx
  apps/wallet-mobile/src/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/src/Staking/index.ts
  apps/wallet-mobile/src/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/components/Icon/ArrowDown.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/Receive/common/SingleOrMultipleAddressesModal/SingleOrMultipleAddressesModal.tsx
  apps/wallet-mobile/src/features/Send/common/useSendAddress.tsx
  apps/wallet-mobile/src/features/index.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/assetUtils/assetUtils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/getMinAmounts.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/delegationUtils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utils.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/timeUtils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/timeUtils.ts
  apps/wallet-mobile/translations/messages/src/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/Dashboard/DashboardNavigator.json
  apps/wallet-mobile/translations/messages/src/Staking/FailedTx/FailedTxScreen.json
  apps/wallet-mobile/translations/messages/src/Staking/PoolTransition/usePoolTransition.json
  apps/wallet-mobile/translations/messages/src/Staking/StakingCenter/StakingCenter.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistory.json
  apps/wallet-mobile/translations/messages/src/TxHistory/usePoolTransition.json
  packages/swap/package.json
  yarn.lock
Labels: feature, hotfix

#3292 release(wallet-mobile): v4.27.1-rc.1 pool transition fixes
  apps/wallet-mobile/src/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionModal.tsx
  apps/wallet-mobile/src/features/index.ts
  apps/wallet-mobile/translations/messages/src/Staking/DelegationConfirmation/DelegationConfirmation.json
  apps/wallet-mobile/translations/messages/src/Staking/PoolTransition/usePoolTransition.json
Labels: fix

#3293 feat(wallet-mobile): dApp explorer Unverified dApp modal and minor UI fixes
  apps/wallet-mobile/src/features/Discover/DiscoverNavigator.tsx
  apps/wallet-mobile/src/features/Discover/common/ConfirmConnectionModal.tsx
  apps/wallet-mobile/src/features/Discover/common/UnverifiedDappModal.stories.tsx
  apps/wallet-mobile/src/features/Discover/common/UnverifiedDappModal.tsx
  apps/wallet-mobile/src/features/Discover/common/useStrings.tsx
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/BrowseDappScreen.tsx
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/WebViewItem.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SearchDappInBrowser/SearchDappInBrowserScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Discover/common/useStrings.json
Labels: fix

#3299 (pool-transition) Fix modal reopening
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionProvider.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransitionModal.tsx
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/translations/messages/src/Staking/PoolTransition/usePoolTransition.json
  yarn.lock
Labels: fix

#3300 (pool-transition) Fix small screen modal scroll
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionModal.tsx
Labels: fix

#3302 fix(stake-pool-migration): resize modal as per screen size
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransitionModal.tsx
Labels: fix

#3291 release(wallet-mobile): v4.27.1
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/android/app/build.gradle
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/ios/nightly.plist
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/ios/yoroi/Info.plist
  apps/wallet-mobile/ios/yoroiTests/Info.plist
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/Dashboard/DashboardNavigator.tsx
  apps/wallet-mobile/src/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxImage.tsx
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxScreen.stories.tsx
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionModal.stories.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionModal.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionNotice.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionProvider.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransition.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransitionModal.tsx
  apps/wallet-mobile/src/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/src/Staking/index.ts
  apps/wallet-mobile/src/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/src/components/Icon/ArrowDown.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/Receive/common/SingleOrMultipleAddressesModal/SingleOrMultipleAddressesModal.tsx
  apps/wallet-mobile/src/features/Send/common/useSendAddress.tsx
  apps/wallet-mobile/src/features/index.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/assetUtils/assetUtils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/getMinAmounts.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/delegationUtils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utils.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/timeUtils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/timeUtils.ts
  apps/wallet-mobile/translations/messages/src/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/Dashboard/DashboardNavigator.json
  apps/wallet-mobile/translations/messages/src/Staking/DelegationConfirmation/DelegationConfirmation.json
  apps/wallet-mobile/translations/messages/src/Staking/FailedTx/FailedTxScreen.json
  apps/wallet-mobile/translations/messages/src/Staking/PoolTransition/usePoolTransition.json
  apps/wallet-mobile/translations/messages/src/Staking/StakingCenter/StakingCenter.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistory.json
  apps/wallet-mobile/translations/messages/src/TxHistory/usePoolTransition.json
  packages/swap/package.json
  yarn.lock
Labels: release

#3297 feature(theming): dark mode leftovers
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/features/WalletManager/useCases/SelectWalletFromListScreen/WalletListItem.tsx
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/translations/messages/src/features/Initialization/DarkThemeAnnouncement/DarkThemeAnnouncement.json
Labels: feature

#3301 chore(initialization): choose biometrics screen copy update
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/features/Initialization/ChooseBiometricLogin/ChooseBiometricLoginScreen.stories.tsx
  apps/wallet-mobile/src/features/Initialization/ChooseBiometricLogin/ChooseBiometricLoginScreen.tsx
  apps/wallet-mobile/src/features/Initialization/common/strings.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/useStrings.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/common/useStrings.json
Labels: chore

#3306 chore(wallet-mobile): Updated translations
  apps/wallet-mobile/src/kernel/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/kernel/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/kernel/i18n/locales/de-DE.json
  apps/wallet-mobile/src/kernel/i18n/locales/el-GR.json
  apps/wallet-mobile/src/kernel/i18n/locales/es-ES.json
  apps/wallet-mobile/src/kernel/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/kernel/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/kernel/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/kernel/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/kernel/i18n/locales/id-ID.json
  apps/wallet-mobile/src/kernel/i18n/locales/it-IT.json
  apps/wallet-mobile/src/kernel/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/kernel/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/kernel/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/kernel/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/kernel/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/kernel/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/kernel/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/kernel/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/kernel/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/kernel/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/kernel/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/kernel/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/kernel/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/kernel/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/kernel/i18n/locales/zh-Hant.json
Labels: chore

#3303 fix(pool-transition) QA Pool transition fixes from v4.27.1 to develop
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/src/legacy/Staking/PoolTransition/PoolTransitionModal.tsx
  apps/wallet-mobile/src/legacy/Staking/PoolTransition/PoolTransitionProvider.tsx
  apps/wallet-mobile/src/legacy/Staking/PoolTransition/usePoolTransitionModal.tsx
  apps/wallet-mobile/translations/messages/src/Staking/DelegationConfirmation/DelegationConfirmation.json
  apps/wallet-mobile/translations/messages/src/Staking/PoolTransition/usePoolTransition.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.json
  packages/swap/package.json
  yarn.lock
Labels: fix

#3305 feature(portfolio): images placeholder
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/features/Dev/DeveloperScreen.tsx
  apps/wallet-mobile/src/features/Dev/Playground.tsx
  apps/wallet-mobile/src/features/Portfolio/common/MediaPreview/MediaPreview.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
Labels: feature

#3298 fix(setup-wallet): stepper
  apps/wallet-mobile/src/features/SetupWallet/common/StepperProgress/StepperProgress.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/Number4.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
Labels: fix

#3307 fix(wallet-mobile): Remove misplaced directory from merging prod into dev
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxImage.tsx
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxScreen.stories.tsx
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionModal.stories.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionModal.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionNotice.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionProvider.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransition.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransitionModal.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Initialization/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/common/useStrings.json
  yarn.lock
Labels: fix

#3308 fix(navigation): Set height to 0 when tab bar is hidden
  apps/wallet-mobile/src/kernel/navigation.tsx
Labels: fix

#3295 feat(theming): dark theme announcement
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/features/Initialization/DarkThemeAnnouncement/DarkThemeAnnouncement.stories.tsx
  apps/wallet-mobile/src/features/Initialization/DarkThemeAnnouncement/DarkThemeAnnouncement.tsx
  apps/wallet-mobile/src/features/Initialization/illustrations/ThemeIlustration.tsx
  apps/wallet-mobile/src/features/Portfolio/common/MediaPreview/MediaPreview.tsx
  apps/wallet-mobile/src/features/WalletManager/useCases/SelectWalletFromListScreen/WalletListItem.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Initialization/DarkThemeAnnouncement/DarkThemeAnnouncement.json
Labels: feature

#3314 fix(pool-transition): Fix modal actions styles
  apps/wallet-mobile/src/legacy/Staking/PoolTransition/PoolTransitionModal.tsx
Labels: fix

#3310 feature(portfolio): metrics
  apps/wallet-mobile/src/features/Portfolio/common/MediaPreview/MediaPreview.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/PortfolioDashboardScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenDetailsScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioDAppsTokenList/PortfolioDAppsTokenList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioTokenListScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/PortfolioWalletTokenList.tsx
  apps/wallet-mobile/src/kernel/metrics/ampli/index.ts
  apps/wallet-mobile/src/kernel/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/kernel/metrics/metricsManager.tsx
  apps/wallet-mobile/src/kernel/metrics/mocks.ts
Labels: feature

#3316 fix(initialization): choose biometrics screen
  apps/wallet-mobile/src/features/Initialization/ChooseBiometricLogin/ChooseBiometricLoginScreen.tsx
  apps/wallet-mobile/src/features/Initialization/illustrations/Biometric.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenDetailsScreen.tsx
Labels: fix

#3318 fix(wallet-mobile): avatar svg requires img size on android
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/components/Icon/WalletAvatar.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/CardAboutPhrase/CardAboutPhrase.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  apps/wallet-mobile/src/legacy/TxHistory/BalanceBanner.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: fix

#3320 fix(wallet-mobile): fixes query-key using object
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: fix

#3321 feature(dapp-connector): metrics
  apps/wallet-mobile/src/components/Tooltip/Tooltip.tsx
  apps/wallet-mobile/src/features/Discover/common/ConfirmConnectionModal.tsx
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/BrowseDappScreen.tsx
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/BrowserSearchToolbar.tsx
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/BrowserTabBar.tsx
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/BrowserToolbar.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SearchDappInBrowser/SearchDappInBrowserScreen.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/SelectDappFromListScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioDAppsTokenList/PortfolioDAppsTokenList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/PortfolioWalletTokenList.tsx
  apps/wallet-mobile/src/features/Send/common/useSendReceiver.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  apps/wallet-mobile/src/hooks/useCopy.ts
  apps/wallet-mobile/src/kernel/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/kernel/metrics/metricsManager.tsx
  apps/wallet-mobile/src/kernel/metrics/mocks.ts
  apps/wallet-mobile/src/legacy/Catalyst/hooks.ts
Labels: feature

#3323 fix: dapp discover ui issues
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/BrowseDappScreen.tsx
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/WebViewItem.tsx
Labels: fix

#3313 feat(dapp-connector): Add CIP-95 support
  apps/wallet-mobile/src/features/Discover/common/helpers.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip95/cip95.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip95/cip95.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utils.ts
  packages/dapp-connector/src/connector.js
  packages/dapp-connector/src/dapp-connector.test.ts
  packages/dapp-connector/src/dapp-connector.ts
  packages/dapp-connector/src/resolver.ts
Labels: feature

#3324 fix(wallet-mobile): Provider suspending
  apps/wallet-mobile/src/yoroi-wallets/cardano/useAdaPrice.tsx
Labels: fix

#3325 fix(wallet-mobile): receive address visual derivation
  apps/wallet-mobile/src/features/Receive/common/useReceiveAddressesStatus.tsx
  apps/wallet-mobile/src/features/Receive/useCases/ListMultipleAddressesScreen.tsx
  apps/wallet-mobile/src/features/WalletManager/network-manager/helpers/get-wallet-factory.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/account-manager/account-manager.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/cardano-config.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
Labels: fix

#3326 fix(wallet-mobile): Change Sancho network backend endpoint
  apps/wallet-mobile/src/features/WalletManager/network-manager/network-manager.ts
Labels: fix

#3327 fix(wallet-mobile): balances - protocolparams
  apps/wallet-mobile/src/features/WalletManager/network-manager/network-manager.ts
  apps/wallet-mobile/src/features/WalletManager/network-manager/useProtocolParams.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  packages/api/src/cardano/api/protocol-params.mocks.ts
  packages/api/src/cardano/api/protocol-params.ts
  packages/types/src/api/cardano.ts
  packages/types/src/index.ts
  packages/types/src/network/manager.ts
Labels: fix

#3330 fix(common): navigation transition background
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/features/Discover/DiscoverNavigator.tsx
  apps/wallet-mobile/src/features/Initialization/AgreementChangedNavigator.tsx
  apps/wallet-mobile/src/features/Initialization/InitializationNavigator.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/Search/SearchContext.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/SetupWallet/SetupWalletNavigator.tsx
  apps/wallet-mobile/src/features/Staking/Governance/GovernanceNavigator.tsx
  apps/wallet-mobile/src/features/ToggleAnalyticsSettings/ToggleAnalyticsSettingsNavigator.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/legacy/Catalyst/VotingRegistration.tsx
  apps/wallet-mobile/src/legacy/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/SetupWalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/ToggleAnalyticsSettings/ToggleAnalyticsSettingsNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/TxHistory/TxHistoryNavigator.json
Labels: fix

#3332 fix(common): add navigation transition animation
  apps/wallet-mobile/src/kernel/navigation.tsx
Labels: fix

#3334 fix(swap): increase test timeout
  packages/swap/jest.setup.js
Labels: fix

#3335 feature(identicon): added jazzicon support
  apps/wallet-mobile/src/features/SetupWallet/common/CardAboutPhrase/CardAboutPhrase.tsx
  apps/wallet-mobile/src/features/SetupWallet/legacy/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  apps/wallet-mobile/src/features/WalletManager/wallet-manager.ts
  apps/wallet-mobile/src/kernel/storage/migrations/4_28_0.ts
  packages/identicon/README.md
  packages/identicon/package.json
  packages/identicon/src/adapters/blockies/blockies.test.ts
  packages/identicon/src/adapters/blockies/blockies.ts
  packages/identicon/src/adapters/blockies/color-saturation.test.ts
  packages/identicon/src/adapters/blockies/color-saturation.ts
  packages/identicon/src/adapters/blockies/color-scheme.ts
  packages/identicon/src/adapters/jazzicon/color-scheme.ts
  packages/identicon/src/adapters/jazzicon/jazzicon.test.ts
  packages/identicon/src/adapters/jazzicon/jazzicon.ts
  packages/identicon/src/index.ts
  packages/identicon/tsconfig.json
  yarn.lock
Labels: feature

#3340 fix(common): android bottom spacing
  apps/wallet-mobile/src/features/Initialization/DarkThemeAnnouncement/DarkThemeAnnouncement.tsx
  apps/wallet-mobile/src/features/WalletManager/useCases/SelectWalletFromListScreen/SelectWalletFromListScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Initialization/DarkThemeAnnouncement/DarkThemeAnnouncement.json
Labels: fix

#3342 fix(receive): multiple address modal button background color
  apps/wallet-mobile/src/features/Receive/common/SingleOrMultipleAddressesModal/SingleOrMultipleAddressesModal.tsx
  apps/wallet-mobile/translations/messages/src/features/Initialization/DarkThemeAnnouncement/DarkThemeAnnouncement.json
Labels: fix

#3345 fix(common): failed tx screen dark theme
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/FailedTx/FailedTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/FailedTx/FailedTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/legacy/Staking/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Staking/FailedTx/FailedTxScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/PoolTransition/usePoolTransition.json
Labels: fix

#3344 feat(dapp-connector): Add HW wallet support for CIP-30
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/Discover/DiscoverNavigator.tsx
  apps/wallet-mobile/src/features/Discover/common/ConfirmHWConnectionModal.tsx
  apps/wallet-mobile/src/features/Discover/common/HWNotSupportedModal.tsx
  apps/wallet-mobile/src/features/Discover/common/helpers.ts
  apps/wallet-mobile/src/features/Discover/common/ledger.ts
  apps/wallet-mobile/src/features/Discover/common/useStrings.tsx
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.ts
  apps/wallet-mobile/src/kernel/i18n/global-messages.ts
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30-ledger.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/common/signatureUtils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utils.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/translations/messages/src/features/Discover/common/useStrings.json
  apps/wallet-mobile/translations/messages/src/kernel/i18n/global-messages.json
  yarn.lock
Labels: feature

#3346 feature(staking): Using Catalyst API
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/legacy/Catalyst/CatalystNavigator.stories.tsx
  apps/wallet-mobile/src/legacy/Catalyst/CatalystNavigator.tsx
  apps/wallet-mobile/src/legacy/Catalyst/DownloadCatalyst.tsx
  apps/wallet-mobile/src/legacy/Catalyst/VotingBanner.tsx
  apps/wallet-mobile/src/legacy/Catalyst/components.tsx
  apps/wallet-mobile/src/legacy/Catalyst/index.ts
  apps/wallet-mobile/src/legacy/Catalyst/useCatalystCurrentFund.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/Catalyst/DownloadCatalyst.json
  apps/wallet-mobile/translations/messages/src/legacy/Catalyst/VotingBanner.json
  packages/staking/package.json
  packages/staking/src/catalyst/adapters/api.test.ts
  packages/staking/src/catalyst/adapters/api.ts
  packages/staking/src/catalyst/adapters/fund-info.mocks.ts
  packages/staking/src/catalyst/api-maker.test.ts
  packages/staking/src/catalyst/api-maker.ts
  packages/staking/src/catalyst/config.ts
  packages/staking/src/catalyst/fund-info.mocks.ts
  packages/staking/src/catalyst/index.ts
  packages/staking/src/catalyst/manager.test.ts
  packages/staking/src/catalyst/manager.ts
  packages/staking/src/catalyst/transformers.test.ts
  packages/staking/src/catalyst/transformers.ts
  packages/staking/src/catalyst/translators/context.test.tsx
  packages/staking/src/catalyst/translators/context.tsx
  packages/staking/src/catalyst/validators.test.ts
  packages/staking/src/catalyst/validators.ts
  packages/staking/src/fixtures/ErrorBoundary.tsx
  packages/staking/src/fixtures/SuspenseBoundary.tsx
  packages/staking/src/fixtures/manager-wrapper.tsx
  packages/staking/src/fixtures/query-client.ts
  packages/staking/src/index.ts
  packages/staking/src/types.ts
Labels: feature
