Repository Emurgo/yoroi, pull requests merged in 2024-08, with the labels that each got.

#3474 fix(swap): card background color
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
Labels: fix

#3476 chore(wallet-mobile) tx-details title
  apps/wallet-mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/TxDetails.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Transactions/TxHistoryNavigator.json
Labels: chore

#3470 release(wallet-mobile): v4.28.0
  apps/wallet-mobile/android/app/build.gradle
  apps/wallet-mobile/ios/nightly.plist
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/ios/yoroi/Info.plist
  apps/wallet-mobile/ios/yoroiTests/Info.plist
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/HW/LedgerConnect/LedgerConnect.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/hw/hw.test.ts
  apps/wallet-mobile/translations/messages/src/HW/LedgerConnect/LedgerConnect.json
  packages/swap/package.json
  packages/types/package.json
  yarn.lock
Labels: release

#3477 fix(swap): tx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/CompletedOrders.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
Labels: fix

#3480 chore(wallet-mobile) drop husky
  .husky/.gitignore
  .husky/pre-commit
Labels: chore

#3479 chore(wallet-mobile) enable dapp debugger in dev
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/WebViewItem.tsx
Labels: chore

#3481 fix(wallet-mobile): expo-img resizeMode is deprecated
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Overview/Overview.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/PortfolioTokenInfo.tsx
Labels: fix

#3482 feature(network-selection): left overs
  apps/wallet-mobile/src/features/Exchange/common/ProviderItem/ProviderItem.tsx
  apps/wallet-mobile/src/features/Exchange/common/useStrings.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeButton/CreateExchangeButton.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/EditAmount/EditAmount.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/ShowDisclaimer/ShowDisclaimer.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/ShowPreprodNotice/ShowPreprodNotice.tsx
  apps/wallet-mobile/src/features/Settings/ChangeNetwork/NetworkTag.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Exchange/common/useStrings.json
Labels: feature

#3484 fix(staking): deregistration confirm tx screen updates
  apps/wallet-mobile/src/components/TwoActionView/TwoActionView.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithPassword.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.json
Labels: fix

#3488 chore(wallet-mobile): network-manager obj destruction
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
Labels: chore

#3486 fix(settings): remove wallet checkbox text
  apps/wallet-mobile/src/components/Checkbox/Checkbox.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/DisplayPin/DisplayPin.tsx
  apps/wallet-mobile/src/features/Settings/RemoveWallet/RemoveWalletScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/RemoveWallet/RemoveWalletScreen.json
Labels: fix

#3490 fix(dapp-connector): Improve event handling
  packages/dapp-connector/src/connector.js
  packages/dapp-connector/src/dapp-connector.test.ts
  packages/dapp-connector/src/resolver.ts
Labels: fix

#3489 alternative-fix(network-selection): Max width wrap
  apps/wallet-mobile/src/features/Settings/ChangeNetwork/NetworkTag.tsx
  apps/wallet-mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/wallet-mobile/translations/messages/src/features/Transactions/TxHistoryNavigator.json
Labels: fix

#3491 chore(wallet-mobile): token activity updates
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/common/package.json
  packages/dapp-connector/package.json
  packages/exchange/package.json
  packages/explorers/package.json
  packages/links/package.json
  packages/portfolio/package.json
  packages/portfolio/src/adapters/dullahan-api/api-maker.mocks.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.test.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.ts
  packages/portfolio/src/adapters/dullahan-api/token-activity.mocks.ts
  packages/portfolio/src/adapters/dullahan-api/transformers.test.ts
  packages/portfolio/src/adapters/dullahan-api/transformers.ts
  packages/portfolio/src/adapters/dullahan-api/types.ts
  packages/portfolio/src/adapters/token-activity.mocks.ts
  packages/portfolio/src/balance-manager.test.ts
  packages/resolver/package.json
  packages/setup-wallet/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/transfer/package.json
  packages/types/package.json
  packages/types/src/index.ts
  packages/types/src/portfolio/activity.ts
  packages/types/src/portfolio/api.ts
Labels: chore

#3492 fix(dapp-connector): Resolve race condition when removing multiple origins
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
  packages/dapp-connector/src/dapp-connector.test.ts
  packages/dapp-connector/src/dapp-connector.ts
  packages/dapp-connector/src/manager.mocks.ts
Labels: fix

#3493 fix(wallet-mobile): amount-input selected text theme
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
Labels: fix

#3494 fix(wallet-mobile): Fix collateral reorg TX
  apps/wallet-mobile/src/features/Discover/common/helpers.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.ts
Labels: fix

#3496 fix(wallet-mobile): Show asset names on TX review screen
  apps/wallet-mobile/src/features/Discover/useCases/ReviewTransaction/ReviewTransaction.tsx
Labels: fix

#3500 fix(staking): withdraw rewards styling
  apps/wallet-mobile/src/components/TwoActionView/TwoActionView.tsx
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithPassword.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.json
Labels: fix

#3502 fix(portfolio): media gallery update
  apps/wallet-mobile/src/features/Portfolio/common/MediaGallery/MediaGallery.tsx
Labels: fix

#3498 fix(wallet-mobile): add network tag in catalyst funnel
  apps/wallet-mobile/src/features/RegisterCatalyst/CatalystNavigator.tsx
Labels: fix

#3503 chore(wallet-mobile): drop legacy
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/common.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/mainnet/constants.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/sanchonet/constants.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/testnet/constants.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/networks.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utils.ts
Labels: chore

#3504 fix(wallet-mobile): Check for staking key in required signers
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/Discover/useCases/ReviewTransaction/ReviewTransaction.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/common/signatureUtils.ts
  packages/swap/package.json
  packages/types/package.json
  yarn.lock
Labels: fix

#3499 feature(wallet-mobile): Adds token activity to show non ada prices
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/src/components/PairedBalance/PairedBalance.tsx
  apps/wallet-mobile/src/features/Portfolio/common/PortfolioProvider.tsx
  apps/wallet-mobile/src/features/Portfolio/common/PortfolioTokenActivityProvider.tsx
  apps/wallet-mobile/src/features/Portfolio/common/helpers/aggregatePrimaryAmount.ts
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/BalanceCard/BalanceCard.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/DashboardTokenItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioDAppsTokenList/DAppTokenItem/DAppTokenItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioDAppsTokenList/LiquidityPoolModal.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioDAppsTokenList/OpenOrderModal.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/PortfolioWalletTokenList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/TokenBalanceItem.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxList/TxListItem.tsx
  apps/wallet-mobile/src/features/WalletManager/useCases/SelectWalletFromListScreen/AggregatedBalance.tsx
  apps/wallet-mobile/src/kernel/features.ts
  apps/wallet-mobile/translations/messages/src/components/PairedBalance/PairedBalance.json
Labels: feature

#3505 fix(wallet-home): copy change for TADA banner
  apps/wallet-mobile/src/features/Exchange/common/useStrings.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Exchange/common/useStrings.json
Labels: fix

#3507 fix(exchange): preprod buy fee text
  apps/wallet-mobile/src/features/Exchange/common/ProviderItem/ProviderItem.stories.tsx
  apps/wallet-mobile/src/features/Exchange/common/ProviderItem/ProviderItem.tsx
  apps/wallet-mobile/src/features/Exchange/common/useStrings.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/ShowDisclaimer/ShowDisclaimer.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/SelectProviderFromListScreen/SelectProviderFromListScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Exchange/common/useStrings.json
Labels: fix

#3511 fix(wallet-mobile): sa using only external 0
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
Labels: fix

#3510 fix(setup-wallet): create wallet styling
  apps/wallet-mobile/src/features/Exchange/common/ProviderItem/ProviderItem.stories.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/RecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/VerifyRecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  packages/theme/src/base-palettes/dark-palette.ts
Labels: fix

#3515 fix(setup-wallet): hw connect error
  apps/wallet-mobile/src/legacy/HW/LedgerConnect/LedgerConnect.tsx
Labels: fix

#3518 fix(receive): double multiple-single modal warning
  apps/wallet-mobile/src/features/Receive/common/SingleOrMultipleAddressesModal/SingleOrMultipleAddressesModal.tsx
Labels: fix

#3513 fix(staking): withdraw rewards dialog
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithHW.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithOS.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithPassword.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.json
  apps/wallet-mobile/translations/messages/src/legacy/HW/LedgerConnect/LedgerConnect.json
Labels: fix

#3519 fix(wallet-mobile): Restore funnel styles
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/TextInput/TextInput.tsx
Labels: fix

#3520 chore: added OHLC
  packages/portfolio/src/adapters/dullahan-api/token-activity.mocks.ts
  packages/portfolio/src/adapters/dullahan-api/transformers.ts
  packages/portfolio/src/adapters/dullahan-api/types.ts
  packages/portfolio/src/adapters/token-activity.mocks.ts
  packages/types/src/portfolio/activity.ts
Labels: fix

#3521 fix(wallet-mobile): Remove settings in tx history
  apps/wallet-mobile/src/features/Portfolio/common/PortfolioTokenActivityProvider.tsx
  apps/wallet-mobile/src/features/Settings/ChangeNetwork/NetworkTag.tsx
  apps/wallet-mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/wallet-mobile/translations/messages/src/features/Transactions/TxHistoryNavigator.json
Labels: fix

#3523 fix(network-selection): hide explorer button on sanchonet
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/TxDetails.tsx
Labels: fix

#3524 fix(wallet-mobile): Network tag size edge case
  apps/wallet-mobile/src/features/Settings/ChangeNetwork/NetworkTag.tsx
Labels: fix

#3525 fix(discovery): single-address tag styling
  apps/wallet-mobile/src/features/Discover/common/LabelSingleAddress.tsx
  packages/theme/src/themed-palettes/black.ts
  packages/theme/src/themed-palettes/light.ts
Labels: fix

#3527 fix(wallet-mobile): Portfolio design fixes
  apps/wallet-mobile/src/components/PairedBalance/PairedBalance.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/BalanceCard/Rate.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/DashboardTokenItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/PortfolioWalletTokenList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/TokenBalanceItem.tsx
  apps/wallet-mobile/translations/messages/src/components/PairedBalance/PairedBalance.json
Labels: fix

#3526 fix(tx-details): padding
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/TxDetails.tsx
Labels: fix

#3528 fix(dApp explorer): display SA banner on modal for reconnecting dapps
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
Labels: fix

#3532 fix(wallet-mobile): Fix primary token id in delegation confirmation
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.tsx
  apps/wallet-mobile/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/TransferSummary/TransferSummary.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.json
Labels: fix

#3533 fix(wallet-mobile): Normalise swap metadata primary token id
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/CompletedOrders.tsx
Labels: fix

#3530 chore(wallet-mobile): from portfolio to swap with data
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/features/Portfolio/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/Actions.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenAction.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenDetailsScreen.tsx
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
  apps/wallet-mobile/src/features/Swap/common/SwapFormProvider.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/Actions/AmountActions/AmountActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/Actions/AmountActions/ResetQuantities.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/Actions/AmountActions/ResetQuantities.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/StartSwapOrderScreen.tsx
  apps/wallet-mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Transactions/TxHistoryNavigator.json
  packages/portfolio/src/adapters/token-discovery.mocks.ts
  packages/portfolio/src/adapters/token-info.mocks.ts
  packages/portfolio/src/constants.ts
  packages/portfolio/src/helpers/create-primary-token-info.test.ts
  packages/portfolio/src/helpers/create-primary-token-info.ts
  packages/portfolio/src/helpers/is-primary-token.test.ts
  packages/portfolio/src/helpers/is-primary-token.ts
  packages/portfolio/src/translators/reactjs/usePortfolioTokenInfo.test.tsx
  packages/portfolio/src/translators/reactjs/usePortfolioTokenInfo.tsx
  packages/portfolio/src/validators/token-info.ts
Labels: chore

#3538 fix(catalyst): fix padding in bottomsheets for android
  apps/wallet-mobile/src/features/RegisterCatalyst/common/InsufficientFundsModal.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/DownloadCatalyst/DownloadCatalyst.tsx
Labels: fix

#3535 fix(wallet-mobile): Disable react-query experimental persistence
  apps/wallet-mobile/src/kernel/query-client.ts
Labels: fix

#3534 fix(receive): qr content
  apps/wallet-mobile/src/components/ShareQRCodeCard/ShareQRCodeCard.stories.tsx
  apps/wallet-mobile/src/components/ShareQRCodeCard/ShareQRCodeCard.tsx
  apps/wallet-mobile/src/features/Receive/common/AddressDetailCard/AddressDetailCard.tsx
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ShowQrCode/ShowQrCode.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: fix

#3540 chore(portfolio): support new API response for multi token when 1 fail
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/common/package.json
  packages/common/src/cache/cache-manage-multi-request.test.ts
  packages/common/src/cache/cache-manage-multi-request.ts
  packages/dapp-connector/package.json
  packages/exchange/package.json
  packages/explorers/package.json
  packages/links/package.json
  packages/portfolio/package.json
  packages/portfolio/src/adapters/dullahan-api/transformers.test.ts
  packages/portfolio/src/adapters/dullahan-api/transformers.ts
  packages/portfolio/src/validators/response-record-with-cache-schema-maker.test.ts
  packages/portfolio/src/validators/response-record-with-cache-schema-maker.ts
  packages/resolver/package.json
  packages/setup-wallet/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/transfer/package.json
  packages/types/package.json
  packages/types/src/api/cache.ts
Labels: chore

#3541 chore(wallet-mobile): drop flag for theme activation
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
Labels: chore

#3543 fix(wallet-mobile): drop sancho from list when not dev
  apps/wallet-mobile/src/features/Settings/ChangeNetwork/NetworkPickerList.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
Labels: fix

#3544 fix(wallet-mobile): drop top edge from sav on staking legacy
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/legacy/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
Labels: fix

#3545 fix(wallet-mobile): enable wallet easy tx confirmation with os theming
  apps/wallet-mobile/src/components/LoadingOverlay/LoadingOverlay.tsx
  apps/wallet-mobile/src/components/ScreenBackground.tsx
  apps/wallet-mobile/src/features/Auth/OsAuthScreen/OsAuthScreen.tsx
  apps/wallet-mobile/src/features/Settings/EasyConfirmation/EnableEasyConfirmationScreen.tsx
  apps/wallet-mobile/src/features/Settings/EnableLoginWithOs/EnableLoginWithOsScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Auth/OsAuthScreen/OsAuthScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/EasyConfirmation/EnableEasyConfirmationScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/EnableLoginWithOs/EnableLoginWithOsScreen.json
Labels: fix

#3546 fix(wallet-mobile): display warning when not registered only
  apps/wallet-mobile/src/features/RegisterCatalyst/CatalystNavigator.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/DownloadCatalystAppScreen/DownloadCatalystAppScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/EasyConfirmation/EnableEasyConfirmationScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
Labels: fix

#3547 fix(wallet-mobile): Add theme to governance
  apps/wallet-mobile/src/features/Staking/Governance/common/Action/Action.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ChangeVote/ChangeVoteScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/EnterDrepIdModal/EnterDrepIdModal.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/SuccessTx/SuccessTxScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/WithdrawWarningModal/WithdrawWarningModal.tsx
Labels: fix

#3549 fix(wallet-mobile): Use theme in claim modal
  apps/wallet-mobile/src/features/Claim/useCases/AskConfirmation.tsx
Labels: fix

#3551 fix(wallet-mobile): cycle networks + select consuming from constant
  apps/wallet-mobile/src/features/Settings/ChangeNetwork/NetworkPickerList.tsx
  apps/wallet-mobile/src/features/Settings/ChangeNetwork/NetworkTag.tsx
  apps/wallet-mobile/src/features/WalletManager/common/constants.ts
Labels: fix

#3553 chore(wallet-mobile): impl explorers v1.0.1
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/Portfolio/common/helpers/build-token-managers.ts
  apps/wallet-mobile/src/features/WalletManager/network-manager/helpers/date-to-epoch-info.test.ts
  apps/wallet-mobile/src/features/WalletManager/network-manager/helpers/get-wallet-factory.ts
  apps/wallet-mobile/src/features/WalletManager/network-manager/network-manager.ts
  apps/wallet-mobile/src/kernel/config.ts
  packages/api/src/cardano/api/config.ts
  packages/dapp-connector/src/adapters/api.test.ts
  packages/dapp-connector/src/adapters/api.ts
  packages/explorers/README.md
  packages/explorers/package.json
  packages/explorers/src/explorer-manager.test.ts
  packages/explorers/src/explorer-manager.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.ts
  packages/staking/src/governance/config.ts
  packages/types/src/chain/network.ts
  packages/types/src/explorers/manager.ts
Labels: refactor

#3556 chore(yoroi): update readme
  README.md
Labels: chore

#3554 feature(governance): no funds warning
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/features/Staking/Governance/GovernanceNavigator.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/navigation.ts
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/illustrations/NoFunds.tsx
  apps/wallet-mobile/src/features/Staking/Governance/illustrations/index.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/NoFunds/NoFundsScreen.stories.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/NoFunds/NoFundsScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/NoFunds/index.ts
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/components/PairedBalance/PairedBalance.json
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
Labels: feature

#3548 feature(governance): hw support
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/components/ConfirmTxWithHwModal/ConfirmTxWithHwModal.tsx
  apps/wallet-mobile/src/components/ModalError/ModalError.tsx
  apps/wallet-mobile/src/features/Staking/Governance/GovernanceNavigator.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/navigation.ts
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/illustrations/BrokenImage.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/NotSupportedCardanoAppVersion/NotSupportedCardanoAppVersion.stories.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/NotSupportedCardanoAppVersion/NotSupportedCardanoAppVersion.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/NotSupportedCardanoAppVersion/index.ts
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/hw/hw.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/translations/messages/src/components/PairedBalance/PairedBalance.json
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
  packages/swap/package.json
  packages/types/package.json
  yarn.lock
Labels: feature

#3550 feature(portfolio): update token activity api response type
  apps/wallet-mobile/src/components/PairedBalance/PairedBalance.tsx
  apps/wallet-mobile/src/features/Portfolio/common/PortfolioTokenActivityProvider.tsx
  apps/wallet-mobile/src/features/Portfolio/common/helpers/aggregatePrimaryAmount.ts
  apps/wallet-mobile/src/features/Portfolio/common/useGetPortfolioTokenChart.ts
  apps/wallet-mobile/src/features/Portfolio/common/useZeroBalance.ts
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/BalanceCard/BalanceCard.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/BalanceCard/BalanceCardContent.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/DashboardTokenItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/PortfolioTokenChart.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/PortfolioWalletTokenList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/TokenBalanceItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/TotalTokensValue/TotalTokensValueContent.tsx
  apps/wallet-mobile/src/features/Settings/Currency/CurrencyContext.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxList/TxListItem.tsx
  apps/wallet-mobile/src/features/WalletManager/useCases/SelectWalletFromListScreen/AggregatedBalance.tsx
  apps/wallet-mobile/src/kernel/constants.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/useAdaPrice.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/usePrimaryTokenActivity.tsx
  apps/wallet-mobile/translations/messages/src/components/PairedBalance/PairedBalance.json
  packages/portfolio/src/adapters/dullahan-api/api-maker.mocks.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.test.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.ts
  packages/portfolio/src/adapters/dullahan-api/token-activity.mocks.ts
  packages/portfolio/src/adapters/dullahan-api/transformers.test.ts
  packages/portfolio/src/adapters/dullahan-api/transformers.ts
  packages/portfolio/src/adapters/dullahan-api/types.ts
  packages/portfolio/src/adapters/token-activity.mocks.ts
  packages/portfolio/src/balance-manager.test.ts
  packages/portfolio/src/helpers/is-primary-token.test.ts
  packages/portfolio/src/helpers/is-primary-token.ts
  packages/types/src/index.ts
  packages/types/src/portfolio/activity.ts
  packages/types/src/portfolio/api.ts
Labels: feature

#3559 fix(governance): missing info link
  apps/wallet-mobile/src/components/ConfirmTxWithHwModal/ConfirmTxWithHwModal.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/NoFunds/NoFundsScreen.tsx
Labels: fix

#3560 chore: bumped packages
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/common/package.json
  packages/dapp-connector/package.json
  packages/exchange/package.json
  packages/explorers/package.json
  packages/identicon/package.json
  packages/links/package.json
  packages/portfolio/README.md
  packages/portfolio/package.json
  packages/resolver/package.json
  packages/setup-wallet/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/theme/package.json
  packages/transfer/package.json
  packages/types/package.json
Labels: chore

#3561 fix(send): edit send amount empty state
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
Labels: fix

#3564 fix(common): styling minors
  apps/wallet-mobile/src/components/Button/Button.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/LoadingLink/ErrorScreen.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/LoadingLink/LoadingScreen.tsx
  packages/theme/src/themed-palettes/black.ts
  packages/theme/src/themed-palettes/light.ts
  packages/theme/src/types.ts
Labels: fix

#3570 feature(discover): intl filter options
  apps/wallet-mobile/src/features/Discover/common/LabelCategoryDApp.tsx
  apps/wallet-mobile/src/features/Discover/common/useStrings.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppTypes/DAppTypes.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/SelectDappFromListScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Discover/common/useStrings.json
Labels: feature

#3571 refactor(wallet-mobile): using logger types from pkg
  apps/wallet-mobile/src/features/Settings/SystemLogScreen/SystemLogScreen.tsx
  apps/wallet-mobile/src/kernel/config.ts
  apps/wallet-mobile/src/kernel/logger/adapters/dev-transporter.ts
  apps/wallet-mobile/src/kernel/logger/adapters/sentry-transporter.ts
  apps/wallet-mobile/src/kernel/logger/helpers/to-logger-metadata.ts
  apps/wallet-mobile/src/kernel/logger/logger.ts
  apps/wallet-mobile/src/kernel/logger/types.ts
  packages/types/src/app/logger.ts
  packages/types/src/index.ts
Labels: chore

#3572 fix(wallet-mobile): qr theming
  apps/wallet-mobile/src/components/ShareQRCodeCard/CaptureShareQRCodeCard/CaptureShareQRCodeCard.tsx
  apps/wallet-mobile/src/components/ShareQRCodeCard/ShareQRCodeCard.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AddressModal/AddressModal.tsx
Labels: fix

#3573 chore(resolver): docs updated
  packages/resolver/README.md
  packages/resolver/package.json
Labels: chore

#3574 fix(staking): dashboard restyling
  apps/wallet-mobile/src/components/Icon/TotalAda.tsx
  apps/wallet-mobile/src/components/Icon/TotalDelegated.tsx
  apps/wallet-mobile/src/components/Icon/TotalReward.tsx
  apps/wallet-mobile/src/components/ProgressCircle.tsx
  apps/wallet-mobile/src/components/TitledCard.tsx
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/legacy/Dashboard/EpochProgress.tsx
  apps/wallet-mobile/src/legacy/Dashboard/StakePoolInfo.tsx
  apps/wallet-mobile/src/legacy/Dashboard/UserSummary.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/EpochProgress.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/StakePoolInfo.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/UserSummary.json
Labels: fix

#3577 fix(theme): buttons styling
  apps/wallet-mobile/src/components/Button/Button.tsx
Labels: fix

#3576 feat(wallet-mobile): Enable governance on preprod network
  apps/wallet-mobile/src/features/Staking/Governance/common/mocks.ts
  apps/wallet-mobile/src/kernel/config.ts
  packages/staking/src/governance/manager.ts
  packages/staking/src/governance/mocks.ts
  packages/staking/src/governance/translators/react/hooks.ts
Labels: feature

#3578 fix(theme): tabs icons active/inactive style
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/TabDiscover.tsx
  apps/wallet-mobile/src/components/Icon/TabDiscoverActive.tsx
  apps/wallet-mobile/src/components/Icon/TabMenu.tsx
  apps/wallet-mobile/src/components/Icon/TabMenuActive.tsx
  apps/wallet-mobile/src/components/Icon/TabPortfolioActive.tsx
  apps/wallet-mobile/src/components/Icon/TabWallet.tsx
  apps/wallet-mobile/src/components/Icon/TabWalletActive.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: fix

#3579 fix(wallet-mobile): white flickering nav transitions
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
Labels: fix

#3580 refactor(wallet-mobile): drop version + readonly on static prop
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
Labels: refactor

#3581 refactor(catalyst): split the generation of voting tx and voting key
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ConfirmPin/ConfirmPin.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ConfirmVotingTx/ConfirmVotingTx.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  packages/staking/src/catalyst/translators/context.tsx
  packages/staking/src/catalyst/translators/state.test.tsx
  packages/staking/src/catalyst/translators/state.tsx
Labels: refactor
