Repository Emurgo/yoroi, pull requests merged in 2024-11, with the labels that each got.

#3722 fix(dapp-connector): Prompt user only if window is focused and fix error handling
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/WebViewItem.tsx
  packages/dapp-connector/src/connector.js
Labels: fix

#3725 fix(wallet-mobile): Navigate to portfolio after clicking back on NFT detail
  apps/wallet-mobile/src/features/Portfolio/common/hooks/useNavigateTo.tsx
Labels: fix

#3723 feature(wallet-mobile): new tx review stake pool details
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/ReviewTx/common/ExplorerInfoLinks.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/PoolDetails.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/TokenDetails.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useStrings.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/operations.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/translations/messages/src/features/ReviewTx/common/hooks/useStrings.json
  yarn.lock
Labels: feature

#3724 feature(wallet-mobile): new tx review wallet balance dialog
  apps/wallet-mobile/src/features/ReviewTx/common/WalletBalance.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useStrings.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/Overview/OverviewTab.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/ReviewTx/common/hooks/useStrings.json
Labels: feature

#3728 refactor(wallet-metadata): new tx review metadata
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedMetadata.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmWithSpendingPassword/ConfirmWithSpendingPassword.tsx
Labels: refactor

#3729 refactor(wallet-mobile): new tx review state
  apps/wallet-mobile/src/features/ReviewTx/common/ReviewTxProvider.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedMetadata.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/types.ts
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/Overview/OverviewTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ReviewSwap/ReviewSwap.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.json
Labels: refactor

#3730 fix(wallet-mobile): new tx review improvements
  apps/wallet-mobile/src/features/ReviewTx/common/Accordion.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/operations.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/types.ts
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/Overview/OverviewTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/UTxOs/UTxOsTab.tsx
Labels: fix

#3733 feature(wallet-mobile): new tx review multi receivers
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useStrings.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/mocks.ts
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Metadata/MetadataTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Overview/OverviewTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.stories.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/UTxOs/UTxOsTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/ReviewTx/common/hooks/useStrings.json
Labels: feature

#3735 feature(wallet-mobile): new tx review dapps info
  apps/wallet-mobile/src/features/Discover/common/helpers.ts
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useStrings.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Overview/OverviewTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.stories.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/translations/messages/src/features/ReviewTx/common/hooks/useStrings.json
Labels: feature

#3734 feature(wallet-mobile): new tx review mint + reference inputs + infrastructure issue screen
  apps/wallet-mobile/src/features/Discover/common/helpers.ts
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.tsx
  apps/wallet-mobile/src/features/ReviewTx/ReviewTxNavigator.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useStrings.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/mocks.ts
  apps/wallet-mobile/src/features/ReviewTx/common/types.ts
  apps/wallet-mobile/src/features/ReviewTx/illustrations/InfraestructureIssueIcon.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Mint/MintTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Overview/OverviewTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReferenceInputs/ReferenceInputs.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.stories.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ShowInfraestructureIssueScreen/InfraestructureIssueScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/translations/messages/src/features/ReviewTx/common/hooks/useStrings.json
Labels: feature

#3738 fix(wallet-mobile): cbor wasnt cleaned after use
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/ReviewTxProvider.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useTxBody.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/operations.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: fix

#3739 fix(wallet-mobile): default pt to zero
  apps/wallet-mobile/src/yoroi-wallets/cardano/usePrimaryTokenActivity.tsx
Labels: fix

#3745 chore: smart workflow - ignore drafts
  .github/workflows/nightly.yml
  .github/workflows/wallet-mobile-checks.yml
Labels: chore

#3748 fix(wallet-mobile): allow screenshot toggle in android production
  apps/wallet-mobile/src/features/Settings/useCases/changeAppSettings/ApplicationSettingsScreen.tsx
Labels: fix

#3749 fix(wallet-mobile): Fallback number for missing data in fetchPtPrice
  apps/wallet-mobile/src/yoroi-wallets/cardano/usePrimaryTokenActivity.tsx
Labels: fix

#3747 feat(wallet-mobile): new tx review success/failed tx screens
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useOnConfirm.tsx
  apps/wallet-mobile/src/features/Send/common/navigation.ts
  apps/wallet-mobile/src/features/Send/common/strings.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ShowFailedTxScreen/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ShowSubmittedTxScreen/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/GovernanceNavigator.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/helpers.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/navigation.ts
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ShowFailedTxScreen/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ShowSubmittedTxScreen/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/common/navigation.ts
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/ReviewSwap/ReviewSwap.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ShowFailedTxScreen/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ShowSubmittedTxScreen/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/legacy/Dashboard/DashboardNavigator.tsx
  apps/wallet-mobile/src/legacy/Dashboard/ShowFailedTxScreen/FailedTxScreen.tsx
  apps/wallet-mobile/src/legacy/Dashboard/ShowSubmittedTxScreen/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/legacy/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/translations/messages/src/features/Send/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/Transactions/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/DashboardNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/ShowFailedTxScreen/FailedTxScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/ShowSubmittedTxScreen/SubmittedTxScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
Labels: feature
