Repository Emurgo/yoroi, pull requests merged in 2024-04, with the labels that each got.

#3176 fix(wallet-mobile): webview about:srcdoc issue
  apps/wallet-mobile/src/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/translations/messages/src/Staking/StakingCenter/StakingCenter.json
Labels: fix

#3178 chore(wallet-mobile): change tag font to medium
  apps/wallet-mobile/src/features/Receive/common/SmallAddressCard/SmallAddressCard.tsx
Labels: fix

#3177 fix(wallet-mobile): Change single or multiple modal check
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/WalletInit/SaveNanoX/SaveNanoXScreen.tsx
  apps/wallet-mobile/src/WalletInit/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.tsx
  apps/wallet-mobile/src/WalletInit/WalletCredentials/WalletCredentialsScreen.tsx
  apps/wallet-mobile/src/features/Receive/common/SingleOrMultipleAddressesModal/SingleOrMultipleAddressesModal.stories.tsx
  apps/wallet-mobile/src/features/Receive/common/SingleOrMultipleAddressesModal/SingleOrMultipleAddressesModal.tsx
  apps/wallet-mobile/src/features/Receive/common/useMultipleAddressesInfo.tsx
  apps/wallet-mobile/src/features/Receive/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Receive/common/useStrings.tsx
  apps/wallet-mobile/src/features/Receive/useCases/DescribeSelectedAddressScreen.tsx
  apps/wallet-mobile/src/features/Receive/useCases/ListMultipleAddressesScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/migrations/4_26_0.test.ts
  apps/wallet-mobile/src/migrations/4_26_0.ts
  apps/wallet-mobile/src/wallet-manager/useAddressModeManager.tsx
  apps/wallet-mobile/translations/messages/src/WalletInit/SaveNanoX/SaveNanoXScreen.json
  apps/wallet-mobile/translations/messages/src/WalletInit/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.json
  apps/wallet-mobile/translations/messages/src/features/Receive/common/useStrings.json
Labels: fix

#3179 fix(receive): Adjust QR card spacing
  apps/wallet-mobile/src/features/Receive/common/ShareQRCodeCard/ShareQRCodeCard.tsx
Labels: fix

#3181 fix(wallet-mobile): Change link color and align text to center
  apps/wallet-mobile/src/features/Receive/common/SingleOrMultipleAddressesModal/SingleOrMultipleAddressesModal.tsx
Labels: fix

#3183 fix(wallet-mobile): Add copy tool tip on address details
  apps/wallet-mobile/src/components/CopyButton.tsx
  apps/wallet-mobile/src/features/Receive/common/ShareDetailsCard/ShareDetailsCard.tsx
Labels: fix

#3188 fix(setup-wallet): avoid intial flow if the user has wallets
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/yoroi-wallets/auth/auth.ts
  apps/wallet-mobile/src/yoroi-wallets/storage/KeychainStorage.test.ts
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: fix

#3139 feat(dapp-connector): Create dApp connector package
  apps/wallet-mobile/babel.config.js
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/components/Icon/ArrowRight.tsx
  apps/wallet-mobile/src/components/SafeArea.tsx
  apps/wallet-mobile/src/features/Discover/BrowserNavigator.tsx
  apps/wallet-mobile/src/features/Discover/common/BrowserProvider.tsx
  apps/wallet-mobile/src/features/Discover/common/hooks.ts
  apps/wallet-mobile/src/features/Discover/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Discover/common/wallet-config.ts
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/WebViewItem.tsx
  apps/wallet-mobile/src/features/Staking/Governance/GovernanceNavigator.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/index.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ChangeVote/ChangeVoteScreen.stories.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ConfirmTx/ConfirmTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/FailedTx/FailedTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.stories.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/SuccessTx/SuccessTxScreen.stories.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  metro.config.js
  packages/dapp-connector/.dependency-cruiser.js
  packages/dapp-connector/.gitignore
  packages/dapp-connector/.watchmanconfig
  packages/dapp-connector/README.md
  packages/dapp-connector/babel.config.js
  packages/dapp-connector/jest.setup.js
  packages/dapp-connector/package.json
  packages/dapp-connector/src/adapters/async-storage.ts
  packages/dapp-connector/src/connector.js
  packages/dapp-connector/src/dapp-connector.test.ts
  packages/dapp-connector/src/dapp-connector.ts
  packages/dapp-connector/src/index.ts
  packages/dapp-connector/src/mocks.ts
  packages/dapp-connector/src/resolver.ts
  packages/dapp-connector/src/storage.mocks.ts
  packages/dapp-connector/src/translators/reactjs/DappConnectorProvider.test.tsx
  packages/dapp-connector/src/translators/reactjs/DappConnectorProvider.tsx
  packages/dapp-connector/tsconfig.build.json
  packages/dapp-connector/tsconfig.json
  scripts/install-pkgs.sh
  yarn.lock
  yoroi.code-workspace
Labels: feature

#3198 fix(root): fix building order
  package.json
Labels: fix

#3199 fix(wallet-setup): mnemonic input
  apps/wallet-mobile/src/features/SetupWallet/common/MnemonicInput/MnemonicInput.tsx
Labels: fix

#3192 fix(setup-wallet): titles and hw wallet prod
  apps/wallet-mobile/src/features/SetupWallet/SetupWalletNavigator.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/ChooseNetwork/ChooseNetworkScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/ChooseSetupType/ChooseSetupTypeScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/SetupWalletNavigator.json
Labels: fix

#3203 fix(setup wallet): wallet plate hardcode issue, redirects and mnemonic button
  apps/wallet-mobile/src/features/SetupWallet/common/useStrings.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/VerifyRecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/common/useStrings.json
  apps/wallet-mobile/translations/messages/src/yoroi-wallets/auth/auth.json
Labels: fix

#3202 fix(wallet-mobile): Non sticky max address message
  apps/wallet-mobile/src/features/Receive/useCases/ListMultipleAddressesScreen.tsx
Labels: fix

#3193 fix(setup-wallet): dialogs and link
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/RecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/WalletManager/SelectWalletFromList/SelectWalletFromListScreen.tsx
  packages/setup-wallet/src/translators/reactjs/provider/SetupWalletProvider.test.tsx
  packages/setup-wallet/src/translators/reactjs/provider/SetupWalletProvider.tsx
  packages/setup-wallet/src/translators/reactjs/state/state.test.ts
  packages/setup-wallet/src/translators/reactjs/state/state.ts
Labels: fix

#3205 chore(resolver): update unstoppable domains supported list
  apps/wallet-mobile/package.json
  packages/resolver/package.json
  packages/resolver/src/adapters/unstoppable/api.ts
  packages/setup-wallet/package.json
  packages/transfer/package.json
Labels: chore

#3145 feature(swap): Use new completed orders endpoint
  apps/wallet-mobile/package.json
  packages/swap/package.json
  packages/swap/src/adapters/openswap-api/api.mocks.ts
  packages/swap/src/adapters/openswap-api/config.ts
  packages/swap/src/adapters/openswap-api/openswap.mocks.ts
  packages/swap/src/adapters/openswap-api/orders.ts
  packages/swap/src/adapters/openswap-api/types.ts
  packages/swap/src/helpers/transformers.test.ts
  packages/swap/src/helpers/transformers.ts
  packages/types/src/swap/order.ts
Labels: feature

#3184 feature(pool-transition): Adds Pool transition modal and warnings
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/Dashboard/DashboardNavigator.tsx
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxImage.tsx
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxScreen.stories.tsx
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionModal.stories.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionModal.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionNotice.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransition.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransitionModal.tsx
  apps/wallet-mobile/src/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/src/Staking/index.ts
  apps/wallet-mobile/src/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/components/Icon/ArrowDown.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/assetUtils/assetUtils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/getMinAmounts.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/timeUtils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/timeUtils.ts
  apps/wallet-mobile/translations/messages/src/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/Dashboard/DashboardNavigator.json
  apps/wallet-mobile/translations/messages/src/Staking/FailedTx/FailedTxScreen.json
  apps/wallet-mobile/translations/messages/src/Staking/PoolTransition/usePoolTransition.json
  apps/wallet-mobile/translations/messages/src/Staking/StakingCenter/StakingCenter.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistory.json
  apps/wallet-mobile/translations/messages/src/TxHistory/usePoolTransition.json
  packages/swap/package.json
  yarn.lock
Labels: feature

#3207 refactor(wallet-mobile): sync logic
  apps/wallet-mobile/src/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/SelectWalletFromList/SelectWalletFromListScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/SelectWalletFromList/WalletListItem.tsx
  apps/wallet-mobile/src/features/WalletManager/Context/SelectedWalletContext.tsx
  apps/wallet-mobile/src/features/index.ts
  apps/wallet-mobile/src/wallet-manager/types.ts
  apps/wallet-mobile/src/wallet-manager/walletManager.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/promise/index.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/promise/promise.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/promise/promise.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  packages/common/src/queue/queue-task.test.ts
  packages/common/src/queue/queue-task.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.ts
Labels: refactor

#3212 fix(wallet-setup): Mnemonic checksum validation retry and tip
  apps/wallet-mobile/src/features/SetupWallet/common/MnemonicInput/MnemonicInput.tsx
Labels: fix

#3211 fix: UAT and regression v4.27.0
  apps/wallet-mobile/src/Dashboard/EpochProgress.tsx
  apps/wallet-mobile/src/features/Settings/ChangeWalletName/ChangeWalletName.tsx
  apps/wallet-mobile/src/features/Settings/RemoveWallet/RemoveWalletScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/ChangeWalletName/ChangeWalletName.json
  apps/wallet-mobile/translations/messages/src/features/Settings/RemoveWallet/RemoveWalletScreen.json
Labels: fix

#3214 fix(wallet-setup): disable keyboard for bottom-sheet
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
Labels: fix

#3213 fix(wallet-mobile): NetworkError instance
  apps/wallet-mobile/src/features/SetupWallet/legacy/SaveNanoX/SaveNanoXScreen.stories.tsx
  apps/wallet-mobile/src/features/SetupWallet/legacy/SaveNanoX/SaveNanoXScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/legacy/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.stories.tsx
  apps/wallet-mobile/src/features/SetupWallet/legacy/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  apps/wallet-mobile/src/features/WalletManager/SelectWalletFromList/SelectWalletFromListScreen.stories.tsx
  apps/wallet-mobile/src/features/WalletManager/SelectWalletFromList/SelectWalletFromListScreen.tsx
  apps/wallet-mobile/src/legacy/DeveloperScreen.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/fetch.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/errors.ts
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/SaveNanoX/SaveNanoXScreen.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.json
  packages/common/src/api/fetcher.test.ts
  packages/common/src/api/fetcher.ts
  packages/common/src/errors/errors.ts
Labels: fix

#3217 fix(wallet-setup): Preparing wallet state
  apps/wallet-mobile/src/features/SetupWallet/common/PreparingWallet/PreparingWallet.stories.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/PreparingWallet/PreparingWallet.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/constants.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/useStrings.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/AboutRecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/RecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Settings/RemoveWallet/RemoveWalletScreen.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/common/useStrings.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/SaveNanoX/SaveNanoXScreen.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.json
Labels: fix
