Repository Emurgo/yoroi, pull requests merged in 2024-12, with the labels that each got.

#3750 fix(wallet-mobile): last graph timestamp to match between periods
  apps/wallet-mobile/src/features/Portfolio/common/hooks/useGetPortfolioTokenChart.ts
Labels: fix

#3752 feature(wallet-mobile): new tx review operations log
  apps/wallet-mobile/src/components/Warning/Warning.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useStrings.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/mocks.ts
  apps/wallet-mobile/src/features/ReviewTx/common/operations.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/types.ts
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Overview/OverviewTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.stories.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/ReviewTx/common/hooks/useStrings.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeAppSettings/ApplicationSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/ShowFailedTxScreen/FailedTxScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/ShowSubmittedTxScreen/SubmittedTxScreen.json
Labels: feature

#3754 feature(wallet-mobile): portfolio token list performance improvement
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/PortfolioWalletTokenList.tsx
Labels: feature

#3756 fix(wallet-mobile): mnemonic suggestions buttons styles
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
Labels: fix

#3757 fix(wallet-mobile): tx review metadata json style
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Metadata/MetadataTab.tsx
Labels: fix

#3758 fix(wallet-mobile): receive address copied feedback in tx history actions banner
  apps/wallet-mobile/src/features/Transactions/common/strings.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Transactions/common/strings.json
Labels: fix

#3761 fix(wallet-mobile): portfolio chart includes padding offset
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/TokenChart.tsx
Labels: fix

#3759 fix(wallet-mobile): address details styling
  apps/wallet-mobile/src/components/Clipboard/ClipboardProvider.tsx
  apps/wallet-mobile/src/components/CopyButton.tsx
Labels: fix

#3743 release(wallet-mobile): v5.0.2
  .github/workflows/nightly.yml
  .github/workflows/wallet-mobile-checks.yml
  apps/wallet-mobile/.tool-versions
  apps/wallet-mobile/android/app/build.gradle
  apps/wallet-mobile/ios/nightly.plist
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/ios/yoroi/Info.plist
  apps/wallet-mobile/ios/yoroiTests/Info.plist
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/common/strings.ts
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/DownloadCatalystAppScreen/DownloadCatalystAppScreen.tsx
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
Labels: release

#3763 fix(wallet-mobile): Allow ledger to withdraw from non own address
  apps/wallet-mobile/src/features/Discover/common/ledger.ts
Labels: fix

#3766 chore(wallet-mobile): tx review copy updates
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useStrings.tsx
  apps/wallet-mobile/src/features/Send/common/strings.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/legacy/Dashboard/ShowSubmittedTxScreen/SubmittedTxScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/RegisterCatalyst/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/ReviewTx/common/hooks/useStrings.json
  apps/wallet-mobile/translations/messages/src/features/Send/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeAppSettings/ApplicationSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/ShowSubmittedTxScreen/SubmittedTxScreen.json
Labels: chore

#3764 fix(wallet-mobile): error boundary copy action
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/YoroiApp.tsx
Labels: fix

#3767 fix(wallet-mobile): tx review wrong reference inputs display
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/operations.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Overview/OverviewTab.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
Labels: fix

#3768 fix(wallet-mobile): collateral dialog closing
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageCollateral/ManageCollateralScreen.tsx
Labels: fix

#3770 fix(wallet-mobile): tx review reference inputs
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedTx.tsx
Labels: fix

#3769 fix(wallet-mobile): Fix HW TX signing
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/Discover/common/ledger.ts
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30-ledger.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utils.ts
  packages/swap/package.json
  yarn.lock
Labels: fix

#3774 fix(wallet-mobile): Handle HW errors gracefully in dApp connector
  apps/wallet-mobile/src/features/Discover/common/ConfirmHWConnectionModal.tsx
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/hw/hw.ts
  apps/wallet-mobile/src/yoroi-wallets/hw/hw.ts
Labels: fix

#3773 fix(wallet-mobile): portfolio sync issues
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/DashboardTokensList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenDetailsScreen.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
Labels: fix
