Repository Emurgo/yoroi, pull requests merged in 2024-07, with the labels that each got.

#3349 refactor(wallet-mobile): exch create order new token info
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
Labels: refactor

#3350 chore(portfolio): added new token-info single endpoint
  apps/wallet-mobile/src/features/Portfolio/common/TokenAmountItem/TokenInfoIcon.tsx
  apps/wallet-mobile/src/features/WalletManager/network-manager/network-manager.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.mocks.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.test.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.ts
  packages/portfolio/src/adapters/dullahan-api/transformers.test.ts
  packages/portfolio/src/adapters/dullahan-api/transformers.ts
  packages/portfolio/src/adapters/dullahan-api/types.ts
  packages/portfolio/src/adapters/token-info.mocks.ts
  packages/portfolio/src/balance-manager.test.ts
  packages/portfolio/src/helpers/create-primary-token-info.test.ts
  packages/portfolio/src/helpers/create-unknown-token-info.test.ts
  packages/portfolio/src/helpers/create-unknown-token-info.ts
  packages/portfolio/src/validators/token-info.ts
  packages/types/src/portfolio/api.ts
  packages/types/src/portfolio/info.ts
Labels: chore

#3352 chore(portfolio): added single token-info hook
  packages/portfolio/src/adapters/token-info.mocks.ts
  packages/portfolio/src/translators/reactjs/usePortfolioTokenInfo.test.tsx
  packages/portfolio/src/translators/reactjs/usePortfolioTokenInfo.tsx
Labels: chore

#3354 fix(wallet-mobile): Add error boundary screen to discover
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/SomethingWentWrong/Illustrations/ErrorImage.tsx
  apps/wallet-mobile/src/components/SomethingWentWrong/SomethingWentWrong.stories.tsx
  apps/wallet-mobile/src/components/SomethingWentWrong/SomethingWentWrong.tsx
  apps/wallet-mobile/src/features/Discover/DiscoverNavigator.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/components/SomethingWentWrong/SomethingWentWrong.json
Labels: fix

#3351 fix(dapp-connector): Add staking key signature when needed
  apps/wallet-mobile/src/yoroi-wallets/cardano/common/signatureUtils.ts
Labels: fix

#3356 feature(dashboard): withdrawal deregistration warning dialog revamp
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/ConfirmTxWithHwModal/ConfirmTxWithHwModal.tsx
  apps/wallet-mobile/src/components/ConfirmTxWithOsModal/ConfirmTxWithOsModal.tsx
  apps/wallet-mobile/src/components/ConfirmTxWithSpendingPasswordModal/ConfirmTxWithSpendingPasswordModal.tsx
  apps/wallet-mobile/src/components/DangerousActionModal/DangerousActionModal.stories.tsx
  apps/wallet-mobile/src/components/DangerousActionModal/DangerousActionModal.tsx
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/components/TwoActionView/TwoActionView.tsx
  apps/wallet-mobile/src/components/Warning/Warning.tsx
  apps/wallet-mobile/src/components/index.ts
  apps/wallet-mobile/src/features/Claim/useCases/AskConfirmation.tsx
  apps/wallet-mobile/src/features/Discover/common/ConfirmConnectionModal.tsx
  apps/wallet-mobile/src/features/Discover/common/UnverifiedDappModal.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/WelcomeDAppModal.tsx
  apps/wallet-mobile/src/features/Exchange/common/DescribeAction/DescribeAction.tsx
  apps/wallet-mobile/src/features/Links/useCases/AskToOpenAWalletScreen/AskToOpenAWalletScreen.tsx
  apps/wallet-mobile/src/features/Links/useCases/AskToRedirect/AskToRedirectScreen.tsx
  apps/wallet-mobile/src/features/Links/useCases/RequestedAdaPaymentWithLinkScreen/RequestedAdaPaymentWithLinkScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioDAppsTokenList/LiquidityPoolModal.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioDAppsTokenList/OpenOrderModal.tsx
  apps/wallet-mobile/src/features/Receive/common/SingleOrMultipleAddressesModal/SingleOrMultipleAddressesModal.tsx
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/RecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/EnterDrepIdModal/EnterDrepIdModal.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/WithdrawWarningModal/WithdrawWarningModal.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithHW.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithOs.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmWithSpendingPassword/ConfirmWithSpendingPassword.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/LedgerTransportSwitch.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/ShowSlippageInfo.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnLimitPrice/WarnLimitPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnPriceImpact/WarnPriceImpact.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnSlippage/WarnSlippage.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  apps/wallet-mobile/src/legacy/Staking/PoolTransition/PoolTransitionModal.tsx
  apps/wallet-mobile/src/legacy/Staking/PoolWarningModal/PoolWarningModal.stories.tsx
  apps/wallet-mobile/src/legacy/Staking/PoolWarningModal/PoolWarningModal.tsx
  apps/wallet-mobile/src/legacy/Staking/PoolWarningModal/index.ts
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.json
Labels: feature

#3360 fix(dashboard): spacing
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
Labels: fix

#3363 fix(swap): create order screen dark theme icons
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/Actions/OrderActions/OrderActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/EditSlippage.tsx
Labels: fix

#3365 fix(dapp-connector): Fix isEnabled check
  packages/dapp-connector/src/connector.js
Labels: fix

#3366 fix(dashboard): timer alignment
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/SelectPoolFromListScreen/SelectPoolFromListScreen.tsx
  apps/wallet-mobile/src/legacy/Dashboard/EpochProgress.tsx
Labels: fix

#3368 fix(swap): slippage screen
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/EditSlippageScreen/EditSlippageScreen.tsx
Labels: fix

#3370 fix(swap): paired balance alignment
  apps/wallet-mobile/src/features/Portfolio/common/TokenAmountItem/TokenAmountItem.tsx
Labels: fix

#3371 refactor(setup-wallet): improvements
  apps/wallet-mobile/src/features/SetupWallet/common/CardAboutPhrase/CardAboutPhrase.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/useStrings.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/VerifyRecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/common/useStrings.json
Labels: refactor

#3372 fix(common): android modal animation
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
Labels: fix

#3375 refactor(setup-wallet): restore wallet mnemonic buttons redesign
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/TextInput/TextInput.tsx
Labels: refactor

#3377 fix(swap): select dex list dark mode
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
Labels: fix

#3378 fix(staking): withdraw rewards warning
  apps/wallet-mobile/src/components/Checkbox/Checkbox.tsx
  apps/wallet-mobile/src/components/Icon/Checkbox.tsx
  apps/wallet-mobile/src/components/Icon/EmptyCheckbox.tsx
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/components/Warning/Warning.tsx
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.json
Labels: fix

#3379 fix(swap): dark theme icons
  apps/wallet-mobile/src/components/Icon/Chevron.tsx
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: fix

#3380 fix(swap): pool card shadow
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
Labels: fix

#3381 fix(send): minor styling issues
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/RemoveAmount.tsx
  apps/wallet-mobile/src/legacy/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/TxHistory/TxHistoryNavigator.json
Labels: fix

#3382 fix(portfolio): Portfolio nft click to details
  apps/wallet-mobile/src/features/Portfolio/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardNFTsList/DashboardNFTsList.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
Labels: fix

#3383 fix(swap): slippage screen style
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/EditSlippageScreen/EditSlippageScreen.tsx
Labels: fix

#3385 fix(swap): slippage screen styling
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/EditSlippageScreen/EditSlippageScreen.tsx
Labels: fix

#3386 fix(swap): slippage screen screen
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/EditSlippageScreen/EditSlippageScreen.tsx
Labels: fix

#3387 fix(wallet-mobile): Sign transaction with staking key for vote delegations
  apps/wallet-mobile/src/yoroi-wallets/cardano/common/signatureUtils.ts
  apps/wallet-mobile/translations/messages/src/legacy/Catalyst/ConfirmVotingTx.json
  apps/wallet-mobile/translations/messages/src/legacy/Catalyst/DownloadCatalyst.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/PoolDetails/PoolDetailScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
Labels: fix

#3390 fix(wallet-mobile): Dark theme nft placeholder
  apps/wallet-mobile/src/assets/img/nft-placeholder-dark.png
  apps/wallet-mobile/src/components/NftPreview/NftPreview.tsx
  apps/wallet-mobile/src/features/Nfts/useCases/NftDetails/NftDetailsImage.tsx
  apps/wallet-mobile/src/features/Portfolio/common/MediaDetails/MediaDetails.tsx
  apps/wallet-mobile/src/features/Portfolio/common/MediaGallery/MediaGallery.tsx
  apps/wallet-mobile/src/features/Portfolio/common/MediaPreview/MediaPreview.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardNFTsList/DashboardNFTsList.tsx
  apps/wallet-mobile/translations/messages/src/features/Portfolio/common/MediaDetails/MediaDetails.json
Labels: fix

#3391 fix(wallet-mobile): Allow WebView to open all origins
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/WebViewItem.tsx
Labels: fix

#3394 fix(wallet-mobile): Improve performance of webview on android and block opening new tab
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/WebViewItem.tsx
Labels: fix

#3395 fix(wallet-mobile): Fix staking key check
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
Labels: fix

#3396 refactor(tx-details): revamp + dark theme
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/features/ListTxHistory/common/strings.tsx
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ListTxHistory/AddressModal/AddressModal.tsx
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ShowTxDetails/TxDetails.tsx
  apps/wallet-mobile/translations/messages/src/features/ListTxHistory/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/ListTxHistory/useCases/ShowTxDetails/TxDetails.json
Labels: refactor

#3398 fix(tx-details): styling minors
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ShowTxDetails/AddressModal/AddressModal.stories.tsx
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ShowTxDetails/AddressModal/AddressModal.tsx
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ShowTxDetails/TxDetails.tsx
Labels: fix

#3399 fix(common): result screens background and spacing
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/SubmittedTx/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/SubmittedTx/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/legacy/Staking/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Staking/FailedTx/FailedTxScreen.json
Labels: fix

#3400 fix(wallet-mobile): Fix portfolio navigation
  apps/wallet-mobile/src/features/Nfts/useCases/Nfts.tsx
  apps/wallet-mobile/src/features/Portfolio/PortfolioNavigator.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardNFTsList/DashboardNFTsList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/DashboardTokensList.tsx
  apps/wallet-mobile/translations/messages/src/features/Nfts/useCases/Nfts.json
Labels: fix

#3401 fix(wallet-mobile): Fix send funnel Ada price
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
Labels: fix

#3404 fix(wallet-mobile): Show correct theme name for auto
  packages/theme/src/ThemeProvider.test.tsx
  packages/theme/src/ThemeProvider.tsx
Labels: fix

#3405 fix(wallet-mobile): Fix missing background in ios, maybe
  apps/wallet-mobile/src/features/Nfts/useCases/NftDetails/NftDetailsImage.tsx
  apps/wallet-mobile/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.json
Labels: fix

#3406 fix(tx-history): top menu transparency android
  apps/wallet-mobile/src/hooks/useStatusBar.ts
Labels: fix

#3412 fix(wallet-mobile): Restore pin keyboard style
  apps/wallet-mobile/src/components/NumericKeyboard.tsx
  apps/wallet-mobile/src/features/Auth/PinLoginScreen/PinLoginScreen.tsx
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ListTxHistory/TxHistory.tsx
  apps/wallet-mobile/translations/messages/src/features/Auth/PinLoginScreen/PinLoginScreen.json
Labels: fix

#3417 fix(wallet-mobile) keyboard avoid view
  apps/wallet-mobile/src/components/KeyboardAvoidingView/KeyboardAvoidingView.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
Labels: fix

#3419 fix(wallet-mobile): modal close button zIndex
  apps/wallet-mobile/src/components/legacy/Modal/Modal.stories.tsx
  apps/wallet-mobile/src/components/legacy/Modal/Modal.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/translations/messages/src/components/ErrorModal/ErrorModal.json
Labels: fix

#3421 fix(catalyst): funnel title
  apps/wallet-mobile/src/kernel/i18n/global-messages.ts
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
Labels: fix

#3424 feature(tx-list): multiparty icon
  apps/wallet-mobile/src/components/Icon/Direction.tsx
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/MultiParty.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ListTxHistory/TxHistoryList/TxHistoryListItem.tsx
Labels: feature

#3425 fix(wallet-mobile): loading inputs rnp
  apps/wallet-mobile/src/features/SetupWallet/legacy/ImportReadOnlyWallet/ImportReadOnlyWalletScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/legacy/SaveNanoX/SaveNanoXScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/legacy/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/translations/messages/src/components/ErrorModal/ErrorModal.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/ImportReadOnlyWallet/ImportReadOnlyWalletScreen.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/SaveNanoX/SaveNanoXScreen.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.json
Labels: fix

#3422 fix(tx-list): background color
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ListTxHistory/TxHistory.tsx
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ListTxHistory/TxHistoryList/TxHistoryListItem.tsx
Labels: fix

#3427 fix(wallet-mobile): confirm-tx funds alignment
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/CurrentBalance.tsx
Labels: fix

#3429 fix(wallet-mobile): please-wait theming confirm-tx
  apps/wallet-mobile/src/components/PleaseWaitModal.tsx
Labels: fix

#3430 fix(wallet-mobile): catalyst styles qr sharing + bottom modal
  apps/wallet-mobile/src/components/KeyboardAvoidingView/KeyboardAvoidingView.tsx
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/components/ShareQRCodeCard/CaptureShareQRCodeCard/CaptureShareQRCodeCard.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/common/InsufficientFundsModal.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/common/components.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ConfirmPin/ConfirmPin.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ConfirmVotingTx/ConfirmVotingTx.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/DisplayPin/DisplayPin.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/DownloadCatalyst/DownloadCatalyst.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ShowQrCode/ShowQrCode.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/InputReceiver.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/hooks/useNextTick.tsx
  apps/wallet-mobile/src/hooks/useStatusBar.ts
  apps/wallet-mobile/src/kernel/keyboard/useIsKeyboardOpen.tsx
  apps/wallet-mobile/translations/messages/src/kernel/i18n/global-messages.json
Labels: fix

#3431 fix(wallet-mobile): restore wallet msg color
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
Labels: fix

#3433 fix(wallet-mobile): header height home
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ListTxHistory/TxHistory.tsx
Labels: fix

#3432 fix(wallet-mobile): android switch color thumb
  apps/wallet-mobile/src/features/Settings/common/SettingsSwitch.tsx
Labels: fix

#3434 fix(wallet-mobile): fix collateral
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/CurrentBalance.tsx
Labels: fix

#3435 fix(wallet-mobile): fix language warning contrib
  apps/wallet-mobile/src/components/Icon/Cross.tsx
  apps/wallet-mobile/src/components/LanguagePicker/LanguagePickerWarning.tsx
  apps/wallet-mobile/translations/messages/src/components/LanguagePicker/LanguagePickerWarning.json
Labels: fix

#3436 fix(wallet-mobile): receive spacing
  apps/wallet-mobile/src/components/ShareQRCodeCard/ShareQRCodeCard.tsx
  apps/wallet-mobile/src/features/Receive/useCases/DescribeSelectedAddressScreen.tsx
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
Labels: fix

#3437 fix(wallet-mobile): analytics switcher
  apps/wallet-mobile/src/components/Analytics/Analytics.tsx
  apps/wallet-mobile/translations/messages/src/components/Analytics/Analytics.json
Labels: fix

#3438 fix(wallet-mobile): swap cards + expandable
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.tsx
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
Labels: fix

#3441 chore(wallet-mobile): dropped dapp ff
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/kernel/config.ts
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: chore

#3442 fix(catalyst): styling minors
  apps/wallet-mobile/src/features/RegisterCatalyst/CatalystNavigator.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/common/strings.ts
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ConfirmPin/ConfirmPin.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/DisplayPin/DisplayPin.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/DownloadCatalyst/DownloadCatalyst.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ShowQrCode/ShowQrCode.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/RegisterCatalyst/common/strings.json
Labels: fix

#3439 refactor(wallet-mobile): Refactor portfolio transactions
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ListTxHistory/TxHistoryList/TxHistoryList.tsx
  apps/wallet-mobile/src/features/ListTxHistory/useCases/ListTxHistory/TxHistoryList/index.ts
  apps/wallet-mobile/src/features/Portfolio/PortfolioNavigator.tsx
  apps/wallet-mobile/src/features/Portfolio/common/useGetPortfolioTokenTransaction.ts
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenDetailLayout.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenDetailsScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/PortfolioTokenInfo.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Transactions/TransactionItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Transactions/index.tsx
  apps/wallet-mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Transactions/common/memos/memosManager.test.ts
  apps/wallet-mobile/src/features/Transactions/common/memos/memosManager.ts
  apps/wallet-mobile/src/features/Transactions/common/strings.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AddressModal/AddressModal.stories.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AddressModal/AddressModal.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AssetList.stories.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AssetList.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AssetListSend.style.ts
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AssetListTransaction.style.ts
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/Base.style.ts
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/TxDetails.stories.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/TxDetails.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/index.ts
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/BalanceBanner.stories.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/BalanceBanner.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/CollapsibleHeader.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/LockedDeposit.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/SyncErrorBanner.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/TxHistory.stories.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/WarningBanner.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/useOnScroll.ts
  apps/wallet-mobile/src/features/Transactions/useCases/TxList/TxFilterProvider.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxList/TxList.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxList/TxListEmpty.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxList/TxListItem.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxList/TxListItemSkeleton.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Transactions/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Transactions/common/strings.json
Labels: feature, refactor

#3444 fix(swap): slippage input cursor color
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/EditSlippageScreen/EditSlippageScreen.tsx
Labels: fix

#3445 fix(wallet-mobile): Minor portfolio fixes and flags
  apps/wallet-mobile/src/features/Portfolio/common/PortfolioTokenDetailContext.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardNFTsList/DashboardNFTsList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenBalance/PortfolioTokenBalance.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenDetailsScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Overview/index.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Performance.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxList/TxFilterProvider.tsx
  apps/wallet-mobile/src/features/index.ts
  apps/wallet-mobile/src/kernel/navigation.tsx
Labels: fix

#3443 fix(catalyst): last step
  apps/wallet-mobile/src/features/RegisterCatalyst/CatalystNavigator.tsx
Labels: fix

#3447 fix(wallet-mobile): Hide pt policyid and fingerprint
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Overview/index.tsx
Labels: fix

#3448 fix(wallet-mobile): Unuse random mocks in portfolio
  apps/wallet-mobile/src/components/PairedBalance/PairedBalance.tsx
  apps/wallet-mobile/src/features/Portfolio/common/useGetQuantityChange.ts
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/BalanceCard/BalanceCard.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/BalanceCard/BalanceCardContent.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/DashboardTokenItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenBalance/PortfolioTokenBalance.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioTokenListScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/TokenBalanceItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/TotalTokensValue/TotalTokensValueContent.tsx
  apps/wallet-mobile/src/features/WalletManager/useCases/SelectWalletFromListScreen/AggregatedBalance.tsx
  apps/wallet-mobile/translations/messages/src/components/PairedBalance/PairedBalance.json
Labels: fix

#3449 suggestion: Refactor NetworkPickerList data
  apps/wallet-mobile/src/features/Settings/ChangeNetwork/NetworkPickerList.tsx
Labels: feature

#3450 fix(wallet-mobile): bio auth enable theme
  apps/wallet-mobile/src/features/Initialization/ChooseBiometricLogin/ChooseBiometricLoginScreen.tsx
Labels: fix

#3452 fix(wallet-mobile): Hide portfolio transaction export
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/ExportTokenTransactions.tsx
  apps/wallet-mobile/src/features/index.ts
Labels: fix

#3456 fix(swap): 'Select Swap' label is missing
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
Labels: fix

#3457 fix(delegation): token name
  apps/wallet-mobile/src/yoroi-wallets/utils/format.ts
  apps/wallet-mobile/translations/messages/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.json
  apps/wallet-mobile/translations/messages/src/yoroi-wallets/utils/format.json
Labels: fix

#3455 fix(send): error screen background
  apps/wallet-mobile/src/components/Boundary/Boundary.tsx
Labels: fix

#3453 fix(tx-details): remove modal auto close
  apps/wallet-mobile/src/features/Transactions/useCases/TxDetails/AddressModal/AddressModal.tsx
Labels: fix

#3454 fix(restore-wallet): mnemonic input message color
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
Labels: fix

#3458 refactor(wallet-mobile): feature flags
  apps/wallet-mobile/src/components/ConfirmTx/ConfirmTx.tsx
  apps/wallet-mobile/src/components/ConfirmTxWithSpendingPasswordModal/ConfirmTxWithSpendingPasswordModal.tsx
  apps/wallet-mobile/src/features/Portfolio/common/PortfolioTokenDetailContext.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/ExportTokenTransactions.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenDetailsScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Overview/index.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/legacy/WalletForm.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmWithSpendingPassword/ConfirmWithSpendingPassword.tsx
  apps/wallet-mobile/src/features/WalletManager/useCases/SelectWalletFromListScreen/SelectWalletFromListScreen.tsx
  apps/wallet-mobile/src/features/WalletManager/useCases/SelectWalletFromListScreen/WalletListItem.tsx
  apps/wallet-mobile/src/kernel/features.ts
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/ConfirmTx/ConfirmTxWithPassword.tsx
  apps/wallet-mobile/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  apps/wallet-mobile/src/legacy/Staking/PoolTransition/usePoolTransition.tsx
  apps/wallet-mobile/src/legacy/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/nfts.ts
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/WalletForm.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/PoolTransition/usePoolTransition.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
  apps/wallet-mobile/translations/messages/src/yoroi-wallets/utils/format.json
Labels: refactor

#3461 feature(network-selection): preprod banner
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/PreprodFaucetBanner.stories.tsx
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/PreprodFaucetBanner.tsx
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/ShowBuyBanner.tsx
  apps/wallet-mobile/src/features/Exchange/common/useStrings.tsx
  apps/wallet-mobile/src/features/Exchange/illustrations/PreprodFaucetBannerLogo.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/DashboardTokensList.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Exchange/common/useStrings.json
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.json
  apps/wallet-mobile/translations/messages/src/yoroi-wallets/utils/format.json
Labels: feature

#3462 feature(wallet-mobile): Adds Ada price integration
  apps/wallet-mobile/src/features/Portfolio/common/helpers/priceChange.ts
  apps/wallet-mobile/src/features/Portfolio/common/useGetPortfolioTokenChart.ts
  apps/wallet-mobile/src/features/Portfolio/common/useQuantityChange.ts
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/BalanceCard/BalanceCardContent.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/DashboardTokenItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/PortfolioTokenChart.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/PortfolioTokenChartSkeleton.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/TokenChart.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/TokenChartToolBar.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/TokenPerformance.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/TokenBalanceItem.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/TotalTokensValue/TotalTokensValueContent.tsx
  apps/wallet-mobile/src/features/Settings/Currency/CurrencyContext.tsx
  apps/wallet-mobile/src/features/Settings/Currency/CurrencyPickerList.tsx
  apps/wallet-mobile/src/kernel/constants.ts
  apps/wallet-mobile/src/kernel/features.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/useAdaPrice.tsx
  apps/wallet-mobile/src/yoroi-wallets/types/other.ts
Labels: feature

#3467 refactor(theming): theme announcement toggle
  apps/wallet-mobile/src/features/Initialization/DarkThemeAnnouncement/DarkThemeAnnouncement.tsx
  apps/wallet-mobile/translations/messages/src/features/Initialization/DarkThemeAnnouncement/DarkThemeAnnouncement.json
Labels: refactor

#3471 feature(network-selection): metrics
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/Settings/ChangeNetwork/NetworkPickerList.tsx
  apps/wallet-mobile/src/features/Settings/ChangeNetwork/NetworkTag.tsx
  apps/wallet-mobile/src/kernel/metrics/ampli/index.ts
  apps/wallet-mobile/src/kernel/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/kernel/metrics/metricsManager.tsx
  apps/wallet-mobile/src/kernel/metrics/mocks.ts
Labels: feature

#3472 chore(catalyst): copy update
  apps/wallet-mobile/src/features/RegisterCatalyst/common/strings.ts
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/RegisterCatalyst/common/strings.json
Labels: chore
