Repository Emurgo/yoroi, pull requests merged in 2024-10, with the labels that each got.

#3667 fix(wallet-mobile): remove decimals from hidden values
  apps/wallet-mobile/src/features/Settings/PrivacyMode/PrivacyMode.tsx
  apps/wallet-mobile/src/legacy/Dashboard/UserSummary.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/UserSummary.json
Labels: fix

#3668 fix(wallet-mobile): add placeholder for "remove wallet" input
  apps/wallet-mobile/src/features/Settings/RemoveWallet/RemoveWalletScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/RemoveWallet/RemoveWalletScreen.json
Labels: fix

#3669 fix(wallet-mobile): navigating from the tabbar to portfolio goes to initial screen
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: fix

#3670 feature(theme): input selected color
  apps/wallet-mobile/src/features/Exchange/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/MnemonicInput.tsx
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/EditPrice/EditPrice.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/EditSlippage/EditSlippageScreen/EditSlippageScreen.tsx
  packages/theme/src/themed-palettes/black.ts
  packages/theme/src/themed-palettes/light.ts
  packages/theme/src/types.ts
Labels: feature

#3671 chore(wallet-mobile): dropped portfolio dev screen + navigation
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/features/Dev/DeveloperScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/PortfolioNavigator.tsx
  apps/wallet-mobile/src/features/Portfolio/common/hooks/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/Actions.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: fix

#3675 refactor(wallet-mobile): import types from csl for tx review
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/types.ts
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: refactor

#3673 fix(wallet-mobile): Change copy and add warning in dapp explorer
  apps/wallet-mobile/src/components/InfoBanner/InfoBanner.stories.tsx
  apps/wallet-mobile/src/components/InfoBanner/InfoBanner.tsx
  apps/wallet-mobile/src/features/Discover/common/useStrings.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Discover/common/useStrings.json
Labels: fix

#3676 feature(wallet-mobile): cap to open secondary token link when NFT
  apps/wallet-mobile/src/features/Portfolio/common/MediaDetailsScreen/MediaDetailsScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Overview/Overview.tsx
  apps/wallet-mobile/translations/messages/src/features/Portfolio/common/MediaDetailsScreen/MediaDetailsScreen.json
  packages/portfolio/src/helpers/trait-value-expander.test.ts
  packages/portfolio/src/helpers/trait-value-expander.ts
  packages/portfolio/src/index.ts
  packages/types/src/index.ts
Labels: feature

#3677 chore(wallet-mobile): sharing yoroi link and no longer cardano link
  apps/wallet-mobile/src/components/ShareQRCodeCard/ShareQRCodeCard.tsx
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
Labels: chore

#3678 chore(wallet-mobile): support yoroi links throught qr scan
  apps/wallet-mobile/src/features/Scan/common/mocks.ts
  apps/wallet-mobile/src/features/Scan/common/parsers.test.ts
  apps/wallet-mobile/src/features/Scan/common/parsers.ts
  apps/wallet-mobile/src/features/Scan/common/useTriggerScanAction.tsx
  packages/types/src/index.ts
  packages/types/src/scan/actions.ts
Labels: chore

#3679 fix(wallet-mobile): add scroll to receive modal
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
Labels: fix

#3680 fix(wallet-mobile): qr capture colors
  apps/wallet-mobile/src/components/ShareQRCodeCard/CaptureShareQRCodeCard/CaptureShareQRCodeCard.tsx
Labels: fix

#3682 fix(wallet-mobile): qr link full read within yoroi
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
Labels: fix

#3672 feature(wallet-mobile): token details dialog for new tx review
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/MediaPreview/MediaPreview.tsx
  apps/wallet-mobile/src/components/SimpleTab/SimpleTab.stories.tsx
  apps/wallet-mobile/src/components/SimpleTab/SimpleTab.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppExplorerTabItem/DAppExplorerTabItem.stories.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/SelectDappFromListScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/common/MediaDetailsScreen/MediaDetailsScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/common/MediaGallery/MediaGallery.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardNFTsList/DashboardNFTsList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/ListMediaGalleryScreen/ZoomMediaImageScreen.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/Accordion.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/Address.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/CopiableText.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/TokenDetails.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/TokenItem.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useStrings.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/types.ts
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/Overview/OverviewTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/UTxOs/UTxOsTab.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Portfolio/common/MediaDetailsScreen/MediaDetailsScreen.json
  apps/wallet-mobile/translations/messages/src/features/ReviewTx/common/hooks/useStrings.json
Labels: feature

#3686 fix(wallet-mobile): disabled actions label color
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/ActionsBanner.tsx
Labels: fix

#3687 chore(types): add more api errors
  packages/types/src/api/errors.ts
  packages/types/src/api/status-code.ts
Labels: chore

#3664 fix(wallet-mobile): offline crashes
  apps/wallet-mobile/src/features/WalletManager/common/hooks/useBestBlock.tsx
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: fix

#3689 refactor(swap): move swap calculation functions to manager
  apps/wallet-mobile/src/features/Swap/useCases/ReviewSwap/TransactionSummary.stories.tsx
  apps/wallet-mobile/src/kernel/config.ts
  packages/swap/src/helpers/mocks.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.test.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.ts
  packages/swap/src/helpers/pools/getBestPoolCalculation.test.ts
  packages/swap/src/helpers/pools/getBestPoolCalculation.ts
  packages/swap/src/index.ts
  packages/swap/src/manager.mocks.ts
  packages/swap/src/manager.ts
  packages/swap/src/translators/reactjs/state/selectors/selectedPoolCalculationSelector.test.ts
  packages/swap/src/translators/reactjs/state/selectors/selectedPoolCalculationSelector.ts
  packages/swap/src/translators/reactjs/state/state.ts
  packages/types/src/index.ts
  packages/types/src/swap/calculations.ts
  packages/types/src/swap/manager.ts
Labels: refactor

#3690 feature(wallet-mobile): new tx review for yoroi governance
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/ReviewTx/common/TokenItem.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useOnConfirm.tsx
  apps/wallet-mobile/src/features/Staking/Governance/GovernanceNavigator.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/helpers.ts
  apps/wallet-mobile/src/features/Staking/Governance/common/helpers.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/navigation.ts
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ChangeVote/ChangeVoteScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ConfirmTx/ConfirmTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
Labels: feature

#3663 feature(wallet-mobile): prefetch ada prices
  apps/wallet-mobile/src/features/Portfolio/common/hooks/useGetPortfolioTokenChart.ts
  apps/wallet-mobile/src/features/Portfolio/common/hooks/useGetTokensWithBalance.ts
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/DashboardTokensList.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/PortfolioTokenChart.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/TokenChartToolBar.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenChart/TokenPerformance.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenDetailsScreen.tsx
  apps/wallet-mobile/src/kernel/features.ts
  apps/wallet-mobile/src/kernel/query-client.ts
Labels: feature

#3691 fix(wallet-mobile): restore debug mode
  apps/wallet-mobile/src/kernel/config.ts
Labels: fix

#3692 fix(wallet-mobile): autofocus and caret color for send edit amount
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
Labels: fix

#3694 feature(wallet-mobile): new tx review for catalyst
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/RegisterCatalyst/CatalystNavigator.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ConfirmPin/ConfirmPin.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ConfirmVotingTx/ConfirmVotingTx.stories.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ConfirmVotingTx/ConfirmVotingTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/ReviewTxProvider.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedMetadata.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useOnConfirm.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/types.ts
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/Metadata/MetadataTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/helpers.tsx
  packages/staking/src/catalyst/translators/context.tsx
  packages/staking/src/catalyst/translators/state.test.tsx
  packages/staking/src/catalyst/translators/state.tsx
Labels: feature

#3695 fix(wallet-mobile): navigation weirdness in Send
  apps/wallet-mobile/src/features/Send/common/navigation.ts
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
Labels: fix

#3696 feature(wallet-mobile): new tx review for stake delegation
  apps/wallet-mobile/src/features/ReviewTx/common/TokenItem.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useStrings.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/operations.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/types.ts
  apps/wallet-mobile/src/features/Staking/Governance/common/helpers.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/legacy/Dashboard/DashboardNavigator.tsx
  apps/wallet-mobile/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.stories.tsx
  apps/wallet-mobile/src/legacy/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  apps/wallet-mobile/src/legacy/Staking/DelegationConfirmation/index.ts
  apps/wallet-mobile/src/legacy/Staking/PoolTransition/usePoolTransition.tsx
  apps/wallet-mobile/src/legacy/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/delegationUtils.ts
  apps/wallet-mobile/translations/messages/src/features/ReviewTx/common/hooks/useStrings.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/DashboardNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/PoolTransition/usePoolTransition.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
Labels: feature

#3697 refactor(staking): use votingPowerThreshold
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/CatalystNavigator.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/common/InsufficientFundsModal.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/common/hooks.ts
  apps/wallet-mobile/src/features/WalletManager/common/adapters/cardano/catalyst-config.ts
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
  packages/staking/src/catalyst/adapters/fund-info.mocks.ts
  packages/staking/src/catalyst/fund-info.mocks.ts
  packages/staking/src/catalyst/transformers.ts
  packages/staking/src/catalyst/validators.test.ts
  packages/staking/src/catalyst/validators.ts
  packages/staking/src/types.ts
Labels: refactor

#3702 fix(wallet-mobile): add scroll to disclaimer modal
  apps/wallet-mobile/src/features/Discover/common/UnverifiedDappModal.tsx
Labels: fix

#3701 fix(wallet-mobile): Make navigation bar color transparent
  apps/wallet-mobile/android/app/src/dev/res/values/styles.xml
  apps/wallet-mobile/android/app/src/nightly/res/values/styles.xml
  apps/wallet-mobile/android/app/src/production/res/values/styles.xml
Labels: fix

#3626 feat(notifications): Add notifications feature and transaction received notification
  apps/wallet-mobile/android/app/build.gradle
  apps/wallet-mobile/android/app/src/dev/AndroidManifest.xml
  apps/wallet-mobile/android/app/src/main/AndroidManifest.xml
  apps/wallet-mobile/android/app/src/main/java/com/emurgo/MainApplication.java
  apps/wallet-mobile/android/settings.gradle
  apps/wallet-mobile/app.json
  apps/wallet-mobile/ios/Podfile
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/ios/yoroi/AppDelegate.mm
  apps/wallet-mobile/ios/yoroi/Info.plist
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/src/features/Dev/DeveloperScreen.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationsDevScreen.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/hooks.ts
  apps/wallet-mobile/src/features/Notifications/useCases/common/notification-manager.ts
  apps/wallet-mobile/src/features/Notifications/useCases/common/notifications.ts
  apps/wallet-mobile/src/features/Notifications/useCases/common/transaction-received-notification.ts
  apps/wallet-mobile/src/kernel/features.ts
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  metro.config.js
  packages/notifications/README.md
  packages/notifications/package.json
  packages/notifications/src/index.ts
  packages/notifications/src/notification-manager.test.ts
  packages/notifications/src/notification-manager.ts
  packages/notifications/src/translators/reactjs/NotificationProvider.test.tsx
  packages/notifications/src/translators/reactjs/NotificationProvider.tsx
  packages/notifications/src/translators/reactjs/mocks.ts
  packages/notifications/src/translators/reactjs/useNotificationsConfig.test.tsx
  packages/notifications/src/translators/reactjs/useNotificationsConfig.ts
  packages/notifications/src/translators/reactjs/useReceivedNotificationEvents.test.tsx
  packages/notifications/src/translators/reactjs/useReceivedNotificationEvents.ts
  packages/notifications/src/translators/reactjs/useResetNotificationsConfig.test.tsx
  packages/notifications/src/translators/reactjs/useResetNotificationsConfig.ts
  packages/notifications/src/translators/reactjs/useUpdateNotificationsConfig.test.tsx
  packages/notifications/src/translators/reactjs/useUpdateNotificationsConfig.ts
  packages/types/src/index.ts
  packages/types/src/notifications/manager.ts
  yarn.lock
Labels: feature

#3685 chore(wallet-mobile): Bump CSL
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/Discover/common/errors.ts
  apps/wallet-mobile/src/features/Discover/useCases/ReviewTransaction/ReviewTransaction.tsx
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30-ledger.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.ts
  packages/common/src/numbers/to-bigint.ts
  packages/dapp-connector/src/resolver.ts
  packages/swap/package.json
  packages/types/package.json
  yarn.lock
Labels: chore

#3705 fix(wallet-mobile): Fix keyboard avoiding view
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
Labels: fix

#3708 Suggestion to open PR
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/operations.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/types.ts
Labels: proposal, refactor

#3698 release(wallet-mobile): v5.0.1 hotfix
  apps/wallet-mobile/android/app/build.gradle
  apps/wallet-mobile/ios/nightly.plist
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/ios/yoroi/Info.plist
  apps/wallet-mobile/ios/yoroiTests/Info.plist
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/features/Discover/common/ConfirmConnectionModal.tsx
  apps/wallet-mobile/src/features/Discover/common/UnverifiedDappModal.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/WelcomeDAppModal.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  yarn.lock
Labels: release

#3711 feat(wallet-mobile): Add PT price changed notification
  apps/wallet-mobile/src/features/Notifications/useCases/common/hooks.ts
  apps/wallet-mobile/src/features/Notifications/useCases/common/notification-manager.ts
  apps/wallet-mobile/src/features/Notifications/useCases/common/notifications.ts
  apps/wallet-mobile/src/features/Notifications/useCases/common/primary-token-price-changed-notification.ts
  apps/wallet-mobile/src/features/Notifications/useCases/common/storage.ts
  apps/wallet-mobile/src/features/Notifications/useCases/common/transaction-received-notification.ts
  apps/wallet-mobile/src/features/Settings/useCases/changeAppSettings/Currency/CurrencyContext.tsx
  packages/notifications/src/notification-manager.test.ts
  packages/notifications/src/notification-manager.ts
  packages/types/src/notifications/manager.ts
Labels: feature

#3714 fix(wallet-mobile): exchange value format
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
Labels: fix

#3717 feature(wallet-mobile): new transaction for discovery (dapps)
  apps/wallet-mobile/src/features/Discover/DiscoverNavigator.tsx
  apps/wallet-mobile/src/features/Discover/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Discover/useCases/ReviewTransaction/ReviewTransaction.stories.tsx
  apps/wallet-mobile/src/features/Discover/useCases/ReviewTransaction/ReviewTransaction.tsx
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.ts
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedMetadata.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useOnConfirm.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useSignTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useTxBody.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
Labels: feature

#3719 refactor(wallet-mobile): dropped legacy assert things
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/Dev/DeveloperScreen.tsx
  apps/wallet-mobile/src/kernel/encryption/encryption.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/account-manager/account-manager.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/account-manager/account-manager.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/api.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/bip44Validators/bip44Validators.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip8/cip8.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/delegationUtils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/processTransactions/processTransactions.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/transactionManager/transactionManager.ts
  yarn.lock
Labels: refactor

#3720 chore(api): updated the protocol params endpoint with the new api response
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/WalletManager/network-manager/network-manager.ts
  packages/api/package.json
  packages/api/src/cardano/api/cardano-api-maker.mocks.ts
  packages/api/src/cardano/api/protocol-params.mocks.ts
  packages/api/src/cardano/api/protocol-params.test.ts
  packages/api/src/cardano/api/protocol-params.ts
  packages/claim/package.json
  packages/common/package.json
  packages/dapp-connector/package.json
  packages/exchange/package.json
  packages/explorers/package.json
  packages/links/package.json
  packages/notifications/package.json
  packages/portfolio/package.json
  packages/resolver/package.json
  packages/setup-wallet/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/theme/package.json
  packages/transfer/package.json
  packages/types/package.json
  packages/types/src/chain/cardano.ts
  packages/types/src/index.ts
  packages/types/src/numbers/ratio.ts
Labels: chore
