Repository Emurgo/yoroi, pull requests merged in 2024-01, with the labels that each got.

#2963 feat(cdn): Use PixelRatio to get sizes based on dpi
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: feature

#2962 fix(swap): price impact risk color, copy and modal
  apps/wallet-mobile/src/features/Swap/common/constants.ts
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnPriceImpact/WarnPriceImpact.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnPriceImpact/WarnPriceImpact.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: fix

#2964 chore: New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#2959 feature(resolver): cns integration
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Claim/module/api.ts
  apps/wallet-mobile/src/features/Send/common/useSendReceiver.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/InputReceiver.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ShowResolvedAddressSelected.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/NotifySupportedNameServers/NotifySupportedNameServers.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/SelectNameServer/SelectNameServer.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  packages/api/src/cardano/api/token-onchain-metadata.ts
  packages/resolver/package.json
  packages/resolver/src/adapters/api.test.ts
  packages/resolver/src/adapters/api.ts
  packages/resolver/src/adapters/cns.test.ts
  packages/resolver/src/adapters/cns.ts
  packages/resolver/src/adapters/cns/api-helpers.test.ts
  packages/resolver/src/adapters/cns/api-helpers.ts
  packages/resolver/src/adapters/cns/api.test.ts
  packages/resolver/src/adapters/cns/api.ts
  packages/resolver/src/adapters/cns/cardano-api-maker.mocks.ts
  packages/resolver/src/adapters/cns/cardano-api-maker.test.ts
  packages/resolver/src/adapters/cns/cardano-api-maker.ts
  packages/resolver/src/adapters/cns/types.ts
  packages/resolver/src/adapters/cns/utils.test.ts
  packages/resolver/src/adapters/cns/utils.ts
  packages/resolver/src/adapters/handle/api.mocks.ts
  packages/resolver/src/adapters/handle/api.test.ts
  packages/resolver/src/adapters/handle/api.ts
  packages/resolver/src/adapters/unstoppable/api.mocks.ts
  packages/resolver/src/adapters/unstoppable/api.test.ts
  packages/resolver/src/adapters/unstoppable/api.ts
  packages/resolver/src/translators/reactjs/hooks/useResolverCryptoAddresses.tsx
  packages/resolver/src/utils/isDomain.ts
  packages/resolver/src/utils/isResolvableDomain.ts
  packages/types/src/index.ts
  packages/types/src/resolver/api.ts
  packages/types/src/resolver/errors.ts
  yoroi.code-workspace
Labels: feature

#2966 fix: lifting action section
  apps/wallet-mobile/src/Dashboard/DashboardNavigator.tsx
  apps/wallet-mobile/src/Staking/DelegationConfirmation/DelegationConfirmation.tsx
  apps/wallet-mobile/src/WalletInit/RestoreWallet/RestoreWalletScreen.tsx
  apps/wallet-mobile/src/features/Settings/ChangePassword/ChangePasswordScreen.tsx
  apps/wallet-mobile/src/features/Settings/ChangeWalletName/ChangeWalletName.tsx
  apps/wallet-mobile/src/features/Settings/EasyConfirmation/EnableEasyConfirmationScreen.tsx
  apps/wallet-mobile/src/features/Settings/RemoveWallet/RemoveWalletScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/translations/messages/src/Dashboard/DashboardNavigator.json
  apps/wallet-mobile/translations/messages/src/Staking/DelegationConfirmation/DelegationConfirmation.json
  apps/wallet-mobile/translations/messages/src/WalletInit/RestoreWallet/RestoreWalletScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ChangePassword/ChangePasswordScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ChangeWalletName/ChangeWalletName.json
  apps/wallet-mobile/translations/messages/src/features/Settings/EasyConfirmation/EnableEasyConfirmationScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/RemoveWallet/RemoveWalletScreen.json
Labels: fix

#2967 fix(resolver): change invalid datum action
  packages/resolver/src/adapters/cns/api-helpers.test.ts
  packages/resolver/src/adapters/cns/api-helpers.ts
Labels: fix

#2969 fix(resolver): change invalid inline datum action
  packages/resolver/src/adapters/cns/api-helpers.test.ts
  packages/resolver/src/adapters/cns/api-helpers.ts
Labels: fix

#2970 fix(send): error message for domain not found
  apps/wallet-mobile/src/features/Send/common/strings.ts
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Send/common/strings.json
Labels: fix

#2968 fix(swap) scroll on transaction confirmation
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
Labels: fix

#2971 chore: New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#2973 chore(resolver): release 1.5.0
  apps/wallet-mobile/package.json
  packages/resolver/package.json
Labels: chore

#2975 chore: release packages v1.5.0
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/banxa/package.json
  packages/common/package.json
  packages/links/package.json
  packages/openswap/package.json
  packages/resolver/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/types/package.json
Labels: chore

#2976 feature(resolver): copy changes
  apps/wallet-mobile/src/features/Send/common/strings.ts
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Send/common/strings.json
Labels: feature

#2979 chore(resolver): notice copy update
  apps/wallet-mobile/src/features/Send/common/strings.ts
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/NotifySupportedNameServers/NotifySupportedNameServers.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Send/common/strings.json
  packages/resolver/src/translators/constants.ts
Labels: chore

#2965 fix(collateral): Add collateral UX improvements
  apps/wallet-mobile/src/components/ConfirmTxWithSpendingPasswordModal/ConfirmTxWithSpendingPasswordModal.stories.tsx
  apps/wallet-mobile/src/components/ConfirmTxWithSpendingPasswordModal/ConfirmTxWithSpendingPasswordModal.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.stories.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/helpers.ts
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithOs.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmWithSpendingPassword/ConfirmWithSpendingPassword.tsx
  apps/wallet-mobile/src/features/Swap/common/errors.ts
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/i18n/global-messages.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/api.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/errors.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
  apps/wallet-mobile/translations/messages/src/i18n/global-messages.json
Labels: refactor

#2981 fix: amount item alignment when there is paired balance
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/translations/messages/src/components/PairedBalance/PairedBalance.json
Labels: fix

#2982 feat(governance): Add learn more link
  apps/wallet-mobile/src/features/Staking/Governance/common/LearnMoreLink/LearnMoreLink.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/components/PairedBalance/PairedBalance.json
Labels: feature

#2984 fix(resolver): copy and bug
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/InputReceiver.tsx
  packages/resolver/src/translators/constants.ts
Labels: fix

#2985 feature(resolver): wallet-specific notice
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
Labels: feature

#2987 fix(send): readonly wallet receive button
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
Labels: fix

#2991 fix(swap): add specific order type on summary
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
Labels: fix

#2992 fix(history): Min-ada + section 1st row
  apps/wallet-mobile/src/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryList/TxHistoryList.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistory.json
Labels: fix

#2983 feat(theme): Add package structure
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/src/features/RampOnOff/RampOnOffNavigator.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ButtonActionGroup/ButtonActionGroup.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerBig.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerSmall.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/CreateExchange.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/ShowDisclaimer/ShowDisclaimer.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/ShowProviderFee/ShowProviderFee.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/ShowProviderInfo/ShowProviderInfo.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/ShowExchangeResult/ContentResult/ContentResult.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/ShowExchangeResult/ShowExchangeResult.tsx
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/common/ButtonGroup/ButtonGroup.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithHW.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithOs.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmWithSpendingPassword/ConfirmWithSpendingPassword.tsx
  apps/wallet-mobile/src/features/Swap/common/Counter/Counter.tsx
  apps/wallet-mobile/src/features/Swap/common/LiquidityPool/LiquidityPool.tsx
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnPriceImpact/WarnPriceImpact.tsx
  apps/wallet-mobile/src/theme/index.ts
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
  metro.config.js
  packages/theme/.dependency-cruiser.js
  packages/theme/.gitignore
  packages/theme/babel.config.js
  packages/theme/jest.setup.ts
  packages/theme/package.json
  packages/theme/src/Palette.stories.tsx
  packages/theme/src/Theme.stories.tsx
  packages/theme/src/ThemeProvider.tsx
  packages/theme/src/Typography.stories.tsx
  packages/theme/src/colors/index.ts
  packages/theme/src/darkTheme.ts
  packages/theme/src/index.ts
  packages/theme/src/lightTheme.ts
  packages/theme/src/palettes/darkPalette.ts
  packages/theme/src/palettes/index.ts
  packages/theme/src/palettes/lightPalette.ts
  packages/theme/src/spacing.ts
  packages/theme/src/types.ts
  packages/theme/src/typography.ts
  packages/theme/tsconfig.build.json
  packages/theme/tsconfig.json
  scripts/install-pkgs.sh
  yarn.lock
  yoroi.code-workspace
Labels: feature, chore

#2986 fix: Show loading on multiple Send attempts
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
Labels: fix

#2988 fix(resolver): multiresolution autoselection
  apps/wallet-mobile/src/features/Send/common/SendContext.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/NotifySupportedNameServers/NotifySupportedNameServers.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/SelectNameServer/SelectNameServer.tsx
  packages/resolver/src/translators/constants.ts
Labels: fix

#2989 feat(collateral): Swap collateral text and flow changes
  apps/wallet-mobile/src/components/Icon/Collateral.tsx
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/helpers.ts
  apps/wallet-mobile/src/features/Settings/WalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/features/Swap/common/navigation.ts
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ShowSubmittedTxScreen/ShowSubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/WalletSettings/WalletSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: feature

#2978 fix(resolver): display domains as NFT
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/api.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/assetSuply.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/assetSupply.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/metadata.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/metadata.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/utils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/utils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/nfts.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/nfts.ts
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
  packages/resolver/src/adapters/handle/api.ts
  packages/resolver/src/index.ts
  packages/resolver/src/translators/domainNormalizer.test.ts
  packages/resolver/src/translators/domainNormalizer.ts
  packages/resolver/src/translators/handle/adaHandleDomainNormalizer.test.ts
  packages/resolver/src/translators/handle/adaHandleDomainNormalizer.ts
  yarn.lock
Labels: fix

#2994 fix(resolver): Function definition order
  apps/wallet-mobile/package.json
  packages/resolver/package.json
  packages/resolver/src/adapters/storage.mocks.ts
Labels: fix

#2997 fix(send): confirm tx screen
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/PrimaryTotal.tsx
Labels: fix

#2996 theme(fix): add themeManager with production flag
  packages/theme/src/ThemeProvider.tsx
Labels: fix

#2998 fix:(banxa): Add new variant to feedback screen
  apps/wallet-mobile/src/features/RampOnOff/RampOnOffNavigator.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/ShowExchangeResult/ShowExchangeResult.stories.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/ShowExchangeResult/ShowExchangeResult.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
Labels: fix, blocked

#3003 fix(swap): removed price impact on limit orders
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/CreateOrder.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPrice/EditPrice.tsx
Labels: fix

#3001 chore: New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#3004 feature(resolver): multiresolution new features
  apps/wallet-mobile/src/features/Send/common/ButtonGroup/ButtonGroup.tsx
  apps/wallet-mobile/src/features/Send/common/SendContext.tsx
  apps/wallet-mobile/src/features/Send/common/strings.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/SelectNameServer/SelectNameServer.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Send/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/StartMultiTokenTx/SelectNameServer/SelectNameServer.json
Labels: feature

#3005 chore: New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#3006 chore: New Crowdin updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#3010 feature(resolver): Add csl scoping
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/InputReceiver.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ShowResolvedAddressSelected.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/NotifySupportedNameServers/NotifySupportedNameServers.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/SelectNameServer/SelectNameServer.stories.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  packages/resolver/package.json
  packages/resolver/src/adapters/api.test.ts
  packages/resolver/src/adapters/api.ts
  packages/resolver/src/adapters/cns/api.test.ts
  packages/resolver/src/adapters/cns/api.ts
Labels: feature

#3012 feat(cdn): Restrict native asset sizes
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: feature

#3014 fix(nft): metadata display
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/metadata.ts
Labels: fix

#3016 fix(cdn): Refix the loading retries
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: fix

#3019 fix(resolver): cns error handling
  packages/resolver/src/adapters/cns/api.ts
  packages/resolver/src/translators/reactjs/hooks/useResolverShowNotice.test.tsx
Labels: fix

#3018 fix(cdn): Remove base64 support
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: fix

#3020 release(resolver): v2.0.1
  apps/wallet-mobile/package.json
  packages/resolver/package.json
Labels: release

#3021 fix(resolver): error handling
  packages/resolver/src/adapters/cns/cardano-api-maker.test.ts
  packages/resolver/src/adapters/cns/cardano-api-maker.ts
Labels: fix

#3022 release(resolver): v2.0.2
  apps/wallet-mobile/package.json
  packages/resolver/package.json
Labels: release

#3023 chore(resolver): update readme
  packages/resolver/README.md
Labels: chore

#3025 fix: Paint header blue for txHistory screen
  apps/wallet-mobile/src/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/components/StatusBar.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistory.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
Labels: fix

#3026 fix(resolver): update unstoppable supported tlds and manage errors
  packages/common/src/api/fetchData.ts
  packages/common/src/api/handleApiError.test.ts
  packages/resolver/src/adapters/handle/api.test.ts
  packages/resolver/src/adapters/unstoppable/api.test.ts
  packages/resolver/src/adapters/unstoppable/api.ts
  packages/resolver/src/utils/isResolvableDomain.test.ts
  packages/types/src/api/response.ts
Labels: fix

#3030 chore: releases
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/common/package.json
  packages/links/package.json
  packages/resolver/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/types/package.json
Labels: release

#3033 fix: txHistory header color scope
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
Labels: fix

#3032 fix(theme): display toggle in dev mode only
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/translations/messages/src/Receive/AddressDetail.json
Labels: fix

#3034 fix(resolver): show error when the domain has not a cardano address
  apps/wallet-mobile/src/features/Send/common/strings.tsx
  apps/wallet-mobile/src/features/Send/common/useSendReceiver.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Send/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
  packages/resolver/src/adapters/unstoppable/api.test.ts
  packages/resolver/src/adapters/unstoppable/api.ts
  packages/types/src/index.ts
  packages/types/src/resolver/errors.ts
Labels: fix

#3036 feature(workspace): relative path suggestion
  yoroi.code-workspace
Labels: feature

#3037 fix(resolver): wrong blockchain error
  packages/resolver/src/adapters/unstoppable/api.test.ts
  packages/resolver/src/adapters/unstoppable/api.ts
  packages/resolver/src/utils/isResolvableDomain.test.ts
Labels: fix

#3038 fix(status-bar): Change status bar color on screen focus
  apps/wallet-mobile/src/Nfts/Nfts.tsx
  apps/wallet-mobile/src/components/StatusBar.tsx
  apps/wallet-mobile/translations/messages/src/Nfts/Nfts.json
Labels: fix

#3042 fix: remove unused keyboard spacer
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/ConfirmTxScreen.tsx
Labels: fix

#3043 fix(ramp-on-off): minors
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerBig.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerSmall.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/useStrings.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/RampOnOff/common/useStrings.json
Labels: fix

#3046 fix(ui): Multiple issues
  apps/wallet-mobile/src/components/Button/Button.tsx
  apps/wallet-mobile/src/features/Swap/common/LiquidityPool/LiquidityPool.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPrice/ShowPriceImpact.tsx
Labels: fix

#3049 chore: releases
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/common/package.json
  packages/links/package.json
  packages/resolver/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/types/package.json
Labels: release

#3050 refactor(api): Use hex format to check for asset supply
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/metadata.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/metadata.ts
  packages/api/src/cardano/api/token-supply.test.ts
  packages/api/src/cardano/api/token-supply.ts
Labels: refactor

#3054 fix: uat
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerSmall.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
Labels: fix

#3052 fix: Only add event listeners once
  apps/wallet-mobile/src/TxHistory/useAnimatedTxHistory.ts
Labels: fix

#3053 fix: Different price impact description for moderate and high
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnPriceImpact/WarnPriceImpact.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: fix

#3055 fix: Hide wallet names too long
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/navigation.tsx
Labels: fix

#3057 fix: Many UAT reports
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/InputReceiver.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/EditSlippage.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/WarnPriceImpact/WarnPriceImpact.tsx
Labels: fix

#3058 fix(wallet): Fix recovery phrase spacing and wrapping
  apps/wallet-mobile/src/WalletInit/MnemonicCheck/MnemonicCheckScreen.tsx
  apps/wallet-mobile/translations/messages/src/WalletInit/MnemonicCheck/MnemonicCheckScreen.json
Labels: fix

#3063 fix(send): tx details styles
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/ReceiverInfo.tsx
Labels: fix

#3059 fix(resolver): input loading animation
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/Loading/Loading.stories.tsx
  apps/wallet-mobile/src/components/Loading/Loading.tsx
Labels: feature

#3065 fix(governance): Use error boundaries when creating governance tx
  apps/wallet-mobile/src/components/ConfirmTxWithOsModal/ConfirmTxWithOsModal.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ChangeVote/ChangeVoteScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: fix
