Repository Emurgo/yoroi, pull requests merged in 2024-02, with the labels that each got.

#3066 fix(swap): remove price impact warning from min received field
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
Labels: fix

#3068 feature(metrics): create / restore wallet funnel
  apps/wallet-mobile/src/WalletInit/MnemonicCheck/MnemonicCheckScreen.tsx
  apps/wallet-mobile/src/WalletInit/SaveNanoX/SaveNanoXScreen.tsx
  apps/wallet-mobile/src/WalletInit/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.tsx
  apps/wallet-mobile/src/WalletInit/WalletCredentials/WalletCredentialsScreen.tsx
  apps/wallet-mobile/src/metrics/ampli/index.ts
  apps/wallet-mobile/src/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/metrics/metricsManager.tsx
  apps/wallet-mobile/src/metrics/mocks.ts
  apps/wallet-mobile/translations/messages/src/WalletInit/MnemonicCheck/MnemonicCheckScreen.json
  apps/wallet-mobile/translations/messages/src/WalletInit/SaveNanoX/SaveNanoXScreen.json
  apps/wallet-mobile/translations/messages/src/WalletInit/SaveReadOnlyWallet/SaveReadOnlyWalletScreen.json
Labels: feature

#3067 fix(governance): Fix DRep ID input spacings
  apps/wallet-mobile/src/features/Staking/Governance/useCases/EnterDrepIdModal/EnterDrepIdModal.tsx
Labels: fix

#3069 fix(send): receiver form autoscroll
  apps/wallet-mobile/src/components/ScrollView/ScrollView.tsx
Labels: fix

#3015 feat(ramp on/off): add support for dark theme and typography
  apps/wallet-mobile/src/Dashboard/DashboardNavigator.tsx
  apps/wallet-mobile/src/NftDetails/NftDetailsNavigator.tsx
  apps/wallet-mobile/src/Nfts/NftsNavigator.tsx
  apps/wallet-mobile/src/Search/SearchContext.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/components/StatusBar.tsx
  apps/wallet-mobile/src/features/Initialization/InitializationNavigator.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/RampOnOff/RampOnOffNavigator.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/AmountCard/AmountCard.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ButtonActionGroup/ButtonActionGroup.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerBig.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/ShowDisclaimer/ShowDisclaimer.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/ShowProviderFee/ShowProviderFee.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/ShowProviderInfo/ShowProviderInfo.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/ShowExchangeResult/ContentResult/ContentResult.stories.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/ShowExchangeResult/ShowExchangeResult.tsx
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/Staking/Governance/GovernanceNavigator.tsx
  apps/wallet-mobile/src/features/ToggleAnalyticsSettings/ToggleAnalyticsSettingsNavigator.tsx
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/Dashboard/DashboardNavigator.json
  apps/wallet-mobile/translations/messages/src/NftDetails/NftDetailsNavigator.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
  apps/wallet-mobile/translations/messages/src/features/ToggleAnalyticsSettings/ToggleAnalyticsSettingsNavigator.json
  packages/theme/src/palettes/darkPalette.ts
  packages/theme/src/palettes/lightPalette.ts
  packages/theme/src/typography.ts
Labels: feature

#3070 refactor(swap): move @yoroi/openswap to @yoroi/swap
  metro.config.js
  package.json
  packages/openswap/.dependency-cruiser.js
  packages/openswap/.gitignore
  packages/openswap/package.json
  packages/openswap/scripts/flowgen.sh
  packages/openswap/src/api.ts
  packages/openswap/src/index.ts
  packages/openswap/tsconfig.json
  packages/swap/package.json
  packages/swap/src/adapters/api-maker.test.ts
  packages/swap/src/adapters/api-maker.ts
  packages/swap/src/adapters/openswap-api/api.test.ts
  packages/swap/src/adapters/openswap-api/api.ts
  packages/swap/src/adapters/openswap-api/config.ts
  packages/swap/src/adapters/openswap-api/openswap.mocks.ts
  packages/swap/src/adapters/openswap-api/orders.test.ts
  packages/swap/src/adapters/openswap-api/orders.ts
  packages/swap/src/adapters/openswap-api/pools.test.ts
  packages/swap/src/adapters/openswap-api/pools.ts
  packages/swap/src/adapters/openswap-api/price.test.ts
  packages/swap/src/adapters/openswap-api/price.ts
  packages/swap/src/adapters/openswap-api/token-pairs.test.ts
  packages/swap/src/adapters/openswap-api/token-pairs.ts
  packages/swap/src/adapters/openswap-api/tokens.test.ts
  packages/swap/src/adapters/openswap-api/tokens.ts
  packages/swap/src/adapters/openswap-api/types.ts
  packages/swap/src/helpers/transformers.test.ts
  packages/swap/src/helpers/transformers.ts
  packages/swap/src/index.ts
  scripts/install-pkgs.sh
  yarn.lock
  yoroi.code-workspace
Labels: refactor

#3072 fix(UI): pool select border
  apps/wallet-mobile/src/features/Swap/common/SelectPool/SelectPoolFromList/SelectPoolFromList.tsx
Labels: fix

#3071 fixes(release 4.25.0)
  apps/wallet-mobile/src/components/Warning/Warning.tsx
  apps/wallet-mobile/src/components/Warning/index.ts
  apps/wallet-mobile/src/features/RampOnOff/common/RampOnOffProvider.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/useStrings.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/CreateExchange.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/SelectNameServer/SelectNameServer.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/RampOnOff/common/useStrings.json
Labels: chore

#3074 fix(nft): iOS error image flickering
  apps/wallet-mobile/src/components/NftPreview/NftPreview.tsx
Labels: in-clarification, fix

#3080 fix(uat): minor styling issues
  apps/wallet-mobile/src/components/Button/Button.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerBig.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/theme/config.ts
Labels: fix

#3081 fix(swap): change text color and alignment
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
Labels: fix

#3076 feature(transfer): package creation
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/TxHistory/TxHistory.stories.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Scan/common/useTriggerScanAction.tsx
  apps/wallet-mobile/src/features/Send/common/SendContext.test.tsx
  apps/wallet-mobile/src/features/Send/common/SendContext.tsx
  apps/wallet-mobile/src/features/Send/common/mocks.ts
  apps/wallet-mobile/src/features/Send/common/useSelectedSecondaryAmountsCounter.tsx
  apps/wallet-mobile/src/features/Send/common/useSendAddress.tsx
  apps/wallet-mobile/src/features/Send/common/useSendReceiver.tsx
  apps/wallet-mobile/src/features/Send/common/useTokenQuantities.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/InputReceiver.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ShowResolvedAddressSelected.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ShowResolvedAddressSelected.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/NotifySupportedNameServers/NotifySupportedNameServers.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/SelectNameServer/SelectNameServer.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/SelectNameServer/SelectNameServer.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/ConfirmTxScreen.stories.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.stories.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Receive/common/useStrings.json
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
  metro.config.js
  packages/transfer/.dependency-cruiser.js
  packages/transfer/.gitignore
  packages/transfer/.watchmanconfig
  packages/transfer/README.md
  packages/transfer/babel.config.js
  packages/transfer/jest.setup.js
  packages/transfer/package.json
  packages/transfer/scripts/flowgen.sh
  packages/transfer/src/helpers/mocks.ts
  packages/transfer/src/index.ts
  packages/transfer/src/translators/reactjs/hooks/useTransfer.tsx
  packages/transfer/src/translators/reactjs/provider/TransferProvider.test.tsx
  packages/transfer/src/translators/reactjs/provider/TransferProvider.tsx
  packages/transfer/src/translators/reactjs/state/state.test.ts
  packages/transfer/src/translators/reactjs/state/state.ts
  packages/transfer/tsconfig.build.json
  packages/transfer/tsconfig.json
  packages/types/src/chain/cardano.ts
  packages/types/src/index.ts
  packages/types/src/transfer/state.ts
  scripts/install-pkgs.sh
  yoroi.code-workspace
Labels: feature

#3084 fix(swap): price impact icon
  apps/wallet-mobile/src/components/Icon/Warning.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPrice/ShowPriceImpact.tsx
Labels: fix

#3085 fix(metrics): send tx confirm screeen viewed
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
Labels: fix

#3087 fix(uat): minors styling issues
  apps/wallet-mobile/src/components/ExpandableInfoCard/ExpandableInfoCard.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
Labels: fix

#3090 chore(wallet-mobile): Translation updates
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#3092 refactor(wallet-mobile): Receive funnel fixes and refactor
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Receive/common/AddressDetailCard/AddressDetailCard.stories.tsx
  apps/wallet-mobile/src/features/Receive/common/AddressDetailCard/AddressDetailCard.tsx
  apps/wallet-mobile/src/features/Receive/common/CaptureShareQRCodeCard/CaptureShareQRCodeCard.tsx
  apps/wallet-mobile/src/features/Receive/common/ReceiveProvider.tsx
  apps/wallet-mobile/src/features/Receive/common/ShareDetailsCard/ShareDetailsCard.stories.tsx
  apps/wallet-mobile/src/features/Receive/common/ShareDetailsCard/ShareDetailsCard.tsx
  apps/wallet-mobile/src/features/Receive/common/ShareQRCodeCard/ShareQRCodeCard.stories.tsx
  apps/wallet-mobile/src/features/Receive/common/ShareQRCodeCard/ShareQRCodeCard.tsx
  apps/wallet-mobile/src/features/Receive/common/ShowAddressLimitInfo/ShowAddressLimitInfo.tsx
  apps/wallet-mobile/src/features/Receive/common/multipleAddressesModal.tsx
  apps/wallet-mobile/src/features/Receive/common/useAddressDerivationManager.tsx
  apps/wallet-mobile/src/features/Receive/common/useAddresses.tsx
  apps/wallet-mobile/src/features/Receive/common/useMultipleAddressesInfo.tsx
  apps/wallet-mobile/src/features/Receive/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Receive/common/useReceiveAddressesStatus.tsx
  apps/wallet-mobile/src/features/Receive/useCases/DescribeSelectedAddressScreen.tsx
  apps/wallet-mobile/src/features/Receive/useCases/ListMultipleAddressesScreen.tsx
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
  apps/wallet-mobile/src/features/Settings/MultipleAddresses/MultipleAddresses.tsx
  apps/wallet-mobile/src/features/Settings/WalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/WalletSettings/WalletSettingsScreen.json
  packages/transfer/src/translators/reactjs/state/state.ts
Labels: refactor

#3091 feature(wallet-mobile): add theme support for settings & collateral funnels
  apps/wallet-mobile/src/features/Settings/About/About.tsx
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/features/Settings/ChangeLanguage/ChangeLanguageScreen.tsx
  apps/wallet-mobile/src/features/Settings/ChangePassword/ChangePasswordScreen.tsx
  apps/wallet-mobile/src/features/Settings/ChangeWalletName/ChangeWalletName.tsx
  apps/wallet-mobile/src/features/Settings/Currency/ChangeCurrencyScreen.tsx
  apps/wallet-mobile/src/features/Settings/Currency/CurrencyPickerItem.tsx
  apps/wallet-mobile/src/features/Settings/EasyConfirmation/DisableEasyConfirmationScreen.tsx
  apps/wallet-mobile/src/features/Settings/EasyConfirmation/EnableEasyConfirmationScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/SubmittedTx/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/CurrentBalance.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/PrimaryTotal.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ConfirmTx/Summary/SecondaryTotals.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/src/features/Settings/PrivacyPolicy/PrivacyPolicyScreen.tsx
  apps/wallet-mobile/src/features/Settings/RemoveWallet/RemoveWalletScreen.tsx
  apps/wallet-mobile/src/features/Settings/SettingsItems.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/Settings/TermsOfService/TermsOfServiceScreen.tsx
  apps/wallet-mobile/src/features/Settings/WalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/About/About.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ChangePassword/ChangePasswordScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ChangeWalletName/ChangeWalletName.json
  apps/wallet-mobile/translations/messages/src/features/Settings/EasyConfirmation/DisableEasyConfirmationScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/EasyConfirmation/EnableEasyConfirmationScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/RemoveWallet/RemoveWalletScreen.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/WalletSettings/WalletSettingsScreen.json
Labels: feature

#3094 fix(wallet-mobile): Design issues
  apps/wallet-mobile/src/NftDetails/NftDetails.tsx
  apps/wallet-mobile/src/Nfts/Nfts.tsx
  apps/wallet-mobile/src/Nfts/NoNftsScreen.tsx
  apps/wallet-mobile/src/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/components/Analytics/Analytics.tsx
  apps/wallet-mobile/src/components/Tabs/Tabs.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  apps/wallet-mobile/src/metrics/metrics.stories.tsx
  apps/wallet-mobile/translations/messages/src/NftDetails/NftDetails.json
  apps/wallet-mobile/translations/messages/src/Nfts/Nfts.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistory.json
  apps/wallet-mobile/translations/messages/src/components/Analytics/Analytics.json
  packages/theme/src/typography.ts
Labels: fix

#3093 feature(exchange): package creation and banxa package migration
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/RampOnOff/common/DescribeAction/DescribeAction.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/RampOnOffProvider.tsx
  apps/wallet-mobile/src/features/RampOnOff/useCases/CreateExchange/CreateExchange.tsx
  metro.config.js
  packages/exchange/.dependency-cruiser.js
  packages/exchange/.gitignore
  packages/exchange/.watchmanconfig
  packages/exchange/README.md
  packages/exchange/babel.config.js
  packages/exchange/jest.setup.js
  packages/exchange/package.json
  packages/exchange/scripts/flowgen.sh
  packages/exchange/src/adapters/banxa/errors.ts
  packages/exchange/src/adapters/banxa/zod-errors.test.ts
  packages/exchange/src/adapters/banxa/zod-schema.ts
  packages/exchange/src/adapters/zod-errors.ts
  packages/exchange/src/helpers/banxa/blockchain-code.test.ts
  packages/exchange/src/helpers/banxa/blockchain-code.ts
  packages/exchange/src/helpers/banxa/coin-types.test.ts
  packages/exchange/src/helpers/banxa/coin-types.ts
  packages/exchange/src/helpers/banxa/fiat-types.test.ts
  packages/exchange/src/helpers/banxa/fiat-types.ts
  packages/exchange/src/helpers/banxa/order-types.test.ts
  packages/exchange/src/helpers/banxa/order-types.ts
  packages/exchange/src/helpers/banxa/theme.test.ts
  packages/exchange/src/helpers/banxa/theme.ts
  packages/exchange/src/helpers/banxa/wallet-address.test.ts
  packages/exchange/src/helpers/banxa/wallet-address.ts
  packages/exchange/src/index.ts
  packages/exchange/src/translators/banxa/domains.ts
  packages/exchange/src/translators/banxa/module.test.ts
  packages/exchange/src/translators/banxa/module.ts
  packages/exchange/tsconfig.build.json
  packages/exchange/tsconfig.json
  scripts/install-pkgs.sh
  yoroi.code-workspace
Labels: refactor

#3095 feature(metrics): receive funnel revamp
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/features/Receive/common/ShareDetailsCard/ShareDetailsCard.tsx
  apps/wallet-mobile/src/features/Receive/common/ShareQRCodeCard/ShareQRCodeCard.tsx
  apps/wallet-mobile/src/features/Receive/useCases/DescribeSelectedAddressScreen.tsx
  apps/wallet-mobile/src/features/Receive/useCases/ListMultipleAddressesScreen.tsx
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
  apps/wallet-mobile/src/metrics/ampli/index.ts
  apps/wallet-mobile/src/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/metrics/metricsManager.tsx
  apps/wallet-mobile/src/metrics/mocks.ts
Labels: feature

#3097 feature(theme): add theme spacing logic/integration
  apps/wallet-mobile/src/components/Analytics/Analytics.tsx
  apps/wallet-mobile/src/components/Space/Space.tsx
  apps/wallet-mobile/src/features/RampOnOff/common/ShowBuyBanner/BuyBannerBig.tsx
  apps/wallet-mobile/translations/messages/src/components/Analytics/Analytics.json
  packages/theme/src/darkTheme.ts
  packages/theme/src/index.ts
  packages/theme/src/lightTheme.ts
  packages/theme/src/spacing.ts
  packages/theme/src/types.ts
Labels: chore
