Repository Emurgo/yoroi, pull requests merged in 2024-05, with the labels that each got.

#3221 fix(wallet setup): create wallet navigation
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/features/Exchange/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/Send/common/navigation.ts
  apps/wallet-mobile/src/features/Swap/common/navigation.ts
  apps/wallet-mobile/src/legacy/DeveloperScreen.tsx
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: fix

#3222 fix(wallet-setup): mnemonic input
  apps/wallet-mobile/src/features/SetupWallet/common/MnemonicInput/MnemonicInput.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
Labels: fix

#3223 fix(setup-wallet): steppers icons
  apps/wallet-mobile/src/features/SetupWallet/common/StepperProgress/Number3.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/StepperProgress/Number4.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/StepperProgress/StepperProgress.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/Check.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/CheckIllustration.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/ChevronRight.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/Number1.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/Number2.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/Number2Empty.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/Number3.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/Number3Empty.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/Number4.tsx
  apps/wallet-mobile/src/features/SetupWallet/illustrations/Number4Empty.tsx
  apps/wallet-mobile/src/features/WalletManager/SelectWalletFromList/WalletListItem.tsx
Labels: fix

#3224 fix(setup wallet): large font size scroll
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/AboutRecoveryPhraseScreen.tsx
Labels: fix

#3226 fix(theme) typo on font family declaration
  packages/theme/src/atoms/atoms.ts
Labels: fix

#3228 fix(wallet-setup): display message for invalid mnemonic
  apps/wallet-mobile/src/features/SetupWallet/common/useStrings.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/common/useStrings.json
Labels: fix

#3232 fix(wallet-mobile): Dependency updates for stake pool delegation
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/Staking/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/PoolTransitionModal.tsx
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransition.tsx
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/features/Receive/common/SingleOrMultipleAddressesModal/SingleOrMultipleAddressesModal.tsx
  apps/wallet-mobile/translations/messages/src/Staking/FailedTx/FailedTxScreen.json
  apps/wallet-mobile/translations/messages/src/Staking/PoolTransition/usePoolTransition.json
  yarn.lock
Labels: dependencies, fix

#3234 fix(setup-wallet): wallet details sticky next button
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
Labels: fix

#3235 fix(setup wallet): add wallet screen back button
  apps/wallet-mobile/src/features/SetupWallet/SetupWalletNavigator.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/ChooseBiometricLogin/ChooseBiometricLoginScreen.tsx
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/SetupWalletNavigator.json
Labels: fix

#3237 refactor(setup-wallet): mnemonic input
  apps/wallet-mobile/src/features/SetupWallet/common/MnemonicInput/MnemonicInput.stories.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/MnemonicInput/MnemonicInput.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
Labels: refactor

#3239 fix(setup-wallet): regression issues
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/SetupWallet/SetupWalletNavigator.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/MnemonicInput.stories.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/MnemonicInput.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/index.ts
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
Labels: fix

#3240 fix(setup-wallet): wallet details form spacing
  apps/wallet-mobile/src/features/SetupWallet/common/useStrings.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/common/useStrings.json
Labels: fix

#3242 fix(setup-wallet): typo
  apps/wallet-mobile/src/features/SetupWallet/common/useStrings.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/common/useStrings.json
Labels: fix

#3245 fix: storybook
  apps/wallet-mobile/.storybook/storybook.requires.js
Labels: fix

#3246 fix(swap): slippage text color
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSlippage/EditSlippageScreen/EditSlippageScreen.tsx
Labels: fix

#3247 fix(setup-wallet): info icon alignment
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/RecoveryPhraseScreen.tsx
Labels: fix

#3249 fix(setup-wallet): mnemonic input cursor and selection colors
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/SetupWallet/common/TextInput/TextInput.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/MnemonicInput.tsx
  yarn.lock
Labels: fix

#3250 fix(setup-wallet): mnemonic input local/selected word inequality on blur
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/MnemonicInput.tsx
Labels: fix

#3251 fix(wallet-mobile): Adds tx history loading while checking for stake pool
  apps/wallet-mobile/src/Staking/PoolTransition/usePoolTransition.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/translations/messages/src/Staking/PoolTransition/usePoolTransition.json
Labels: fix

#3254 fix(stacking): dialog color
  apps/wallet-mobile/src/components/DangerousActionModal/DangerousActionModal.tsx
Labels: fix

#3252 refactor(wallet-mobile): drop old pkgs
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/i18n/LocalizableError.ts
  apps/wallet-mobile/src/legacy/DeveloperScreen.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/errors.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/errors.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/parsing.ts
  yarn.lock
Labels: refactor

#3258 fix(receiver): font size
  apps/wallet-mobile/src/features/Receive/common/ShareDetailsCard/ShareDetailsCard.tsx
  apps/wallet-mobile/src/features/Receive/common/ShareQRCodeCard/ShareQRCodeCard.tsx
  apps/wallet-mobile/src/features/Receive/common/SmallAddressCard/SmallAddressCard.tsx
  apps/wallet-mobile/src/features/Receive/useCases/DescribeSelectedAddressScreen.tsx
  apps/wallet-mobile/src/features/Receive/useCases/ListMultipleAddressesScreen.tsx
Labels: fix

#3259 fix(wallet-mobile): Rename Context to context
  apps/wallet-mobile/src/features/WalletManager/context/SelectedWalletContext.tsx
  apps/wallet-mobile/src/features/WalletManager/context/SelectedWalletMetaContext.tsx
  apps/wallet-mobile/src/features/WalletManager/context/WalletManagerContext.tsx
Labels: fix

#3261 fix(swap): tx confirmation screen item alignment
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/features/Swap/useCases/ConfirmTxScreen/TransactionSummary.tsx
Labels: fix

#3260 fix(wallet-mobile): Fix address normalization
  apps/wallet-mobile/src/features/Send/common/useSendAddress.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/assetUtils/assetUtils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/assetUtils/assetUtils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/getMinAmounts.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/getMinAmounts.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/delegationUtils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utils.ts
Labels: fix

#3265 fix(swap): Round sellInPtTerms, Quantity shouldn't have decimals
  apps/wallet-mobile/package.json
  packages/swap/package.json
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.test.ts
  packages/swap/src/helpers/orders/factories/makeOrderCalculations.ts
Labels: fix

#3264 feature(resolver): preprod support
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  packages/resolver/src/adapters/api.ts
  packages/resolver/src/adapters/cns/api-helpers.ts
  packages/resolver/src/adapters/cns/api.test.ts
  packages/resolver/src/adapters/cns/api.ts
  packages/resolver/src/adapters/handle/api.test.ts
  packages/resolver/src/adapters/handle/api.ts
  packages/resolver/src/translators/handle/adaHandleDomainNormalizer.test.ts
  packages/resolver/src/translators/handle/adaHandleDomainNormalizer.ts
Labels: feature

#3266 fix(wallet-mobile): Change route to staking when dApp explorer is enabled
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
Labels: fix

#3225 feat(dapp-connector): Add CIP-30 support
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/components/Icon/Connection.tsx
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/YoroiApp.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/components/Modal/ModalContext.tsx
  apps/wallet-mobile/src/features/Discover/DiscoverNavigator.tsx
  apps/wallet-mobile/src/features/Discover/common/ConfirmConnectionModal.stories.tsx
  apps/wallet-mobile/src/features/Discover/common/ConfirmConnectionModal.tsx
  apps/wallet-mobile/src/features/Discover/common/helpers.ts
  apps/wallet-mobile/src/features/Discover/common/hooks.tsx
  apps/wallet-mobile/src/features/Discover/common/useDAppsConnected.tsx
  apps/wallet-mobile/src/features/Discover/common/useStrings.tsx
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/BrowserTabBar.tsx
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/WebViewItem.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SearchDappInBrowser/SearchDappInBrowserScreen.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/SelectDappFromListScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/api.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/common/signatureUtils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utxoManager/types.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utxoManager/utxos.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/utxoManager/utxos.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/wrappedCsl.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/translations/messages/src/Dashboard/Dashboard.json
  apps/wallet-mobile/translations/messages/src/features/Discover/common/useStrings.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/WalletForm.json
  packages/dapp-connector/src/connector.js
  packages/dapp-connector/src/dapp-connector.test.ts
  packages/dapp-connector/src/dapp-connector.ts
  packages/dapp-connector/src/index.ts
  packages/dapp-connector/src/resolver.ts
  yarn.lock
Labels: feature

#3271 fix(setup-wallet): dialog spacing
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/RecoveryPhraseScreen.tsx
Labels: fix

#3274 feature(wallet-mobile): NFTs traits
  apps/wallet-mobile/src/features/Portfolio/common/MediaDetails/MediaDetails.tsx
  apps/wallet-mobile/src/kernel/constants.ts
  apps/wallet-mobile/translations/messages/src/features/Portfolio/common/MediaDetails/MediaDetails.json
  packages/portfolio/src/adapters/dullahan-api/api-maker.mocks.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.test.ts
  packages/portfolio/src/adapters/dullahan-api/api-maker.ts
  packages/portfolio/src/adapters/dullahan-api/types.ts
  packages/portfolio/src/adapters/token-traits.mocks.ts
  packages/portfolio/src/adapters/token.mocks.ts
  packages/portfolio/src/balance-manager.test.ts
  packages/portfolio/src/index.ts
  packages/portfolio/src/translators/reactjs/usePortfolioTokenTraits.test.tsx
  packages/portfolio/src/translators/reactjs/usePortfolioTokenTraits.tsx
  packages/portfolio/src/validators/token-traits.test.ts
  packages/portfolio/src/validators/token-traits.ts
  packages/types/src/index.ts
  packages/types/src/portfolio/api.ts
  packages/types/src/portfolio/traits.ts
Labels: chore

#3276 fix(wallet-mobile): open/restore redirect and sync
  apps/wallet-mobile/.env
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/src/features/Exchange/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/SetupWalletNavigator.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/PreparingWallet/PreparingWallet.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/PreparingWalletScreen/PreparingWalletScreen.stories.tsx
  apps/wallet-mobile/src/features/SetupWallet/common/PreparingWalletScreen/PreparingWalletScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/legacy/CheckNanoX/CheckNanoXScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/legacy/ConnectNanoX/ConnectNanoXScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/legacy/ImportReadOnlyWallet/ImportReadOnlyWalletScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/ChooseMnemonicType/ChooseMnemonicTypeScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/ChooseNetwork/ChooseNetworkScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/ChooseSetupType/ChooseSetupTypeScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/AboutRecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/RecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/VerifyRecoveryPhraseScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/wallet-mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  apps/wallet-mobile/src/features/Swap/common/navigation.ts
  apps/wallet-mobile/src/features/WalletManager/common/useLaunchWalletAfterSyncing.tsx
  apps/wallet-mobile/src/features/WalletManager/common/useSyncTemporarilyPaused.tsx
  apps/wallet-mobile/src/features/WalletManager/common/walletManager.ts
  apps/wallet-mobile/src/hooks/useApiDialogs.tsx
  apps/wallet-mobile/src/hooks/useApiErrorResolver.tsx
  apps/wallet-mobile/src/hooks/useApiStringsErrors.tsx
  apps/wallet-mobile/src/kernel/constants.ts
  apps/wallet-mobile/src/kernel/env.ts
  apps/wallet-mobile/src/kernel/logger/hooks/useSetupLogger.tsx
  apps/wallet-mobile/src/kernel/logger/logger.ts
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/legacy/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/SetupWalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/CheckNanoX/CheckNanoXScreen.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/ConnectNanoX/ConnectNanoXScreen.json
  apps/wallet-mobile/translations/messages/src/features/SetupWallet/legacy/ImportReadOnlyWallet/ImportReadOnlyWalletScreen.json
  packages/common/src/utils/arrays.test.ts
  packages/setup-wallet/src/translators/reactjs/provider/SetupWalletProvider.test.tsx
  packages/setup-wallet/src/translators/reactjs/provider/SetupWalletProvider.tsx
  packages/setup-wallet/src/translators/reactjs/state/state.test.ts
  packages/setup-wallet/src/translators/reactjs/state/state.ts
  packages/theme/src/atoms/atoms.ts
Labels: fix

#3273 fix(common): privacy mode
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/components/HideableText/HideableText.tsx
  apps/wallet-mobile/src/components/PairedBalance/PairedBalance.tsx
  apps/wallet-mobile/src/features/Portfolio/common/TokenAmountItem/TokenAmountItem.tsx
  apps/wallet-mobile/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.tsx
  apps/wallet-mobile/src/features/Settings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/src/features/Settings/PrivacyMode/PrivacyMode.tsx
  apps/wallet-mobile/src/legacy/Dashboard/UserSummary.tsx
  apps/wallet-mobile/src/legacy/TxHistory/AssetList/AssetList.tsx
  apps/wallet-mobile/src/legacy/TxHistory/BalanceBanner.tsx
  apps/wallet-mobile/src/legacy/TxHistory/LockedDeposit.tsx
  apps/wallet-mobile/src/legacy/TxHistory/TxDetails/AssetList.tsx
  apps/wallet-mobile/src/legacy/TxHistory/TxDetails/TxDetails.tsx
  apps/wallet-mobile/src/legacy/TxHistory/TxHistoryList/TxHistoryListItem.tsx
  apps/wallet-mobile/translations/messages/src/components/PairedBalance/PairedBalance.json
  apps/wallet-mobile/translations/messages/src/features/Settings/ApplicationSettings/ApplicationSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/UserSummary.json
  apps/wallet-mobile/translations/messages/src/legacy/TxHistory/TxDetails/AssetList.json
  apps/wallet-mobile/translations/messages/src/legacy/TxHistory/TxDetails/TxDetails.json
  apps/wallet-mobile/translations/messages/src/legacy/TxHistory/TxHistoryList/TxHistoryListItem.json
Labels: fix

#3277 feature(links): add nmkr partner support
  apps/wallet-mobile/package.json
  packages/exchange/package.json
  packages/exchange/src/adapters/api.ts
  packages/links/README.md
Labels: feature

#3278 fix(common): privacy mode left overs
  apps/wallet-mobile/src/features/Portfolio/common/TokenAmountItem/TokenAmountItem.tsx
  apps/wallet-mobile/src/legacy/TxHistory/BalanceBanner.tsx
Labels: fix
