Repository Emurgo/yoroi, pull requests merged in 2024-03, with the labels that each got.

#3103 fix: minor styling and copy issues
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditBuyAmount/SelectBuyTokenFromListScreen/SelectBuyTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/CreateOrder/EditSellAmount/SelectSellTokenFromListScreen/SelectSellTokenFromListScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
Labels: fix

#3104 fix(wallet-mobile): yoroi zero mainnet url
  packages/api/src/cardano/api/config.ts
  packages/staking/src/governance/config.ts
Labels: in-clarification, fix

#3107 fix(receive): small screen issues and typo in receive
  apps/wallet-mobile/src/features/Receive/common/SmallAddressCard/SmallAddressCard.tsx
  apps/wallet-mobile/src/features/Receive/common/useStrings.tsx
  apps/wallet-mobile/src/features/Receive/useCases/ListMultipleAddressesScreen.tsx
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
  apps/wallet-mobile/src/features/Settings/WalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Receive/common/useStrings.json
  apps/wallet-mobile/translations/messages/src/features/Settings/WalletSettings/WalletSettingsScreen.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/strings.json
Labels: fix

#3111 fix(wallet-mobile): Adds separator to address list only when it needs scroll
  apps/wallet-mobile/src/features/Receive/useCases/ListMultipleAddressesScreen.tsx
Labels: fix

#3114 fix(wallet-mobile): initial paint of border
  apps/wallet-mobile/src/features/Receive/useCases/ListMultipleAddressesScreen.tsx
Labels: fix

#3112 feature(theme): add theme support for wallet/gallery/send features
  apps/wallet-mobile/.storybook/stories/Button/ExampleButton.js
  apps/wallet-mobile/src/Screen.tsx
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
  apps/wallet-mobile/src/TxHistory/AssetList/ActionsBanner.tsx
  apps/wallet-mobile/src/TxHistory/AssetList/AssetList.tsx
  apps/wallet-mobile/src/TxHistory/AssetList/ChipButton/ChipButton.tsx
  apps/wallet-mobile/src/TxHistory/BalanceBanner.tsx
  apps/wallet-mobile/src/TxHistory/LockedDeposit.tsx
  apps/wallet-mobile/src/TxHistory/ModalInfo/ModalInfo.tsx
  apps/wallet-mobile/src/TxHistory/TxDetails/AssetList.stories.tsx
  apps/wallet-mobile/src/TxHistory/TxDetails/AssetList.tsx
  apps/wallet-mobile/src/TxHistory/TxDetails/AssetListSend.style.ts
  apps/wallet-mobile/src/TxHistory/TxDetails/AssetListTransaction.style.ts
  apps/wallet-mobile/src/TxHistory/TxDetails/Base.style.ts
  apps/wallet-mobile/src/TxHistory/TxDetails/TxDetails.tsx
  apps/wallet-mobile/src/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryList/ActionsBanner/ActionsBanner.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryList/EmptyHistory.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryList/TxHistoryList.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryList/TxHistoryListItem.tsx
  apps/wallet-mobile/src/TxHistory/WarningBanner.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/Send/common/ButtonGroup/ButtonGroup.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/ConfirmTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/FailedTx/FailedTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/SubmittedTx/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/CurrentBalance.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/PrimaryTotal.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/SecondaryTotals.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/AddToken.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/ShowError/NoBalance.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/ShowError/UnableToSpend.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/RemoveAmount.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/InputReceiver.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/InputReceiver/ShowResolvedAddressSelected.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/NotifySupportedNameServers/NotifySupportedNameServers.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/src/navigationOptions.tsx
  apps/wallet-mobile/src/theme/palettes/darkPalette.ts
  apps/wallet-mobile/src/theme/palettes/lightPalette.ts
  apps/wallet-mobile/src/theme/types.ts
  apps/wallet-mobile/translations/messages/src/TxHistory/AssetList/AssetList.json
  apps/wallet-mobile/translations/messages/src/TxHistory/ModalInfo/ModalInfo.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxDetails/AssetList.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxDetails/TxDetails.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryList/TxHistoryListItem.json
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/AddToken/AddToken.json
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
  packages/theme/src/palettes/darkPalette.ts
  packages/theme/src/palettes/lightPalette.ts
  packages/theme/src/types.ts
Labels: feature

#3113 chore: Update packages
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/yoroi-wallets/cardano/assetUtils/assetUtils.test.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/assetUtils/assetUtils.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/constants/common.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/hooks/index.ts
Labels: chore

#3115 fix(swap): Transformers fix for asset ascii name
  apps/wallet-mobile/package.json
  packages/swap/package.json
  packages/swap/src/adapters/openswap-api/api.mocks.ts
  packages/swap/src/adapters/openswap-api/openswap.mocks.ts
  packages/swap/src/helpers/transformers.ts
Labels: fix

#3120 chore: bump csl-mobile-bridge
  apps/wallet-mobile/package.json
  yarn.lock
Labels: chore

#3122 fix(wallet-mobile): Typo in specific amount title
  apps/wallet-mobile/src/features/Receive/common/useStrings.tsx
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Receive/common/useStrings.json
Labels: fix

#3123 fix: Animated tx history
  apps/wallet-mobile/src/TxHistory/useAnimatedTxHistory.ts
Labels: fix

#3125 fix(swap): minor styling and typos issues
  apps/wallet-mobile/src/Search/SearchContext.tsx
  apps/wallet-mobile/src/features/Swap/common/strings.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
Labels: fix

#3124 fix(wallet-mobile): tx history animation initial state
  apps/wallet-mobile/src/TxHistory/useAnimatedTxHistory.ts
Labels: fix

#3132 fix(receive): Add last used date to receive address
  apps/wallet-mobile/src/features/Receive/common/ShareDetailsCard/ShareDetailsCard.tsx
  apps/wallet-mobile/src/features/Receive/common/ShareDetailsCard/useLastDateAddressUsed.ts
  apps/wallet-mobile/src/features/Receive/common/useStrings.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Receive/common/useStrings.json
Labels: fix

#3134 fix(wallet-mobile): menu design and status bar on some screens
  apps/wallet-mobile/src/WalletInit/WalletForm.tsx
  apps/wallet-mobile/src/WalletInit/WalletInit/WalletInitScreen.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/legacy/DeveloperScreen.tsx
  apps/wallet-mobile/translations/messages/src/WalletInit/WalletForm.json
  apps/wallet-mobile/translations/messages/src/WalletInit/WalletInit/WalletInitScreen.json
Labels: fix

#3133 fix(receive): Reduce qr card spacing for small screen
  apps/wallet-mobile/src/features/Receive/common/ShareQRCodeCard/ShareQRCodeCard.tsx
Labels: fix

#3135 fix(wallet-mobile): tx history animation flick
  apps/wallet-mobile/src/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/TxHistory/useAnimatedTxHistory.ts
  apps/wallet-mobile/src/features/Scan/useCases/ScanCodeScreen.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistory.json
Labels: fix

#3138 fix(receive): Adjust date format
  apps/wallet-mobile/src/features/Receive/common/ShareDetailsCard/useLastDateAddressUsed.ts
Labels: fix

#3136 fix(receive): Limit specific amount max
  apps/wallet-mobile/src/features/Receive/useCases/ListMultipleAddressesScreen.tsx
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
Labels: fix

#3137 fix(wallet-mobile): modal double close
  apps/wallet-mobile/src/components/Modal/ModalContext.tsx
Labels: fix

#3118 chore(wallet-mobile): Translations updated
  apps/wallet-mobile/src/i18n/locales/bn-BD.json
  apps/wallet-mobile/src/i18n/locales/cs-CZ.json
  apps/wallet-mobile/src/i18n/locales/de-DE.json
  apps/wallet-mobile/src/i18n/locales/el-GR.json
  apps/wallet-mobile/src/i18n/locales/es-ES.json
  apps/wallet-mobile/src/i18n/locales/fil-PH.json
  apps/wallet-mobile/src/i18n/locales/fr-FR.json
  apps/wallet-mobile/src/i18n/locales/hr-HR.json
  apps/wallet-mobile/src/i18n/locales/hu-HU.json
  apps/wallet-mobile/src/i18n/locales/id-ID.json
  apps/wallet-mobile/src/i18n/locales/it-IT.json
  apps/wallet-mobile/src/i18n/locales/ja-JP.json
  apps/wallet-mobile/src/i18n/locales/ko-KR.json
  apps/wallet-mobile/src/i18n/locales/nl-NL.json
  apps/wallet-mobile/src/i18n/locales/pl-PL.json
  apps/wallet-mobile/src/i18n/locales/pt-BR.json
  apps/wallet-mobile/src/i18n/locales/ru-RU.json
  apps/wallet-mobile/src/i18n/locales/sk-SK.json
  apps/wallet-mobile/src/i18n/locales/sl-SI.json
  apps/wallet-mobile/src/i18n/locales/sv-SE.json
  apps/wallet-mobile/src/i18n/locales/sw-KE.json
  apps/wallet-mobile/src/i18n/locales/tr-TR.json
  apps/wallet-mobile/src/i18n/locales/uk-UA.json
  apps/wallet-mobile/src/i18n/locales/vi-VN.json
  apps/wallet-mobile/src/i18n/locales/zh-Hans.json
  apps/wallet-mobile/src/i18n/locales/zh-Hant.json
Labels: chore

#3141 fix: deps
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/common/package.json
  packages/exchange/src/index.ts
  packages/resolver/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/theme/package.json
  packages/transfer/package.json
  packages/types/package.json
Labels: fix

#3142 fix(exchange): addresses
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
Labels: fix

#3143 fix(swap): undefined ticker
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/OpenOrders.tsx
Labels: fix

#3144 fix(exchange): access token management
  packages/exchange/src/adapters/api.test.ts
  packages/exchange/src/adapters/api.ts
  packages/exchange/src/adapters/zod-schema.ts
  packages/exchange/src/manager.test.tsx
  packages/exchange/src/manager.ts
  packages/types/src/exchange/query-string.ts
Labels: fix

#3146 fix(receive): Receive in readOnly wallet
  apps/wallet-mobile/src/TxHistory/ActionsBanner.tsx
Labels: fix

#3147 feature(types,links): deeplinks
  apps/wallet-mobile/android/app/src/main/AndroidManifest.xml
  apps/wallet-mobile/ios/nightly.entitlements
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/ios/yoroi/AppDelegate.mm
  apps/wallet-mobile/ios/yoroi/yoroi.entitlements
  packages/links/.well-known/apple-app-site-association
  packages/links/.well-known/assetlinks.json
  packages/links/README.md
  packages/links/package.json
  packages/links/src/cardano/constants.ts
  packages/links/src/cardano/module.test.ts
  packages/links/src/cardano/module.ts
  packages/links/src/cardano/types.ts
  packages/links/src/index.ts
  packages/links/src/yoroi/constants.ts
  packages/links/src/yoroi/links-builder.ts
  packages/links/src/yoroi/module.test.ts
  packages/links/src/yoroi/module.ts
  packages/links/src/yoroi/types.ts
  packages/types/src/index.ts
  packages/types/src/links/link.ts
Labels: feature

#3148 fix(wallet-mobile): manifest update path and fix host
  apps/wallet-mobile/android/app/src/main/AndroidManifest.xml
Labels: fix

#3150 chore(links): Updated docs + authorization param
  packages/links/README.md
  packages/links/src/yoroi/links-builder.ts
  packages/links/src/yoroi/module.test.ts
Labels: chore

#3149 fix(exchange): manager link generation
  packages/exchange/src/adapters/base-url-adapter.test.ts
  packages/exchange/src/adapters/base-url-adapter.ts
  packages/exchange/src/manager.test.tsx
  packages/exchange/src/manager.ts
Labels: fix

#3152 chore(yoroi-lib): Update yoroi lib to fix fe fee signature issues
  apps/wallet-mobile/package.json
  packages/swap/package.json
  yarn.lock
Labels: fix

#3153 refactor(CIP-30): Use UTXO index directly instead of parsing
  apps/wallet-mobile/src/yoroi-wallets/cardano/utils.ts
Labels: refactor

#3155 feature(wallet-mobile): Redirect universal & deeplinks
  apps/wallet-mobile/android/app/src/main/AndroidManifest.xml
  apps/wallet-mobile/index.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/IntialLinkManagerProvider.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/src/features/Exchange/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/ShowExchangeResultOrderScreen/ShowExchangeResultOrderScreen.stories.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/ShowExchangeResultOrderScreen/ShowExchangeResultOrderScreen.tsx
  apps/wallet-mobile/src/features/Links/common/constants.ts
  apps/wallet-mobile/src/features/Links/common/useDeepLinkWatcher.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  packages/links/README.md
  packages/links/package.json
  packages/links/src/index.ts
  packages/links/src/translators/reactjs/hooks/useLinks.tsx
  packages/links/src/translators/reactjs/provider/LinksProvider.test.tsx
  packages/links/src/translators/reactjs/provider/LinksProvider.tsx
  packages/links/src/translators/reactjs/state/state.mocks.ts
  packages/links/src/translators/reactjs/state/state.test.ts
  packages/links/src/translators/reactjs/state/state.ts
  packages/links/src/yoroi/constants.ts
  packages/links/src/yoroi/helpers.test.ts
  packages/links/src/yoroi/helpers.ts
  packages/links/src/yoroi/links-builder.ts
  packages/links/src/yoroi/links-parser.test.ts
  packages/links/src/yoroi/links-parser.ts
  packages/links/src/yoroi/module.test.ts
  packages/links/src/yoroi/module.ts
  packages/links/src/yoroi/types.ts
  packages/links/src/yoroi/validators.ts
  packages/theme/src/ThemeProvider.tsx
Labels: feature

#3157 fix(swap): Hide cancelled orders with FE fee from completed orders
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/CompletedOrders.tsx
Labels: fix

#3154 fix(receive): Adds single or multiple modal for receive
  apps/wallet-mobile/src/features/Receive/common/useStrings.tsx
  apps/wallet-mobile/src/features/Receive/useCases/DescribeSelectedAddressScreen.tsx
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Receive/common/useStrings.json
Labels: fix

#3160 feature(links, wallet-mobile): Deeplinks
  .github/actions/wallet-mobile/action.yml
  .tool-versions
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/.tool-versions
  apps/wallet-mobile/scripts/request-ada-with-link-android.sh
  apps/wallet-mobile/scripts/request-ada-with-link-ios.sh
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/SelectedWallet/WalletSelection/WalletSelectionScreen.tsx
  apps/wallet-mobile/src/TxHistory/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/WalletNavigator.tsx
  apps/wallet-mobile/src/components/ConfirmTx/ConfirmTx.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/ShowExchangeResultOrderScreen/ShowExchangeResultOrderScreen.tsx
  apps/wallet-mobile/src/features/Links/common/constants.ts
  apps/wallet-mobile/src/features/Links/common/useDeepLinkWatcher.tsx
  apps/wallet-mobile/src/features/Links/common/useLinksRequestAction.tsx
  apps/wallet-mobile/src/features/Links/common/useLinksRequestRedirect.tsx
  apps/wallet-mobile/src/features/Links/common/useLinksRequestWallet.tsx
  apps/wallet-mobile/src/features/Links/common/useLinksShowActionResult.tsx
  apps/wallet-mobile/src/features/Links/common/useNavigationTo.tsx
  apps/wallet-mobile/src/features/Links/common/useStrings.ts
  apps/wallet-mobile/src/features/Links/useCases/AskToOpenAWalletScreen/AskToOpenAWalletScreen.stories.tsx
  apps/wallet-mobile/src/features/Links/useCases/AskToOpenAWalletScreen/AskToOpenAWalletScreen.tsx
  apps/wallet-mobile/src/features/Links/useCases/AskToRedirect/AskToRedirectScreen.stories.tsx
  apps/wallet-mobile/src/features/Links/useCases/AskToRedirect/AskToRedirectScreen.tsx
  apps/wallet-mobile/src/features/Links/useCases/RequestedAdaPaymentWithLinkScreen/RequestedAdaPaymentWithLink.stories.tsx
  apps/wallet-mobile/src/features/Links/useCases/RequestedAdaPaymentWithLinkScreen/RequestedAdaPaymentWithLinkScreen.tsx
  apps/wallet-mobile/src/features/Links/useCases/RequestedAdaPaymentWithLinkScreen/ShowDisclaimer/ShowDisclaimer.stories.tsx
  apps/wallet-mobile/src/features/Links/useCases/RequestedAdaPaymentWithLinkScreen/ShowDisclaimer/ShowDisclaimer.tsx
  apps/wallet-mobile/src/features/Scan/common/useNavigateTo.tsx
  apps/wallet-mobile/src/features/Scan/common/useTriggerScanAction.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/SubmittedTx/SubmittedTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/Summary/ReceiverInfo.tsx
  apps/wallet-mobile/src/i18n/global-messages.ts
  apps/wallet-mobile/src/i18n/locales/en-US.json
  apps/wallet-mobile/src/navigation.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/SelectedWallet/WalletSelection/WalletSelectionScreen.json
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Links/common/useStrings.json
  apps/wallet-mobile/translations/messages/src/i18n/global-messages.json
  packages/links/README.md
  packages/links/src/yoroi/links-builder.ts
  packages/links/src/yoroi/links-parser.test.ts
  packages/links/src/yoroi/links-parser.ts
  packages/links/src/yoroi/module.test.ts
  packages/links/src/yoroi/module.ts
  packages/links/src/yoroi/transformers.mocks.ts
  packages/links/src/yoroi/transformers.test.ts
  packages/links/src/yoroi/transformers.ts
  packages/links/src/yoroi/types.ts
  packages/links/src/yoroi/validators.ts
  packages/transfer/src/translators/reactjs/provider/TransferProvider.test.tsx
  packages/transfer/src/translators/reactjs/provider/TransferProvider.tsx
  packages/transfer/src/translators/reactjs/state/state.test.ts
  packages/transfer/src/translators/reactjs/state/state.ts
  packages/types/src/exchange/query-string.ts
  scripts/install-dev-pkg.sh
  yarn.lock
Labels: feature

#3163 fix(swap): Hide wrong password message when password changed
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithPassword.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmWithSpendingPassword/ConfirmWithSpendingPassword.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistoryList/EmptyHistory.json
  apps/wallet-mobile/translations/messages/src/WalletNavigator.json
Labels: fix

#3168 fix(receive): Increase modal height
  apps/wallet-mobile/src/features/Receive/useCases/DescribeSelectedAddressScreen.tsx
Labels: fix

#3169 feature(links): return url adapter
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
  apps/wallet-mobile/src/legacy/config.ts
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  packages/links/src/yoroi/constants.ts
  packages/links/src/yoroi/validators.ts
Labels: fix

#3171 chore(wallet-mobile): clean ups
  apps/wallet-mobile/src/components/Modal/ModalContext.tsx
  apps/wallet-mobile/src/features/Links/common/useLinksRequestAction.tsx
  apps/wallet-mobile/src/features/Links/common/useLinksRequestRedirect.tsx
  apps/wallet-mobile/src/features/Links/common/useLinksRequestWallet.tsx
  apps/wallet-mobile/src/features/Receive/useCases/RequestSpecificAmountScreen.tsx
  apps/wallet-mobile/src/metrics/metricsManager.tsx
  apps/wallet-mobile/src/wallet-manager/walletManager.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/api/fetch.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/byron/ByronWallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/hw/hw.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/promise/promise.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/shelley/ShelleyWallet.ts
Labels: chore

#3173 chore: bumped pkgs
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/components/AmountItem/AmountItem.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTx.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithHW.tsx
  apps/wallet-mobile/src/features/Swap/common/LiquidityPool/LiquidityPool.stories.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartSwapScreen/ListOrders/helpers.ts
  packages/api/package.json
  packages/common/package.json
  packages/exchange/package.json
  packages/links/package.json
  packages/resolver/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/theme/package.json
  packages/transfer/package.json
  packages/types/package.json
  packages/types/tsconfig.build.json
  yarn.lock
Labels: chore

#3174 refactor(links,wallet-mobile): links types
  apps/wallet-mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
  apps/wallet-mobile/src/features/Exchange/useCases/ShowExchangeResultOrderScreen/ShowExchangeResultOrderScreen.tsx
  apps/wallet-mobile/src/features/Links/common/constants.ts
  apps/wallet-mobile/src/features/Links/common/logos.ts
  apps/wallet-mobile/src/features/Links/common/trustedApps.ts
  apps/wallet-mobile/src/features/Links/common/useLinksRequestAction.tsx
  apps/wallet-mobile/src/features/Links/common/useLinksRequestRedirect.tsx
  apps/wallet-mobile/src/features/Links/useCases/RequestedAdaPaymentWithLinkScreen/RequestedAdaPaymentWithLinkScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ConfirmTx/SubmittedTx/SubmittedTxScreen.tsx
  apps/wallet-mobile/translations/messages/src/TxHistory/TxHistory.json
  apps/wallet-mobile/translations/messages/src/features/Swap/common/AmountCard/AmountCard.json
  package.json
  packages/exchange/src/adapters/api.ts
  packages/exchange/src/manager.test.tsx
  packages/links/README.md
  packages/links/src/index.ts
  packages/links/src/translators/reactjs/provider/LinksProvider.tsx
  packages/links/src/translators/reactjs/state/state.mocks.ts
  packages/links/src/translators/reactjs/state/state.ts
  packages/links/src/yoroi/links-parser.ts
  packages/links/src/yoroi/module.test.ts
  packages/links/src/yoroi/module.ts
  packages/links/src/yoroi/transformers.mocks.ts
  packages/links/src/yoroi/types.ts
  packages/links/src/yoroi/validators.ts
  packages/transfer/src/helpers/mocks.ts
  packages/transfer/src/translators/reactjs/provider/TransferProvider.test.tsx
  packages/transfer/src/translators/reactjs/provider/TransferProvider.tsx
  packages/transfer/src/translators/reactjs/state/state.test.ts
  packages/transfer/src/translators/reactjs/state/state.ts
  packages/types/src/exchange/provider.ts
  packages/types/src/index.ts
  packages/types/src/links/cardano.ts
  packages/types/src/links/yoroi.ts
Labels: chore
