Repository Emurgo/yoroi, pull requests merged in 2025-04, with the labels that each got.

#3891 chore(wallet-mobile): Refactor wallet transactions getters
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
Labels: chore

#3893 fix(common): fetchData cache
  packages/common/src/api/fetchData.ts
Labels: fix

#3892 feat(wallet-mobile): Add notification center
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/YoroiApp.tsx
  apps/wallet-mobile/src/features/Notifications/common/NotificationPopup.tsx
  apps/wallet-mobile/src/features/Notifications/common/NotificationPopupItem.tsx
  apps/wallet-mobile/src/features/Notifications/common/NotificationStack.tsx
  apps/wallet-mobile/src/features/Notifications/common/SwipeOutWrapper.tsx
  apps/wallet-mobile/src/features/Notifications/common/TransactionReceivedNotification.tsx
  apps/wallet-mobile/src/features/Notifications/common/TransactionReceivedNotificationPopup.tsx
  apps/wallet-mobile/src/features/Notifications/common/YoroiNotificationManager.tsx
  apps/wallet-mobile/src/features/Notifications/common/hooks.ts
  apps/wallet-mobile/src/features/Notifications/common/notification-manager.ts
  apps/wallet-mobile/src/features/Notifications/common/notifications.ts
  apps/wallet-mobile/src/features/Notifications/common/primary-token-price-changed-notification.ts
  apps/wallet-mobile/src/features/Notifications/common/rewards-updated-notification.ts
  apps/wallet-mobile/src/features/Notifications/common/storage.ts
  apps/wallet-mobile/src/features/Notifications/common/transaction-received-notification.ts
  apps/wallet-mobile/src/features/Notifications/common/useStrings.tsx
  apps/wallet-mobile/src/features/Notifications/common/useWalletNotifications.ts
  apps/wallet-mobile/src/features/Notifications/illustrations/EmptyNotifications.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationUIHandler.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationsDevScreen.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/ViewNotificationHistory/ViewNotificationHistoryScreen.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.tsx
  apps/wallet-mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Transactions/common/HeaderRightHistory.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Notifications/common/useStrings.json
  apps/wallet-mobile/translations/messages/src/features/Transactions/TxHistoryNavigator.json
  packages/notifications/src/notification-manager.test.ts
  packages/notifications/src/notification-manager.ts
  packages/theme/src/base-palettes/dark-palette.ts
  packages/theme/src/base-palettes/light-palette.ts
  packages/theme/src/types.ts
  packages/types/src/index.ts
  packages/types/src/notifications/manager.ts
Labels: feature

#3898 fix(wallet-mobile): ReviewTX onConfirm handleError
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useOnConfirm.tsx
Labels: fix

#3899 fix(wallet-mobile): Fix rewards notifications display conditions
  apps/wallet-mobile/src/features/Notifications/common/rewards-updated-notification.ts
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationUIHandler.tsx
Labels: fix

#3895 feature(wallet-mobile): gov status screen updates
  apps/wallet-mobile/src/features/Staking/Governance/common/Action/Action.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
Labels: feature

#3897 feat(wallet-mobile): Add push notifications onboarding modal
  apps/wallet-mobile/src/features/Notifications/common/GetImportantAlertsModal.tsx
  apps/wallet-mobile/src/features/Notifications/common/hooks.ts
  apps/wallet-mobile/src/features/Notifications/common/notification-manager.ts
  apps/wallet-mobile/src/features/Notifications/common/primary-token-price-changed-notification.ts
  apps/wallet-mobile/src/features/Notifications/common/processed-notifications-storage.ts
  apps/wallet-mobile/src/features/Notifications/common/rewards-updated-notification.ts
  apps/wallet-mobile/src/features/Notifications/common/storage.ts
  apps/wallet-mobile/src/features/Notifications/common/transaction-received-notification.ts
  apps/wallet-mobile/src/features/Notifications/common/useStrings.tsx
  apps/wallet-mobile/src/features/Notifications/illustrations/PhoneBell.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Notifications/common/useStrings.json
Labels: feature

#3900 feature(wallet-mobile): update change gov vote screen
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ChangeVote/ChangeVoteScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
Labels: feature

#3904 chore(wallet-mobile): Remove push notifications feature flag
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/features/Transactions/common/HeaderRightHistory.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/kernel/features.ts
Labels: chore

#3907 fix(wallet-mobile): Fix push notification history
  apps/wallet-mobile/src/features/Notifications/common/NotificationPopup.tsx
  apps/wallet-mobile/src/features/Notifications/common/hooks.ts
  apps/wallet-mobile/src/features/Notifications/common/useWalletNotifications.ts
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationUIHandler.tsx
Labels: fix

#3910 chore(notifications): Update README file
  packages/notifications/README.md
Labels: chore

#3906 feat(wallet-mobile): Add new settings page for notifications
  apps/wallet-mobile/src/features/Notifications/common/GetImportantAlertsModal.tsx
  apps/wallet-mobile/src/features/Notifications/common/tools.ts
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageNotifications/ManageNotificationDisplayDuration/ManageNotificationDisplayDurationScreen.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageNotifications/ManageNotificationDisplayDuration/strings.ts
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageNotifications/ManageNotificationSettings/ManageNotificationSettings.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageNotifications/ManageNotificationsNavigator.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageNotifications/useStrings.ts
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeWalletSettings/ManageNotifications/ManageNotificationDisplayDuration/strings.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeWalletSettings/ManageNotifications/ManageNotificationSettings/ManageNotificationSettings.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeWalletSettings/ManageNotifications/useStrings.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.json
Labels: feature

#3913 feat(wallet-mobile): Display description for push notifications in the notification centre
  apps/wallet-mobile/src/features/Notifications/useCases/ViewNotificationHistory/ViewNotificationHistoryScreen.tsx
Labels: feature

#3914 chore(root): added back git wfs
  .github/workflows/pr-author.yml
  .github/workflows/sonarqube.yml
  apps/wallet-mobile/sonar-project.properties
  sonar-project.properties
Labels: chore

#3915 fix(wallet-mobile): Fix notification permission setting
  apps/wallet-mobile/src/features/Notifications/common/tools.ts
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageNotifications/ManageNotificationSettings/ManageNotificationSettings.tsx
Labels: fix

#3916 fix(wallet-mobile): Show Yoroi logo as a notification icon
  apps/wallet-mobile/android/app/src/dev/AndroidManifest.xml
  apps/wallet-mobile/android/app/src/dev/drawable/notification_icon.png
  apps/wallet-mobile/android/app/src/main/AndroidManifest.xml
  apps/wallet-mobile/android/app/src/main/res/drawable/notification_icon.png
  apps/wallet-mobile/android/app/src/nightly/drawable/notification_icon.png
  apps/wallet-mobile/android/app/src/production/drawable/notification_icon.png
Labels: fix

#3918 feat(wallet-mobile): Add notification press action support
  apps/wallet-mobile/src/features/Notifications/common/hooks.ts
  apps/wallet-mobile/src/features/Notifications/common/tools.ts
  apps/wallet-mobile/src/features/Notifications/useCases/ViewNotificationHistory/ViewNotificationHistoryScreen.tsx
Labels: feature

#3927 fix(wallet-mobile): gov copies
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
Labels: fix
