Repository Emurgo/yoroi, pull requests merged in 2025-06, with the labels that each got.

#3951 chore(banners, wallet-mobile): Remove Banners
  .cursor.json
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/features/Banners/common/DelegateToYoroiDRepBanner/DelegateToYoroiDRepBanner.stories.tsx
  apps/wallet-mobile/src/features/Banners/common/DelegateToYoroiDRepBanner/DelegateToYoroiDRepBanner.tsx
  apps/wallet-mobile/src/features/Banners/common/strings.ts
  apps/wallet-mobile/src/features/Banners/illustrations/GovernanceBackground.tsx
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsGovernanceBanner.tsx
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsStakingCenterBanner.tsx
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsTxHistoryBanner.tsx
  apps/wallet-mobile/src/features/Dev/DeveloperScreen.tsx
  apps/wallet-mobile/src/features/Dev/Playground.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  metro.config.js
  packages/banners/.dependency-cruiser.js
  packages/banners/.gitignore
  packages/banners/.watchmanconfig
  packages/banners/README.md
  packages/banners/babel.config.js
  packages/banners/dependency-graph.svg
  packages/banners/jest.setup.js
  packages/banners/package.json
  packages/banners/scripts/flowgen.sh
  packages/banners/src/banners-manager.test.ts
  packages/banners/src/banners-manager.ts
  packages/banners/src/helpers/should-show-drep2us-on-governance.test.ts
  packages/banners/src/helpers/should-show-drep2us-on-governance.ts
  packages/banners/src/helpers/should-show-drep2us-on-staking-center.test.ts
  packages/banners/src/helpers/should-show-drep2us-on-staking-center.ts
  packages/banners/src/helpers/should-show-drep2us-on-tx-history.test.ts
  packages/banners/src/helpers/should-show-drep2us-on-tx-history.ts
  packages/banners/src/index.ts
  packages/banners/src/translators/reactjs/BannersProvider.test.tsx
  packages/banners/src/translators/reactjs/BannersProvider.tsx
  packages/banners/src/translators/reactjs/useBanner.test.ts
  packages/banners/src/translators/reactjs/useBanner.ts
  packages/banners/tsconfig.build.json
  packages/banners/tsconfig.json
  packages/types/src/banners/banners.ts
  packages/types/src/index.ts
  scripts/install-dev-pkg.sh
  scripts/install-pkgs.sh
  yoroi.code-workspace
Labels: chore

#3956 chore(wallet-mobile): drop NFT word
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
Labels: chore

#3952 feature(wallet-mobile): Governance banner notification and refactor
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/BuyBannerBig.stories.tsx
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/BuyBannerBig.tsx
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/BuyBannerSmall.stories.tsx
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/BuyBannerSmall.tsx
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/PreprodFaucetBanner.stories.tsx
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/PreprodFaucetBanner.tsx
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/PreprodFaucetBannerLogo.tsx
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/ShowBuyBanner.stories.tsx
  apps/wallet-mobile/src/features/Exchange/common/ShowBuyBanner/ShowBuyBanner.tsx
  apps/wallet-mobile/src/features/Exchange/common/useBuyCryptoBanner.tsx
  apps/wallet-mobile/src/features/Exchange/common/useResetShowBuyBannerSmall.tsx
  apps/wallet-mobile/src/features/Exchange/common/useShowBuyBannerSmall.tsx
  apps/wallet-mobile/src/features/Notifications/common/NotificationPopup.tsx
  apps/wallet-mobile/src/features/Notifications/common/banners.ts
  apps/wallet-mobile/src/features/Notifications/common/notification-manager.ts
  apps/wallet-mobile/src/features/Notifications/common/show-banners.ts
  apps/wallet-mobile/src/features/Notifications/common/tools.ts
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/BuyADABanner/AssetImage.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioDashboard/DashboardTokensList/BuyADABanner/BuyADABanner.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/useGovernanceBanner.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
  packages/notifications/src/notification-manager.ts
Labels: feature

#3966 fix(wallet-mobile): invalidate banners on utxo change
  apps/wallet-mobile/src/features/Exchange/common/useBuyCryptoBanner.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/useGovernanceBanner.tsx
Labels: fix
