Repository Emurgo/yoroi, pull requests merged in 2025-05, with the labels that each got.

#3928 feature(yoroi-mobile, staking): drep id deprecated format warning
  apps/wallet-mobile/src/components/InfoBanner/InfoBanner.tsx
  apps/wallet-mobile/src/components/Warning/Warning.tsx
  apps/wallet-mobile/src/components/WarningBanner/WarningBanner.tsx
  apps/wallet-mobile/src/features/Banners/common/DelegateToYoroiDRepBanner/DelegateToYoroiDRepBanner.tsx
  apps/wallet-mobile/src/features/Discover/common/ConfirmConnectionModal.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useStrings.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/operations.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Overview/OverviewTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/StartMultiTokenTx/SelectNameServer/SelectNameServer.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/drep.ts
  apps/wallet-mobile/src/features/Staking/Governance/common/helpers.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ChangeVote/ChangeVoteScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/EnterDrepIdModal/EnterDrepIdModal.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.tsx
  apps/wallet-mobile/translations/messages/src/features/ReviewTx/common/hooks/useStrings.json
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/WithdrawStakingRewards/WithdrawStakingRewards.json
  packages/staking/src/governance/helpers/index.ts
  packages/staking/src/governance/helpers/parsing.ts
  packages/staking/src/governance/index.ts
Labels: feature

#3930 fix(wallet-mobile): swap input alignment
  apps/wallet-mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
Labels: fix

#3919 feat(wallet-mobile): Add screen navigation for notification press
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/features/Notifications/common/hooks.ts
  apps/wallet-mobile/src/features/Notifications/common/tools.ts
  apps/wallet-mobile/src/features/Notifications/useCases/ViewNotificationHistory/ViewNotificationHistoryScreen.tsx
  apps/wallet-mobile/src/features/WalletManager/useCases/SelectWalletFromListScreen/SelectWalletFromListScreen.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
Labels: feature

#3934 fix(wallet-mobile): Some fixes
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/ConfirmTx/ConfirmTx.stories.tsx
  apps/wallet-mobile/src/components/ConfirmTx/ConfirmTx.tsx
  apps/wallet-mobile/src/components/ConfirmTx/Dialog.stories.tsx
  apps/wallet-mobile/src/components/ConfirmTx/Dialog.tsx
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/BrowserSearchToolbar.tsx
  apps/wallet-mobile/src/features/Discover/useCases/BrowseDapp/WebViewItem.tsx
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Overview/Overview.tsx
  packages/swap/src/adapters/api/muesliswap/api-maker.test.ts
  packages/swap/src/adapters/api/muesliswap/api-maker.ts
  packages/swap/src/adapters/api/muesliswap/api.mocks.ts
  packages/swap/src/adapters/api/muesliswap/transformers.test.ts
  packages/swap/src/adapters/api/muesliswap/transformers.ts
  packages/swap/src/adapters/api/muesliswap/types.ts
Labels: fix, refactor

#3937 fix dependency
  packages/common/package.json
Labels: fix

#3938 chore(root): Packages were bumped major for new types
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/banners/README.md
  packages/banners/package.json
  packages/blockchains/package.json
  packages/claim/package.json
  packages/common/package.json
  packages/dapp-connector/package.json
  packages/exchange/package.json
  packages/explorers/package.json
  packages/links/package.json
  packages/notifications/package.json
  packages/portfolio/package.json
  packages/resolver/package.json
  packages/setup-wallet/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/theme/package.json
  packages/transfer/package.json
  packages/types/package.json
  yarn.lock
Labels: chore

#3939 fix(wallet-mobile): Update wanted price per protocol changed
  apps/wallet-mobile/src/features/Swap/common/SwapProvider.tsx
  apps/wallet-mobile/src/features/Swap/useCases/CreateOrder/SelectProtocolScreen.tsx
Labels: fix

#3943 chore(theme): moved to expo-gradient theme
  apps/wallet-mobile/__mocks__/expo-linear-gradient.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
  packages/theme/package.json
  packages/theme/src/storybook/BasePalette.tsx
  packages/theme/src/types.ts
  yarn.lock
Labels: chore

#3944 fix(theme): dropped BasePalette from export index
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/Dev/Palettes.stories.tsx
  packages/theme/package.json
  packages/theme/src/index.ts
Labels: fix

#3945 chore(resolver): update handle.me types
  packages/resolver/src/adapters/handle/api.mocks.ts
  packages/resolver/src/adapters/handle/api.ts
Labels: chore
