Repository Emurgo/yoroi, pull requests merged in 2025-09, with the labels that each got.

#4115 Fix/react state update warning
  mobile/src/kernel/query/QueryProvider.tsx
  mobile/src/ui/Boundary/Boundary.tsx
Labels: fix

#4118 Fixes dapp strings, welcome to dapps not saving, markdown loading, canProceed in modals
  mobile/markdown-transformer.js
  mobile/metro.config.js
  mobile/metro.config.nightly.js
  mobile/metro.config.production.js
  mobile/package-lock.json
  mobile/package.json
  mobile/src/features/Discover/common/useShowWelcomeDApp.tsx
  mobile/src/features/Legal/common/loadTextAsset.ts
  mobile/src/features/Legal/ui/Disclaimer/ShowDisclaimer.tsx
  mobile/src/features/Legal/ui/Disclaimer/loadText.ts
  mobile/src/features/Legal/ui/PrivacyPolicy/loadPrivacyPolicy.ts
  mobile/src/features/Legal/ui/TermsOfService/loadTos.ts
  mobile/src/kernel/i18n/messages/discover.ts
  mobile/src/ui/Modal/ModalContext.tsx
Labels: fix

#4125 fix(swap): Add muesliswap partner to limit quote and create
  mobile/packages/swap/adapters/api/muesliswap/api.mocks.ts
  mobile/packages/swap/adapters/api/muesliswap/transformers.ts
  scripts/packages/swap/package.json
Labels: fix

#4126 feat: eas build
  .github/workflows/preview-eas-build.yml
  .github/workflows/production-eas-build.yml
  codecov.yml
  mobile/.env
  mobile/.env.nightly
  mobile/.env.production
  mobile/.env.staging
  mobile/app.config.js
  mobile/app.config.nightly.js
  mobile/app.config.production.js
  mobile/app.json
  mobile/eas.json
  mobile/env.nightly
  mobile/env.production
  mobile/metro.config.nightly.js
  mobile/metro.config.production.js
  mobile/package-lock.json
  mobile/package.json
  mobile/scripts/eas-post-install.sh
  mobile/scripts/eas-pre-install.sh
  mobile/src/kernel/constants.ts
Labels: feature

#4136 fix(mobile): privacy ctrl + style
  mobile/src/ui/BalanceCardContent/BalanceCardContent.tsx
  mobile/src/ui/PairedBalance/PairedBalance.tsx
Labels: fix

#4137 fix(mobile): links providers order
  mobile/App.tsx
  mobile/src/features/Discover/DiscoverNavigator.tsx
Labels: fix

#4145 fix(mobile): swap price warnings and language picker search
  mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
  mobile/src/kernel/i18n/messages/swap.ts
  mobile/src/ui/BalanceCardContent/BalanceCardContent.tsx
  mobile/src/ui/LanguagePicker/LanguagePicker.tsx
  mobile/src/ui/PairedBalance/PairedBalance.tsx
Labels: fix

#4141 fix(mobile): missing send funnel banner
  mobile/src/features/Send/useCases/StartMultiTokenTx/NotifySupportedNameServers/NotifySupportedNameServers.tsx
  mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  mobile/src/kernel/i18n/messages/send.ts
Labels: fix

#4166 fix(mobile): notification empty string
  mobile/src/features/Notifications/common/NotificationPopup.tsx
  mobile/src/features/Notifications/useCases/TransactionReceivedNotificationPopup.tsx
  mobile/src/kernel/i18n/messages/notifications.ts
Labels: fix

#4165 fix(mobile): wallet resync
  mobile/src/features/DevMenu/DevMenu.tsx
  mobile/src/features/Settings/ui/screens/ChangeWalletSettingsScreen/ChangeWalletSettingsScreen.tsx
  mobile/src/features/SetupWallet/common/PreparingWalletScreen/PreparingWalletScreen.tsx
  mobile/src/features/WalletManager/hooks/useResync.ts
  mobile/src/features/WalletManager/wallet-manager.ts
  mobile/src/hooks/usePromise.ts
  mobile/src/wallets/cardano/cardano-wallet.ts
  mobile/src/wallets/cardano/types.ts
Labels: fix

#4168 doc(mobile): Apple encryption compliance
  APPLE_STORE_ENCRYPTION_COMPLIANCE.md
Labels: docs

#4163 feature(mobile): yoroi custom modal
  mobile/PlatformShell.tsx
  mobile/package-lock.json
  mobile/package.json
  mobile/src/features/WalletManager/ui/screens/SelectWalletFromListScreen/SelectWalletFromListScreen.tsx
  mobile/src/ui/Modal/ModalContext.tsx
  mobile/src/ui/Modal/ModalScreen.tsx
Labels: feature

#4176 fix(mobile): walletduplicatedmodal issues
  mobile/src/features/SetupWallet/common/WalletDuplicatedModal/WalletDuplicatedModal.tsx
Labels: fix

#4178 fix(mobile): biometrics initialization screen fixes
  mobile/src/features/Auth/ui/screens/LoginWithHostScreen.tsx
  mobile/src/features/Initialization/ui/screens/ChooseBiometricLoginScreen.tsx
Labels: fix

#4179 Fix labels/copy in Tx History, Send and Settings
  mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  mobile/src/features/Settings/ui/screens/ChangeWalletSettingsScreen/ChangeWalletSettingsScreen.tsx
  mobile/src/kernel/i18n/messages/send.ts
  mobile/src/kernel/i18n/messages/settings.ts
  mobile/src/kernel/i18n/messages/transactions.ts
  mobile/src/kernel/navigation/WalletTabNavigator.tsx
Labels: fix

#4182 refactor(mobile): yoroi custom modal
  mobile/src/features/Claim/useCases/AskConfirmation.tsx
  mobile/src/features/DevMenu/DevMenu.tsx
  mobile/src/features/Discover/common/ConfirmConnectionModal.tsx
  mobile/src/features/Discover/common/UnverifiedDappModal.tsx
  mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
  mobile/src/features/Discover/useCases/SelectDappFromList/WelcomeDAppModal.tsx
  mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
  mobile/src/features/HW/LedgerTransportSwitchModal/LedgerTransportSwitchModal.tsx
  mobile/src/features/Legal/ui/shared/Disclaimer/ShowDisclaimer.tsx
  mobile/src/features/Links/hooks/useLinksRequestAction.tsx
  mobile/src/features/Links/ui/screens/AskToOpenAWalletScreen/AskToOpenAWalletScreen.tsx
  mobile/src/features/Links/ui/screens/AskToRedirect/AskToRedirectScreen.tsx
  mobile/src/features/Links/ui/screens/RequestedAdaPaymentWithLinkScreen/RequestedAdaPaymentWithLinkScreen.tsx
  mobile/src/features/Links/ui/screens/RequestedBrowserLaunchDappUrlScreen/RequestedBrowserLaunchDappUrlScreen.tsx
  mobile/src/features/Notifications/common/GetImportantAlertsModal.tsx
  mobile/src/features/Portfolio/screens/PortfolioTokensList/PortfolioDAppsTokenList/LiquidityPoolModal.tsx
  mobile/src/features/Portfolio/screens/PortfolioTokensList/PortfolioDAppsTokenList/OpenOrderModal.tsx
  mobile/src/features/RegisterCatalyst/common/InsufficientFundsModal.tsx
  mobile/src/features/ReviewTx/common/PoolDetails.tsx
  mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Overview/OverviewTab.tsx
  mobile/src/features/Scan/common/useTriggerScanAction.tsx
  mobile/src/features/Settings/hooks/useOpenNetworkNoticeModal.tsx
  mobile/src/features/Settings/ui/screens/ChangeWalletSettingsScreen/ManageCollateralScreen/CollateralInfoModal.tsx
  mobile/src/features/Settings/ui/screens/ChangeWalletSettingsScreen/ManageCollateralScreen/InitialCollateralInfoModal.tsx
  mobile/src/features/Settings/ui/screens/ChangeWalletSettingsScreen/ManageCollateralScreen/ManageCollateralScreen.tsx
  mobile/src/features/Settings/ui/shared/NetworkTag.tsx
  mobile/src/features/SetupWallet/common/WalletDuplicatedModal/WalletDuplicatedModal.tsx
  mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  mobile/src/features/SetupWallet/useCases/RestoreHwWallet/SaveNanoXScreen.tsx
  mobile/src/features/SetupWallet/useCases/RestoreHwWallet/SelectHwConnectionModal.tsx
  mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  mobile/src/features/Staking/Governance/useCases/EnterDrepIdModal/EnterDrepIdModal.tsx
  mobile/src/features/Staking/Governance/useCases/WithdrawGovernanceWarningModal/WithdrawGovernanceWarningModal.tsx
  mobile/src/features/Staking/Staking/PoolTransition/PoolTransitionModal.tsx
  mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithOs.tsx
  mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithPassword.tsx
  mobile/src/features/Swap/common/ConfirmWithSpendingPassword/ConfirmWithSpendingPassword.tsx
  mobile/src/features/Swap/common/EstimateSummary/EstimateSummary.tsx
  mobile/src/features/Swap/useCases/CreateOrder/SwapMainScreen.tsx
  mobile/src/features/Swap/useCases/ListOrders/ListOrders.tsx
  mobile/src/features/Transactions/useCases/TxDetails/AddressModal/AddressModal.tsx
  mobile/src/features/WalletManager/ui/screens/SelectWalletFromListScreen/SelectWalletFromListScreen.tsx
  mobile/src/ui/ConfirmTxWithHwModal/ConfirmTxWithHwModal.tsx
  mobile/src/ui/ConfirmTxWithOsModal/ConfirmTxWithOsModal.tsx
  mobile/src/ui/ConfirmTxWithSpendingPasswordModal/ConfirmTxWithSpendingPasswordModal.tsx
  mobile/src/ui/Modal/ModalContentWrapper.tsx
  mobile/src/ui/Modal/ModalScreen.tsx
  mobile/src/ui/Modal/hooks.tsx
  mobile/src/ui/ModalError/ModalError.tsx
  mobile/src/ui/SingleOrMultipleAddressesModal/SingleOrMultipleAddressesModal.tsx
  mobile/src/ui/TokenDetails/TokenDetails.tsx
Labels: dont-merge

#4187 fix(modal): modals
  mobile/src/features/Legal/ui/shared/Disclaimer/ShowDisclaimer.tsx
  mobile/src/features/Scan/common/useTriggerScanAction.tsx
  mobile/src/ui/Modal/ModalContentWrapper.tsx
  mobile/src/ui/Modal/ModalContext.tsx
  mobile/src/ui/Modal/ModalScreen.tsx
Labels: fix

#4189 fix(mobile): swap ui fixes
  mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  mobile/src/features/Swap/common/SwapProvider.tsx
  mobile/src/features/Swap/useCases/CreateOrder/LimitInput.tsx
  mobile/src/features/Swap/useCases/CreateOrder/SwapMainScreen.tsx
Labels: fix

#4191 fix(mobile): ui minors
  mobile/src/features/Legal/ui/shared/Analytics/Analytics.tsx
  mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  mobile/src/kernel/i18n/locales/en-US.json
  mobile/src/kernel/i18n/messages/send.ts
  mobile/src/kernel/i18n/useStrings.ts
  mobile/src/kernel/navigation/WalletTabNavigator.tsx
Labels: fix

#4195 refactor(mobile): tx review sync and remove remaining wrappedCsl
  mobile/src/features/ReviewTx/common/hooks/useFormattedMetadata.tsx
  mobile/src/features/ReviewTx/common/hooks/useFormattedTx.tsx
  mobile/src/features/ReviewTx/common/hooks/useTxBody.tsx
  mobile/src/features/ReviewTx/common/operations.tsx
  mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  mobile/src/features/Swap/common/useGetInputs.ts
  mobile/src/features/Transactions/useCases/UtxoList/useUtxoList.ts
  mobile/src/features/WalletManager/wallet-manager.ts
  mobile/src/ui/Divider/Divider.tsx
  mobile/src/wallets/cardano/assetUtils.ts
  mobile/src/wallets/cardano/cardano-wallet.ts
  mobile/src/wallets/cardano/cip30/cip30-ledger.ts
  mobile/src/wallets/cardano/cip8/cip8.test.ts
  mobile/src/wallets/cardano/cip95/cip95.ts
  mobile/src/wallets/cardano/delegationUtils.ts
  mobile/src/wallets/cardano/utils.ts
  mobile/src/wallets/cardano/wrappedCsl.ts
Labels: fix

#4200 feature(mobile): modal queue
  mobile/src/features/DevMenu/DevMenu.tsx
  mobile/src/features/Swap/useCases/ListOrders/ListOrders.tsx
  mobile/src/kernel/constants.ts
  mobile/src/ui/Modal/ModalContext.tsx
Labels: feature

#4204 fix(mobile): preprod tx list crash and staking rewards warning modal
  mobile/src/features/Dashboard/Dashboard.tsx
  mobile/src/features/Staking/Staking/PoolTransition/usePoolTransition.tsx
  mobile/src/features/Staking/hooks/useStakingInfo.ts
Labels: fix

#4209 fix(mobile): fix DApp connection modal flow and clean up disconnected dApp WebViews
  mobile/packages/dapp-connector/connector.js
  mobile/src/features/Discover/common/BrowserProvider.tsx
  mobile/src/features/Discover/common/UnverifiedDappModal.tsx
  mobile/src/features/Discover/common/helpers.ts
  mobile/src/features/Discover/common/hooks.tsx
  mobile/src/features/Discover/common/useConfirmConnection.ts
  mobile/src/features/Discover/common/useDisconnectDapp.ts
  mobile/src/features/Discover/useCases/BrowseDapp/WebViewItem.tsx
  mobile/src/ui/Modal/ModalContext.tsx
Labels: fix

#4212 fix(mobile): ledger connection error handling
  mobile/src/kernel/dialogs.ts
Labels: fix

#4218 fix(mobile): fix pipeline
  .github/workflows/mobile-checks.yml
  .github/workflows/preview-eas-build.yml
  .github/workflows/production-eas-build.yml
Labels: fix

#4221 fix(mobile): fix pipeline drop checks
  .github/workflows/mobile-checks.yml
  .github/workflows/preview-eas-build.yml
  .github/workflows/production-eas-build.yml
Labels: fix

#4223 fix(mobile): fix working dir pip
  .github/workflows/production-eas-build.yml
Labels: fix

#4234 fix(mobile): add catalyst loading to prevent opening the modal before fund data ready
  mobile/src/features/Menu/Menu.tsx
  mobile/src/features/RegisterCatalyst/common/InsufficientFundsModal.tsx
  mobile/src/features/RegisterCatalyst/common/hooks.ts
Labels: fix

#4235 feat: sentry setup autoupload sourcemaps
  mobile/.env
  mobile/.gitignore
  mobile/App.tsx
  mobile/app.json
  mobile/metro.config.js
Labels: feature

#4237 feat: improve sentry logging
  mobile/src/kernel/logger/helpers/init-logger.tsx
Labels: feature

#4240 fix(common, mobile): decimal edge cases
  mobile/packages/common/utils/parse-number-from-text.ts
  mobile/src/features/Swap/common/EstimateSummary/EstimateSummary.tsx
  mobile/src/features/Swap/useCases/CreateOrder/SelectProtocolScreen.tsx
  mobile/src/features/Swap/useCases/ListOrders/ListOrders.tsx
  mobile/src/features/Swap/useCases/ReviewSwap/TransactionSummary.tsx
Labels: fix

#4241 fix(mobile): AmountCard quantity
  mobile/src/features/Swap/common/AmountCard/AmountCard.tsx
  mobile/src/features/Swap/common/EstimateSummary/EstimateSummary.tsx
Labels: fix
