Repository Emurgo/yoroi, pull requests merged in 2025-02, with the labels that each got.

#3807 fix(wallet-mobile): Fix iOS nightly FCM integration
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/ios/nightly.entitlements
  apps/wallet-mobile/ios/nightly.plist
  apps/wallet-mobile/ios/yoroi.xcodeproj/project.pbxproj
  apps/wallet-mobile/ios/yoroi/AppDelegate.mm
Labels: fix

#3808 fix(wallet-mobile): Fix modal prop canDiscard not being used
  apps/wallet-mobile/src/components/Modal/ModalContext.tsx
Labels: fix

#3810 fix(wallet-mobile): Discover apps failing
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/SelectDappFromListScreen.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/WelcomeDAppModal.tsx
Labels: fix

#3809 feat(wallet-mobile): remove trailing zeros from tx list amounts
  apps/wallet-mobile/src/yoroi-wallets/utils/format.test.ts
  apps/wallet-mobile/src/yoroi-wallets/utils/format.ts
  apps/wallet-mobile/translations/messages/src/yoroi-wallets/utils/format.json
Labels: feature

#3811 feature(wallet-mobile): tx review generalize cbor signing
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useLegacyOnConfirm.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useOnConfirm.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTx.stories.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTx.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithHW.tsx
  apps/wallet-mobile/src/features/Swap/common/helpers.ts
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
Labels: feature

#3812 fix(wallet-mobile): modal taps persistence
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
Labels: fix

#3813 fix(wallet-mobile): modal spacing
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/components/ScrollView/ScrollView.tsx
Labels: fix

#3815 fix(wallet-mobile): Fix notification shadow, display time, and order
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationUIHandler.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/NotificationPopup.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/SwipeOutWrapper.tsx
Labels: fix

#3814 fix(wallet-mobile): modal tap persistence
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
Labels: fix

#3816 fix(wallet-mobile): collateral modal update
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageCollateral/InitialCollateralInfoModal.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageCollateral/strings.ts
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeWalletSettings/ManageCollateral/strings.json
Labels: fix

#3820 chore(wallet-mobile): Refactor connected dApps queries
  apps/wallet-mobile/src/features/Discover/common/useConfirmConnection.ts
  apps/wallet-mobile/src/features/Discover/common/useDAppsConnected.tsx
  apps/wallet-mobile/src/features/Discover/common/useDisconnectDapp.ts
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/DAppListItem/DAppListItem.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/SelectDappFromListScreen.tsx
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.tsx
Labels: chore

#3822 fix(wallet-mobile): Display notifications only on incoming TXs confirmed when the app is open
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationsDevScreen.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/transaction-received-notification.ts
Labels: fix

#3824 fix(wallet-mobile): missing ft placeholders
  apps/wallet-mobile/src/assets/img/ft-placeholder-dark.png
  apps/wallet-mobile/src/assets/img/ft-placeholder.png
  apps/wallet-mobile/src/components/MediaPreview/MediaPreview.tsx
Labels: fix

#3818 fix(wallet-mobile): Dapp explorer failing
  apps/wallet-mobile/src/features/Discover/common/useShowWelcomeDApp.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/SelectDappFromListScreen.tsx
  apps/wallet-mobile/src/features/Discover/useCases/SelectDappFromList/WelcomeDAppModal.tsx
  apps/wallet-mobile/src/features/Legal/Disclaimer/ShowDisclaimer.tsx
Labels: fix

#3826 chore(types): Use new @yoroi/types version
  apps/wallet-mobile/package.json
  packages/api/package.json
  packages/claim/package.json
  packages/common/package.json
  packages/dapp-connector/package.json
  packages/exchange/package.json
  packages/explorers/package.json
  packages/links/package.json
  packages/notifications/package.json
  packages/portfolio/package.json
  packages/resolver/package.json
  packages/setup-wallet/package.json
  packages/staking/package.json
  packages/swap/package.json
  packages/theme/package.json
  packages/transfer/package.json
  packages/types/package.json
Labels: chore

#3827 Feature/swap cancellation details
  apps/wallet-mobile/src/features/Swap/useCases/ListOrders/ListOrders.tsx
  packages/types/src/swap/pool.ts
Labels: feature

#3828 fix(wallet-mobile): Do not show notifications on wallet selection screen
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationUIHandler.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
Labels: fix

#3830 fix(wallet-mobile): Operations missing key
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Overview/OverviewTab.tsx
Labels: fix

#3834 fix(wallet-mobile): Disclaimers should not be discardable
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/features/Legal/Disclaimer/ShowDisclaimer.tsx
  apps/wallet-mobile/translations/messages/src/yoroi-wallets/utils/format.json
Labels: fix

#3835 fix(wallet-mobile): Do not display TX received notifications on TX history route
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationUIHandler.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
Labels: fix

#3836 fix(wallet-mobile): Wait for selected wallet only sync to create notifications
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationUIHandler.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/transaction-received-notification.ts
Labels: fix

#3837 fix(wallet-mobile): Fix route path comparison for TX history screen
  apps/wallet-mobile/src/kernel/navigation.tsx
Labels: fix

#3838 fix(wallet-mobile): Treat small notification movement as a press
  apps/wallet-mobile/src/features/Notifications/useCases/common/NotificationPopup.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/SwipeOutWrapper.tsx
Labels: fix

#3839 fix(wallet-mobile): disable gestures for modals
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/components/ModalScreenWrapper/ModalScreenWrapper.stories.tsx
  apps/wallet-mobile/src/components/ModalScreenWrapper/ModalScreenWrapper.tsx
Labels: fix

#3840 fix(wallet-mobile): Fix HW message signing
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30-ledger.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip8/cip8.ts
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
Labels: fix

#3843 fix(wallet-mobile): Fix address path for message signing and TX review message parsing
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useFormattedMetadata.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.ts
Labels: fix

#3842 feat(swap): Remotely configure buying side of swap
  apps/wallet-mobile/src/features/Swap/common/useSwapConfig.ts
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/ActionsBanner.tsx
  packages/swap/package.json
  packages/swap/src/adapters/getSwapConfig.test.ts
  packages/swap/src/adapters/getSwapConfig.ts
  packages/swap/src/index.ts
Labels: feature

#3845 fix(wallet-mobile): cip30 refactor leftovers
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.ts
Labels: fix

#3847 fix(wallet-mobile): Do not break app on swap config error, safe to ignore
  apps/wallet-mobile/src/features/Swap/common/useSwapConfig.ts
Labels: fix

#3849 feat(wallet-mobile): Add FCM Token to About screen
  apps/wallet-mobile/src/components/CopyButton.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeAppSettings/About/About.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeAppSettings/About/About.json
Labels: feature

#3852 fix(wallet-mobile): Fix tx review accordion and send loading button
  apps/wallet-mobile/src/features/ReviewTx/common/Accordion.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
Labels: fix
