Repository Emurgo/yoroi, pull requests merged in 2025-08, with the labels that each got.

#4012 fix(mobile): setup wallet string
  apps/mobile/src/features/SetupWallet/SetupWalletNavigator.tsx
  apps/mobile/src/features/SetupWallet/common/PreparingWalletScreen/PreparingWalletScreen.tsx
  apps/mobile/src/features/SetupWallet/common/WalletDuplicatedModal/WalletDuplicatedModal.tsx
  apps/mobile/src/features/SetupWallet/useCases/ChooseSetupType/ChooseSetupTypeScreen.tsx
  apps/mobile/src/features/SetupWallet/useCases/CreateWallet/RecoveryPhraseScreen.tsx
  apps/mobile/src/features/SetupWallet/useCases/CreateWallet/VerifyRecoveryPhraseScreen.tsx
  apps/mobile/src/features/SetupWallet/useCases/CreateWallet/WalletDetailsScreen.tsx
  apps/mobile/src/features/SetupWallet/useCases/RestoreHwWallet/CheckNanoXScreen.tsx
  apps/mobile/src/features/SetupWallet/useCases/RestoreHwWallet/ConnectNanoXScreen.tsx
  apps/mobile/src/features/SetupWallet/useCases/RestoreHwWallet/SelectHwConnectionModal.tsx
  apps/mobile/src/features/SetupWallet/useCases/RestoreWallet/MnemonicInput/MnemonicInput.tsx
  apps/mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletDetailsScreen.tsx
  apps/mobile/src/features/SetupWallet/useCases/RestoreWallet/RestoreWalletScreen.tsx
  apps/mobile/src/kernel/i18n/locales/en-US.json
  apps/mobile/src/kernel/i18n/messages/setup-wallet.ts
  apps/mobile/src/kernel/i18n/useStrings.ts
Labels: fix

#4017 chore(mobile): restored use status bar
  apps/mobile/package-lock.json
  apps/mobile/package.json
  apps/mobile/src/kernel/navigation/AppNavigator.tsx
  apps/mobile/src/kernel/navigation/RouterContainer.tsx
  apps/mobile/src/kernel/navigation/common/helpers.tsx
  apps/mobile/src/kernel/navigation/hooks/useStatusBar.test.ts
  apps/mobile/src/kernel/navigation/hooks/useStatusBar.ts
  apps/mobile/src/kernel/navigation/types.ts
Labels: chore

#4018 chore(mobile): restored login with host (former OS)
  apps/mobile/src/features/Auth/ui/screens/LoginWithHostScreen.tsx
  apps/mobile/src/features/DevMenu/DevMenu.tsx
  apps/mobile/src/features/DevMenu/index.ts
  apps/mobile/src/kernel/navigation/AppNavigator.tsx
Labels: chore

#4022 feat(swap): adapt Muesliswap adapter to API v2 changes
  packages/swap/src/adapters/api/muesliswap/api.mocks.ts
  packages/swap/src/adapters/api/muesliswap/helpers.test.ts
  packages/swap/src/adapters/api/muesliswap/helpers.ts
  packages/swap/src/adapters/api/muesliswap/transformers.test.ts
  packages/swap/src/adapters/api/muesliswap/transformers.ts
  packages/swap/src/adapters/api/muesliswap/types.ts
Labels: fix

#4025 refactor(mobile): reapply navigation changes
  apps/mobile/package-lock.json
  apps/mobile/src/features/Dashboard/DashboardNavigator.tsx
  apps/mobile/src/features/Menu/Menu.tsx
  apps/mobile/src/features/RegisterCatalyst/CatalystNavigator.tsx
  apps/mobile/src/features/ReviewTx/ReviewTxNavigator.tsx
  apps/mobile/src/features/Scan/common/useNavigateTo.tsx
  apps/mobile/src/features/Send/common/navigation.ts
  apps/mobile/src/features/Settings/ToggleAnalyticsSettings/ToggleAnalyticsSettingsNavigator.tsx
  apps/mobile/src/features/Staking/Governance/GovernanceNavigator.tsx
  apps/mobile/src/features/Staking/Governance/common/navigation.ts
  apps/mobile/src/features/Transactions/useCases/TxHistory/ActionsBanner.tsx
  apps/mobile/src/kernel/navigation/navigation.tsx
Labels: chore

#4026 refactor(mobile): navigation update
  apps/mobile/src/WalletNavigator.tsx
  apps/mobile/src/features/Dashboard/DashboardNavigator.tsx
  apps/mobile/src/features/Discover/DiscoverNavigator.tsx
  apps/mobile/src/features/Initialization/ui/navigation/AgreementChangedNavigator.tsx
  apps/mobile/src/features/Initialization/ui/navigation/InitializationNavigator.tsx
  apps/mobile/src/features/Menu/Menu.tsx
  apps/mobile/src/features/Portfolio/NftsNavigator.tsx
  apps/mobile/src/features/Portfolio/PortfolioNavigator.tsx
  apps/mobile/src/features/RegisterCatalyst/CatalystNavigator.tsx
  apps/mobile/src/features/ReviewTx/ReviewTxNavigator.tsx
  apps/mobile/src/features/Search/SearchContext.tsx
  apps/mobile/src/features/Send/useCases/StartMultiTokenTx/StartMultiTokenTxScreen.tsx
  apps/mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/mobile/src/features/Settings/ToggleAnalyticsSettings/ToggleAnalyticsSettingsNavigator.tsx
  apps/mobile/src/features/Settings/useCases/changeWalletSettings/ManageNotifications/ManageNotificationsNavigator.tsx
  apps/mobile/src/features/Staking/Governance/GovernanceNavigator.tsx
  apps/mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/mobile/src/kernel/navigation/AppNavigator.tsx
  apps/mobile/src/kernel/navigation/common/helpers.tsx
  apps/mobile/src/kernel/navigation/hooks/useWalletNavigation.ts
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/WalletNavigator.tsx
Labels: refactor

#4035 fix(mobile): metro compiling issue
  apps/mobile/package-lock.json
  apps/mobile/package.json
Labels: fix

#4041 feat: restore notification feature with proper provider setup
  apps/mobile/PlatformShell.tsx
  apps/mobile/src/features/Exchange/common/useBuyCryptoBanner.tsx
  apps/mobile/src/features/Notifications/common/NotificationPopup.tsx
  apps/mobile/src/features/Notifications/common/hooks.ts
  apps/mobile/src/features/Notifications/useCases/ViewNotificationHistory/ViewNotificationHistoryScreen.tsx
  apps/mobile/src/features/Staking/Governance/useCases/useGovernanceBanner.tsx
  apps/mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/mobile/src/features/Transactions/common/HeaderRightHistory.tsx
  apps/mobile/src/features/Transactions/useCases/TxHistory/TxHistory.tsx
  apps/mobile/src/features/Transactions/useCases/UtxoConsolidation/UtxoConsolidation/useUtxoConsolidationBanner.tsx
  apps/mobile/src/kernel/i18n/locales/en-US.json
  apps/mobile/src/kernel/i18n/messages/exchange.ts
  apps/mobile/src/kernel/i18n/messages/notifications.ts
  apps/mobile/src/kernel/i18n/messages/staking.ts
  apps/mobile/src/kernel/i18n/useStrings.ts
  apps/mobile/src/kernel/navigation/AppNavigator.tsx
  apps/mobile/src/kernel/navigation/RouterContainer.tsx
  apps/mobile/src/kernel/navigation/WalletTabNavigator.tsx
  apps/mobile/src/ui/Button/Button.tsx
  apps/mobile/src/ui/YoroiLogo/YoroiLogo.tsx
Labels: feature

#4043 fix: restore discover tabs behavior and fix styling issues
  apps/mobile/src/features/Discover/common/LabelSingleAddress.tsx
  apps/mobile/src/features/Discover/useCases/SelectDappFromList/SelectDappFromListScreen.tsx
  apps/mobile/src/kernel/i18n/messages/discover.ts
Labels: fix

#4050 chore: dev 2 peer dep lock files
  apps/mobile/package-lock.json
  packages/blockchains/package-lock.json
  packages/claim/package-lock.json
  packages/setup-wallet/package-lock.json
  packages/transfer/package-lock.json
Labels: chore

#4051 fix(mobile): missing translations
  apps/mobile/src/kernel/i18n/locales/en-US.json
Labels: fix

#4077 feature(mobile): tx review integration
  apps/mobile/App.tsx
  apps/mobile/package-lock.json
  apps/mobile/package.json
  apps/mobile/src/features/ReviewTx/common/ConfirmRawTxWithHw.tsx
  apps/mobile/src/features/ReviewTx/common/hooks/useFormattedTx.tsx
  apps/mobile/src/features/ReviewTx/common/hooks/useLegacyOnConfirm.tsx
  apps/mobile/src/features/ReviewTx/common/operations.tsx
  apps/mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Metadata/MetadataTab.tsx
  apps/mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Mint/MintTab.tsx
  apps/mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReferenceInputs/ReferenceInputs.tsx
  apps/mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.tsx
  apps/mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/mobile/src/kernel/navigation/WalletNavigator.tsx
  apps/mobile/src/kernel/navigation/types.tsx
  apps/mobile/src/ui/ConfirmTxWithHwModal/ConfirmTxWithHwModal.tsx
  apps/mobile/src/ui/ConfirmTxWithOsModal/ConfirmTxWithOsModal.tsx
  apps/mobile/src/ui/ConfirmTxWithSpendingPasswordModal/ConfirmTxWithSpendingPasswordModal.tsx
Labels: feature

#4088 fix(portfolio): strings and zoom media
  mobile/package-lock.json
  mobile/package.json
  mobile/src/features/Portfolio/screens/PortfolioTokensList/PortfolioWalletTokenList/ListMediaGalleryScreen/ZoomMediaImageScreen.tsx
  mobile/src/kernel/i18n/messages/portfolio.ts
  mobile/src/kernel/i18n/useStrings.ts
Labels: fix

#4093 fix(mobile): tests
  mobile/jest.setup.js
  mobile/package-lock.json
  mobile/package.json
  mobile/src/features/WalletManager/wallet-manager.test.ts
  mobile/src/kernel/crypto/decrypt-data.test.ts
  mobile/src/kernel/crypto/encrypt-data.test.ts
  mobile/src/kernel/crypto/random-hex-string.test.ts
  mobile/src/kernel/metrics/metricsManager.test.tsx
  mobile/src/kernel/metrics/metricsManager.tsx
  mobile/src/wallets/cardano/getMinAmounts.test.ts
Labels: fix

#4095 fix(mobile): several fixes
  mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/CreateExchangeOrderScreen.tsx
  mobile/src/features/Exchange/useCases/CreateExchangeOrderScreen/LoadingLink/ErrorScreen.tsx
  mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Overview/OverviewTab.tsx
  mobile/src/features/ReviewTx/useCases/ShowFailedTxScreen/FailedTxScreen.tsx
  mobile/src/features/ReviewTx/useCases/ShowSubmittedTxScreen/SubmittedTxScreen.tsx
  mobile/src/features/Swap/common/SwapProvider.tsx
  mobile/src/features/Swap/useCases/ListOrders/ListOrders.tsx
  mobile/src/kernel/i18n/locales/en-US.json
  mobile/src/kernel/i18n/messages/swap.ts
  mobile/src/kernel/i18n/useStrings.ts
Labels: fix

#4097 fix(mobile): api
  mobile/packages/staking/governance/config.ts
Labels: fix

#4096 fix(mobile): Wrong pin alert
  mobile/package-lock.json
  mobile/src/features/Auth/context/AuthProvider.tsx
  mobile/src/features/Auth/ui/screens/LoginWithPinScreen.tsx
  mobile/src/features/Temporal_To_Remove/Auth/TempPinLoginScreen.tsx
  mobile/src/features/Temporal_To_Remove/InitialScreen/InitialScreenNavigatorNavigator.tsx
  mobile/src/features/Temporal_To_Remove/Search/TempTestSearchScreen.tsx
Labels: fix

#4103 fix: Restore keypad and strings
  mobile/src/features/Auth/ui/shared/PinInput/PinInput.tsx
  mobile/src/kernel/i18n/messages/send.ts
  mobile/src/kernel/i18n/messages/swap.ts
  mobile/src/kernel/i18n/messages/transactions.ts
  mobile/src/kernel/i18n/messages/ui.ts
Labels: fix
