Repository Emurgo/yoroi, pull requests merged in 2025-03, with the labels that each got.

#3855 fix(wallet-mobile): Minor design adjustments
  apps/wallet-mobile/src/components/Modal/ModalScreen.tsx
  apps/wallet-mobile/src/components/TextInput/TextInput.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeAppSettings/About/About.json
Labels: fix

#3857 chore(wallet-mobile): Drop local notifications feature flag
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/kernel/features.ts
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.json
Labels: chore

#3858 chore(wallet-mobile): Add google services config to production folder
  apps/wallet-mobile/android/app/src/production/google-services.json
Labels: chore

#3856 fix(wallet-mobile): Use explorer data when pool info is missing
  apps/wallet-mobile/src/legacy/Dashboard/DashboardNavigator.tsx
  apps/wallet-mobile/src/legacy/Dashboard/StakePoolInfo.tsx
  apps/wallet-mobile/src/legacy/Dashboard/StakePoolInfos.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/DashboardNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/StakePoolInfo.json
Labels: fix

#3860 feat(notifications, wallet-mobile): Add timer to in-app notifications
  apps/wallet-mobile/src/components/Icon/Icon.stories.tsx
  apps/wallet-mobile/src/components/Icon/Time.tsx
  apps/wallet-mobile/src/components/Icon/index.ts
  apps/wallet-mobile/src/features/Notifications/useCases/common/SwipeOutWrapper.tsx
  apps/wallet-mobile/src/features/Settings/SettingsCollateralItem.tsx
  apps/wallet-mobile/src/features/Settings/SettingsItems.tsx
  apps/wallet-mobile/src/features/Settings/SettingsNotificationDurationItem.tsx
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageNotificationDisplayDuration/ManageNotificationDisplayDurationScreen.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageNotificationDisplayDuration/strings.ts
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/LanguageProvider.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeWalletSettings/ManageNotificationDisplayDuration/strings.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.json
  packages/notifications/src/notification-manager.test.ts
  packages/notifications/src/notification-manager.ts
  packages/notifications/src/translators/reactjs/useNotificationsConfig.ts
  packages/notifications/src/translators/reactjs/useUpdateNotificationsConfig.ts
  packages/types/src/notifications/manager.ts
Labels: feature

#3862 feature(banners): banners package
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/package.json
  apps/wallet-mobile/src/features/Banners/common/DismissableBanner.tsx
  apps/wallet-mobile/src/features/Banners/common/should-show-drep-consider-delegating.test.ts
  apps/wallet-mobile/src/features/Banners/common/should-show-drep-consider-delegating.tsx
  apps/wallet-mobile/src/features/Banners/common/types.ts
  apps/wallet-mobile/src/features/Banners/useCases/ShowBannerDRepConsiderDelegating.tsx
  apps/wallet-mobile/src/features/Dev/Playground.tsx
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/helpers.tsx
  apps/wallet-mobile/src/kernel/constants.ts
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  codecov.yml
  metro.config.js
  packages/banners/.dependency-cruiser.js
  packages/banners/.gitignore
  packages/banners/.watchmanconfig
  packages/banners/README.md
  packages/banners/babel.config.js
  packages/banners/dependency-graph.svg
  packages/banners/jest.setup.js
  packages/banners/package.json
  packages/banners/scripts/flowgen.sh
  packages/banners/src/banners-manager.test.ts
  packages/banners/src/banners-manager.ts
  packages/banners/src/index.ts
  packages/banners/src/translators/reactjs/BannersProvider.test.tsx
  packages/banners/src/translators/reactjs/BannersProvider.tsx
  packages/banners/src/translators/reactjs/useBanner.test.ts
  packages/banners/src/translators/reactjs/useBanner.ts
  packages/banners/tsconfig.build.json
  packages/banners/tsconfig.json
  packages/common/src/index.ts
  packages/common/src/numbers/to-number.test.ts
  packages/common/src/numbers/to-number.ts
  packages/types/src/banners/banners.ts
  packages/types/src/index.ts
  scripts/install-dev-pkg.sh
  scripts/install-pkgs.sh
  yoroi.code-workspace
Labels: feature

#3863 feat(wallet-mobile): Add delegate to Yoroi banners
  apps/wallet-mobile/.storybook/storybook.requires.js
  apps/wallet-mobile/src/components/DismissableView.tsx
  apps/wallet-mobile/src/features/Banners/common/DelegateToYoroiDRepBanner/DelegateToYoroiDRepBanner.stories.tsx
  apps/wallet-mobile/src/features/Banners/common/DelegateToYoroiDRepBanner/DelegateToYoroiDRepBanner.tsx
  apps/wallet-mobile/src/features/Banners/common/strings.ts
  apps/wallet-mobile/src/features/Banners/common/types.ts
  apps/wallet-mobile/src/features/Banners/illustrations/GovernanceBackground.tsx
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsGovernanceBanner.tsx
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsStakingCenterBanner.tsx
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsTxHistoryBanner.tsx
  apps/wallet-mobile/src/features/Banners/useCases/ShowBannerDRepConsiderDelegating.tsx
  apps/wallet-mobile/src/features/Dev/Playground.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/primary-token-price-changed-notification.ts
  apps/wallet-mobile/src/features/Portfolio/common/MediaDetailsScreen/MediaDetailsScreen.tsx
  apps/wallet-mobile/src/features/Portfolio/common/PortfolioTokenActivityProvider.tsx
  apps/wallet-mobile/src/features/Portfolio/common/hooks/useGetPortfolioTokenChart.ts
  apps/wallet-mobile/src/features/RegisterCatalyst/common/hooks.ts
  apps/wallet-mobile/src/features/ReviewTx/common/TokenDetails.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeAppSettings/ChangeNetwork/ChangeNetworkScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/navigation.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/ChangeVote/ChangeVoteScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/features/Transactions/TxHistoryNavigator.tsx
  apps/wallet-mobile/src/features/Transactions/useCases/TxHistory/TxHistory.tsx
  apps/wallet-mobile/src/features/WalletManager/common/hooks/useLaunchWalletAfterSyncing.tsx
  apps/wallet-mobile/src/features/WalletManager/wallet-manager.ts
  apps/wallet-mobile/src/kernel/constants.ts
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/types.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/usePrimaryTokenActivity.tsx
  apps/wallet-mobile/src/yoroi-wallets/mocks/wallet.ts
  apps/wallet-mobile/translations/messages/src/features/Banners/ConsiderDelegatingToYoroiBanner/strings.json
  apps/wallet-mobile/translations/messages/src/features/Banners/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/Portfolio/common/MediaDetailsScreen/MediaDetailsScreen.json
  apps/wallet-mobile/translations/messages/src/features/Transactions/TxHistoryNavigator.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
  packages/banners/src/helpers/should-show-drep2us-on-governance.test.ts
  packages/banners/src/helpers/should-show-drep2us-on-governance.ts
  packages/banners/src/helpers/should-show-drep2us-on-staking-center.test.ts
  packages/banners/src/helpers/should-show-drep2us-on-staking-center.ts
  packages/banners/src/helpers/should-show-drep2us-on-tx-history.test.ts
  packages/banners/src/helpers/should-show-drep2us-on-tx-history.ts
  packages/banners/src/index.ts
  packages/common/src/index.ts
  packages/common/src/time/time.test.ts
  packages/common/src/time/time.ts
  packages/staking/src/governance/config.ts
  packages/staking/src/governance/index.ts
  packages/types/src/banners/banners.ts
  packages/types/src/index.ts
Labels: feature

#3866 chore(wallet-mobile): Change Yoroi Drep CTA label
  apps/wallet-mobile/src/features/Banners/common/strings.ts
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
Labels: chore

#3868 fix(wallet-mobile): Do not display notifications for intrawallet transactions
  apps/wallet-mobile/src/features/Notifications/useCases/common/transaction-received-notification.ts
Labels: fix

#3867 feat(wallet-mobile): Redesign governance screen
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsGovernanceBanner.tsx
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsStakingCenterBanner.tsx
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsTxHistoryBanner.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/Action/Action.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/helpers.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/strings.ts
  apps/wallet-mobile/src/features/Staking/Governance/useCases/Home/HomeScreen.tsx
  apps/wallet-mobile/src/kernel/i18n/locales/en-US.json
  apps/wallet-mobile/src/legacy/Dashboard/Dashboard.tsx
  apps/wallet-mobile/translations/messages/src/features/Banners/common/strings.json
  apps/wallet-mobile/translations/messages/src/features/Staking/Governance/common/strings.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/Dashboard.json
Labels: feature

#3869 chore(banners): Only show DRep promotion on mainnet
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsGovernanceBanner.tsx
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsStakingCenterBanner.tsx
  apps/wallet-mobile/src/features/Banners/useCases/ConsiderDRepToUsTxHistoryBanner.tsx
  packages/banners/src/helpers/should-show-drep2us-on-governance.test.ts
  packages/banners/src/helpers/should-show-drep2us-on-governance.ts
  packages/banners/src/helpers/should-show-drep2us-on-staking-center.test.ts
  packages/banners/src/helpers/should-show-drep2us-on-staking-center.ts
  packages/banners/src/helpers/should-show-drep2us-on-tx-history.test.ts
  packages/banners/src/helpers/should-show-drep2us-on-tx-history.ts
Labels: chore

#3872 fix(wallet-mobile): Redirect to TX history from governance centre when navigating back
  apps/wallet-mobile/src/features/Menu/Menu.tsx
  apps/wallet-mobile/src/features/Staking/Governance/GovernanceNavigator.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
Labels: fix

#3877 chore(notifications): Increase default display duration to 8 seconds
  packages/notifications/src/notification-manager.test.ts
  packages/notifications/src/notification-manager.ts
Labels: chore

#3878 fix(wallet-mobile): missing local vote delegation certificate management
  apps/wallet-mobile/src/features/Discover/common/ledger.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30-ledger.ts
Labels: fix

#3880 fix(wallet-mobile): reselect staking pool
  apps/wallet-mobile/src/legacy/Staking/StakingCenter/StakingCenter.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Staking/StakingCenter/StakingCenter.json
Labels: fix

#3886 refactor(types, explorers): rename adaex, and refactor explorer links
  apps/wallet-mobile/src/components/Button/Button.tsx
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokenDetails/PortfolioTokenInfo/Overview/Overview.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/ExplorerInfoLinks.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/PoolDetails.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/TokenDetails.tsx
  packages/explorers/README.md
  packages/explorers/src/explorer-manager.test.ts
  packages/explorers/src/explorer-manager.ts
  packages/types/src/explorers/explorer.ts
Labels: fix, refactor

#3887 fix(wallet): portfolio token list filter and sort
  apps/wallet-mobile/src/features/Portfolio/useCases/PortfolioTokensList/PortfolioWalletTokenList/PortfolioWalletTokenList.tsx
Labels: fix

#3888 fix(wallet-mobile): max amounts banner
  apps/wallet-mobile/src/components/ErrorPanel/ErrorPanel.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/SelectTokenFromListScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/AddToken/Show/MaxAmountsPerTx.tsx
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/AddToken/Show/MaxAmountsPerTx.json
Labels: fix
