Repository Emurgo/yoroi, pull requests merged in 2025-01, with the labels that each got.

#3778 fix(wallet-mobile): tx review collateral and staking ctas
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/src/legacy/Dashboard/ShowFailedTxScreen/FailedTxScreen.tsx
  apps/wallet-mobile/src/legacy/Dashboard/ShowSubmittedTxScreen/SubmittedTxScreen.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/ShowFailedTxScreen/FailedTxScreen.json
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/ShowSubmittedTxScreen/SubmittedTxScreen.json
Labels: fix

#3779 fix(wallet-button): send max quantity format
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/EditAmount/EditAmountScreen.tsx
Labels: fix

#3780 fix(wallet-mobile): error boundary button layout
  apps/wallet-mobile/src/components/ErrorBoundary/ErrorBoundary.tsx
Labels: fix

#3782 fix(wallet-mobile): ledger cancel swap order
  apps/wallet-mobile/src/features/Discover/common/ledger.ts
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithHW.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30-ledger.ts
  translations/messages/src/AppNavigator.json
  translations/messages/src/WalletNavigator.json
  translations/messages/src/features/Auth/OsLoginScreen/OsLoginScreen.json
  translations/messages/src/features/Auth/PinLoginScreen/PinLoginScreen.json
  translations/messages/src/features/Auth/common/hooks.json
  translations/messages/src/features/Initialization/DarkThemeAnnouncement/DarkThemeAnnouncement.json
  translations/messages/src/features/SetupWallet/SetupWalletNavigator.json
  translations/messages/src/kernel/i18n/global-messages.json
Labels: fix

#3784 fix(wallet-mobile): Remove swap info link from open order cancel modal
  apps/wallet-mobile/android/build.gradle
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/OpenOrders.tsx
Labels: fix

#3785 fix(wallet-mobile): tx review uat overview tab
  apps/wallet-mobile/src/components/Info/Info.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/CopiableText.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/Overview/OverviewTab.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.tsx
Labels: fix

#3787 fix(wallet-mobile): Adjust staking icons dark background
  apps/wallet-mobile/src/components/Icon/TotalAda.tsx
  apps/wallet-mobile/src/components/Icon/TotalDelegated.tsx
  apps/wallet-mobile/src/components/Icon/TotalReward.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/UserSummary.json
Labels: fix

#3786 fix(wallet-mobile): Add padding for swap pool actions
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/CreateOrder/EditPool/ShowPoolActions.tsx
Labels: fix

#3788 fix(wallet-mobile): Critical button color text
  apps/wallet-mobile/src/components/Button/Button.tsx
Labels: fix

#3790 fix(wallet-mobile): tx review uat utxos tab
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/ReviewTx.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTx/UTxOs/UTxOsTab.tsx
Labels: fix

#3791 feat(wallet-mobile): Add slide in and out animations
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationUIHandler.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/NotificationsDevScreen.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/NotificationPopup.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/NotificationStack.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/SwipeOutWrapper.tsx
  apps/wallet-mobile/translations/messages/src/legacy/Dashboard/UserSummary.json
  packages/notifications/src/translators/reactjs/useReceivedNotificationEvents.ts
Labels: feature

#3795 fix(wallet-mobile): Fix dark variant of notifications
  apps/wallet-mobile/src/features/Notifications/useCases/common/NotificationPopup.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/SwipeOutWrapper.tsx
Labels: fix

#3796 feat(wallet-mobile): Add HW message signing support
  apps/wallet-mobile/src/features/Discover/common/HWNotSupportedModal.tsx
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30-ledger.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/hw/hw.ts
Labels: feature

#3798 feat(wallet-mobile): Add feature flag for push notifications
  apps/wallet-mobile/src/AppNavigator.tsx
  apps/wallet-mobile/src/features/Notifications/useCases/common/hooks.ts
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/kernel/features.ts
  apps/wallet-mobile/translations/messages/src/AppNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.json
Labels: feature

#3794 refactor(wallet-mobile): tx review cbor signing generalization
  apps/wallet-mobile/src/components/ConfirmTxWithOsModal/ConfirmTxWithOsModal.tsx
  apps/wallet-mobile/src/components/ConfirmTxWithSpendingPasswordModal/ConfirmTxWithSpendingPasswordModal.tsx
  apps/wallet-mobile/src/features/Discover/common/ConfirmHWConnectionModal.tsx
  apps/wallet-mobile/src/features/Discover/common/hooks.tsx
  apps/wallet-mobile/src/features/Discover/useDappConnectorManager.tsx
  apps/wallet-mobile/src/features/RegisterCatalyst/useCases/ConfirmPin/ConfirmPin.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useLegacyOnConfirm.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useOnConfirm.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/usePromptRootKey.tsx
  apps/wallet-mobile/src/features/ReviewTx/common/hooks/useSignTxWithHW.tsx
  apps/wallet-mobile/src/features/ReviewTx/useCases/ReviewTxScreen/ReviewTxScreen.tsx
  apps/wallet-mobile/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/ManageCollateral/ManageCollateralScreen.tsx
  apps/wallet-mobile/src/features/Staking/Governance/common/helpers.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTx.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithOs.tsx
  apps/wallet-mobile/src/features/Swap/common/ConfirmRawTx/ConfirmRawTxWithPassword.tsx
  apps/wallet-mobile/src/features/Swap/useCases/StartOrderSwapScreen/ListOrders/OpenOrders.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/src/yoroi-wallets/cardano/cip30/cip30.ts
  apps/wallet-mobile/translations/messages/src/features/Send/useCases/ListAmountsToSend/ListAmountsToSendScreen.json
Labels: refactor

#3802 feat(wallet-mobile): Add amplitude tracking for notifications
  apps/wallet-mobile/ampli.json
  apps/wallet-mobile/src/features/Notifications/useCases/common/NotificationPopup.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/kernel/metrics/ampli/index.ts
  apps/wallet-mobile/src/kernel/metrics/metricsManager.test.tsx
  apps/wallet-mobile/src/kernel/metrics/metricsManager.tsx
  apps/wallet-mobile/src/kernel/metrics/mocks.ts
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.json
Labels: feature

#3803 fix(wallet-mobile): clear token info cache when resync
  apps/wallet-mobile/ios/Podfile.lock
  apps/wallet-mobile/src/features/Settings/SettingsScreenNavigator.tsx
  apps/wallet-mobile/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.tsx
  apps/wallet-mobile/src/kernel/navigation.tsx
  apps/wallet-mobile/src/yoroi-wallets/cardano/cardano-wallet.ts
  apps/wallet-mobile/translations/messages/src/features/Settings/SettingsScreenNavigator.json
  apps/wallet-mobile/translations/messages/src/features/Settings/useCases/changeWalletSettings/WalletSettingsScreen.json
Labels: fix

#3806 fix(wallet-mobile): Request android permissions only on android
  apps/wallet-mobile/src/features/Notifications/useCases/common/hooks.ts
Labels: fix
